### ISSUE TITLE
Multiple MCU pin declaration

### ISSUE THREAD

**Issue by barnard704344** [Klipper3d/klipper#1015]
Hi there, 
I am using 4 separate arduino nano's with a custom board and trying to make use of multiple mcu's, but I keep getting the following: **"pin ar4 used multiple times in config"**
 The boards are identical and have one stepper attached to each arduino.
any way around it ? or am i missing something?

thanks.

Firmware version: v0.6.0-668-gef4f84e

**Klippy.log**-----
File "/home/pi/klipper/klippy/pins.py", line 253, in setup_pin
    pin_params = self.lookup_pin(pin_desc, can_invert, can_pullup)
  File "/home/pi/klipper/klippy/pins.py", line 241, in lookup_pin
    raise error("pin %s used multiple times in config" % (pin,))
error: pin ar4 used multiple times in config
pin ar4 used multiple times in config
Once the underlying issue is corrected, use the "RESTART"
command to reload the config and restart the host software.
Printer is halted
Klipper state: Not ready

**My printer config is as follows:**

# controls the Z steppers, Heatbed Mosfet
[mcu]
serial: /dev/serial/by-path/platform-3f980000.usb-usb-0:1.5:1.0-port0
pin_map: arduino

# The "yboard" micro-controller controls Y stepper, Y endstop, Heatbed Thermistor
[mcu yboard]
serial: /dev/serial/by-path/platform-3f980000.usb-usb-0:1.4:1.0-port0
pin_map: arduino

# The "xboard" micro-controller controls X stepper, Z probe
[mcu xboard]
serial: /dev/serial/by-path/platform-3f980000.usb-usb-0:1.3:1.0-port0
pin_map: arduino

# The " Eboard" micro-controller controls Extruder, X endstop, Layer Fan, Extruder Mosfet
[mcu eboard]
serial: /dev/serial/by-path/platform-3f980000.usb-usb-0:1.2:1.0-port0
pin_map: arduino

[stepper_x]
step_pin: xboard:ar4
dir_pin: xboard:ar7
enable_pin: xboard:ar8
step_distance: .0125
endstop_pin: xboard:ar2
position_endstop: 0
position_max: 200
homing_speed: 50

[stepper_y]
step_pin: yboard:ar4
dir_pin: yboard:ar7
enable_pin: yboard:ar8
step_distance: .0125
endstop_pin: yboard:ar2
position_endstop: 0
position_max: 200
homing_speed: 50

[stepper_z]
step_pin: ar4
dir_pin: ar7
enable_pin: ar8
step_distance: .0025
endstop_pin: ar2
position_endstop: 0.5
position_max: 200

[extruder]
step_pin: eboard:ar4
dir_pin: eboard:ar7
enable_pin: eboard:ar8
step_distance: .002
nozzle_diameter: 0.400
filament_diameter: 1.750
heater_pin: xboard:ar5
sensor_type: EPCOS 100K B57560G104F

**Comment by yschroeder** [comment]
Generally, it is possible to use 4 identical boards and also the same pins on those boards. Prefixing them with the board name is correct. I have a similar looking config for 4 STM32F103 boards. I scanned through your configuration and it looks correct to me.

Either you use the pin `ar4` elsewhere in your configuration (which you did not post) or there is a bug in Klipper. To be clear: You are allowed to use every pin (for example `ar4`) once without prefix and once with every of your defined prefixes from the additional MCUs (`xboard`, `yboard`, `eboard`).

**Comment by paulsboutique** [comment]
That is the full config except for the printer declaration. It does not matter what pin is defined first or whether i move them around, it gives the same result.

**Comment by paulsboutique** [comment]
Thanks yschroeder, 

i missed a double declaration at the end of the file for e_board:ar4
#[fan]
#pin: e_board:ar4

It was late :)
