### ISSUE TITLE
Move out of range

### ISSUE THREAD

**Issue by YaronSoffer** [Klipper3d/klipper#1024]
My guess this is happing if you have done BED_MESH_CALIBRATION ( my bed is not level at all).
somehow the calculation leads to a value of Z below zero.
Here is an example of a failure :
Move out of range: 165.313 85.200 -0.531
you can work around this by setting the following to negative value. I had set mine to almost minus one millimeter. Add the following to Z section e.g [stepper_z].
position_min: -0.99
my guess this can be done in the software ( taking the lowest value from the BED_MESH_CALIBRATION).

**Comment by cosminr86** [comment]
Try something like position_min: -2

**Comment by KevinOConnor** [comment]
In order for us to assist, you'll need to attach the klipper log file from the event - see: https://github.com/KevinOConnor/klipper/blob/master/docs/Contact.md

**Comment by YaronSoffer** [comment]
[klippy.log](https://github.com/KevinOConnor/klipper/files/2705916/klippy.log)
Here is the log as requested . In this case the error occur on the folllowing:
"Move out of range: 180.791 16.605 -1.021 [28.758]"
cosminr86 - you are right need to put it on -2 .
I had to RESTART the system ,hope that this did not initated the log from the start. I can recreate if needed.

**Comment by KevinOConnor** [comment]
As noted, the log indicates you need to change the position_min to allow a move below -1.021 .

-Kevin

**Comment by YaronSoffer** [comment]
You are correct but the question remains? why does it happen ? in the gcode there is no indication of a move below zero levels? my wild guess is that the BED_MESH_CALIBRATION result is added to the z height and then you get a negative value as the height. Can the warning take into consideration that the values are not real?

**Comment by KevinOConnor** [comment]
Yes - the position_min/position_max checks are done relative to the linear rail, not relative to the gcode parameters.

-Kevin

**Comment by YaronSoffer** [comment]
Is it possible to notify the user what is the lowest value ? Maybe set the
"position_min" in the config file ( with some added safety value )?

**Comment by Tjiaepbu** [comment]
Send: N52604 G91*20
Send: N52605 G1 E-1 F300*0
Recv: ok
Send: N52606 G1 Z+0.5 E-5 X-20 Y-20 F9000*70
Recv: ok
Send: N52607 G90*22
Recv: !! Move out of range: -0.553 36.071 52.132 [44137.946]
Changing monitoring state from "Printing" to "Cancelling"

What this meens? Got always this error after print, and the hot end stops and melts a crater to the print.

**Comment by jakep82** [comment]
It looks like your end gcode is telling the printer to make a move out of range.  It's generally not a good idea to move X or Y with relative positioning (G91) at the end of a print.  You're telling the printer to move -20mm in X and Y, regardless of where the nozzle is at the end of the print.  If the nozzle is less than 20mm from your X or Y min_position, it will cause this error.  You should only move Z and E after the G91, then switch back to absolute positioning with a G90 before moving X and Y.

**Comment by Tjiaepbu** [comment]
Thats just the cura end code. Do i need to chance it somehow?

pe 22. helmik. 2019 klo 22.17 jakep82 <notifications@github.com> kirjoitti:

**Comment by jakep82** [comment]
Yes, you need to change your end gcode.

**Comment by YaronSoffer** [comment]
I found another work around except setting the value to -2 . Try installing
the bed visualizer plugin from octoprint plugins.
Youcan try to achieve better bed leveling manually.  Or you can see the
lowest value of your bed in the visualizer and set it accordingly.
