### ISSUE TITLE
ADC out of range

### ISSUE THREAD

**Issue by CharlesStArnault** [Klipper3d/klipper#1034]
After trying to setup my second extruder, I keep getting the MCU shutdown: ADC out of range error. Why is this happening, and how do I fix this?

[klippy.txt](https://github.com/KevinOConnor/klipper/files/2705583/klippy.txt)

**Comment by jakep82** [comment]
This would imply you don't have the thermistor for you second extruder plugged in, it's configured incorrectly, or the thermistor has failed.
