### ISSUE TITLE
Thermistor resistance reading

### ISSUE THREAD

**Issue by cosminr86** [Klipper3d/klipper#1123]
Hi.
There is a way to read the thermistor resistance at different temps? 
I saw that marlin had this feature. I want to calibrate my temps and I don't really want to flash marlin. 

https://youtu.be/brl1weuD8bs

**Comment by KevinOConnor** [comment]
Not currently.  It's certainly possible to extend the code to add that feature if someone wishes to work on it.

-Kevin
