### ISSUE TITLE
Missing info in description for bed_mesh Move Splitting

### ISSUE THREAD

**Issue by ld3300** [Klipper3d/klipper#4384]
On line 172 of [klipper/docs/Bed_Mesh.md](https://github.com/KevinOConnor/klipper/blob/master/docs/Bed_Mesh.md#move-splitting) under the description for "### Move Splitting"

Current sentence: "Long moves must be and split into smaller moves
to correctly follow the shape of the bed."

It feels there is a word or statement missing in this location: "Long moves must be (????????) and split into smaller moves
to correctly follow the shape of the bed."

-David

[klippy.log](https://github.com/KevinOConnor/klipper/files/6643128/klippy.log)

**Comment by Sineos** [comment]
I'd guess rather the "and" is surplus

**Comment by KevinOConnor** [comment]
I reworded that paragraph (commit 6e87befa).

-Kevin
