### ISSUE TITLE
Update Documentation to use CMD to ssh instead of PuTTY on Windows / Also FileZilla for scp

### ISSUE THREAD

**Issue by ChaosBlades** [Klipper3d/klipper#4433]
The documentation states....

> If using a Linux or MacOS desktop, then the “ssh” software should already be installed on the desktop. There are free ssh clients available for other desktops (eg, PuTTY). Use the ssh utility to connect to the Raspberry Pi (ssh pi@octopi – password is “raspberry”) and run the following commands:

"ssh" software is already installed on Windows as well and has been for many years. You can simply open CMD and type `ssh pi@octopi.local` just like you can do on Linux/BSD/MacOS Terminal. No reason to have the user download additional software when it is not needed.

Edit:

> The SSH client is installed by default on Windows Server 2019, Windows 10 1809 and newer builds.

Windows 10 1809 reached End of Life in November 10, 2020. Everyone should have this installed.

Edit2:
In addition FileZilla is supported on Linux, BSD, MacOS, and Windows. So one software can be used for all platforms instead of confusing people by telling them to install software that is only for specific platforms.

**Comment by ChaosBlades** [comment]
*Activity*

**Comment by dxgldotorg** [comment]
Is SSH pre-installed or do you have to add it as an optional feature in Windows 10/11?

**Comment by charlespick** [comment]
@dxgldotorg yes it's pre-installed

@ChaosBlades documentation issues almost never go anywhere. Write up the proposed documentation changes yourself and open a pull request. It's a fairly sensible update so my guess is it'll get merged.
