### ISSUE TITLE
Move out of range: 250.012 0.000 2.000 [0.000]

### ISSUE THREAD

**Issue by RaoulFabisch** [Klipper3d/klipper#4706]
When starting a print I often get this error: Move out of range: 250.012 0.000 2.000 [0.000] 

Sometimes it starts when restarting the print often enough, but I guess that is not how it should behave. Hope that there is a quick fix for this problem.

[klippy.txt.txt](https://github.com/KevinOConnor/klipper/files/7191515/klippy.txt.txt)

**Comment by dmbutyugin** [comment]
When exactly does this happen? My 2 cents: in the config you have
```
[stepper_x]
endstop_pin = tmc2209_stepper_x:virtual_endstop
position_endstop = 250
position_max = 250
```
The toolhead appears to be outside of the allowed range of [0, 250] on X axis at 250.012. But I assume it is not how your gcode commands it? Does it happen after homing, or bed meshing? If it happens just mid-print, I'd double check gcode.

**Comment by florian-senn** [comment]
Maybe forgot to G21 set metric values?

**Comment by KevinOConnor** [comment]
Best to raise this on Klipper Discord or Discourse.

-Kevin

**Comment by schnello** [comment]
Hello.

[250.012 0.000 2.000 [0.000]]

This happens if you use sensorless homing and you start the homing process if the toolhead is parked directly at the frame. 

Regards

**Comment by embedded-iot4me** [comment]
Hello, 

after updating to the latest FW (v0.9.1-780-g7a02cde4), I got the **move out of range -0.013 -0.013 15.000 [0.000]** message by sending a "simple" G28 (home) command. I was able to mitigate this behavior by changing the value for position_endstop: 0 to 1 (below: stepper_x / stepper_y in printer.cfg)

best regards,
Ulf
