### ISSUE TITLE
Buzzer support on STM32F103 Creality boards

### ISSUE THREAD

**Issue by Kieraneasdale** [Klipper3d/klipper#4726]
Hi there, could someone add default buzzer support to printer-creality-ender3pro-2020.cfg and V2? I just dont know the pin number

**Comment by Kieraneasdale** [comment]
Some is wrong here:

https://github.com/Klipper3d/klipper/blob/master/config/printer-creality-ender3pro-2020.cfg

This shows PB13 being assigned to display:

sclk_pin: PB13

**Comment by Kieraneasdale** [comment]
![Screenshot 2021-09-28 120732](https://user-images.githubusercontent.com/45006607/135075811-8cd006c1-e112-44f8-a7f4-0ba5fdb68f88.png)

According to the Schem, is is the buzzer though

**Comment by Woodcat64** [comment]
It's working for me. I have E3v2 with Creality Dwin screen connected to RPi so I don't use the [display] section in printer.cfg.
https://github.com/Klipper3d/klipper/blob/master/config/printer-creality-ender3-v2-2020.cfg. With the Dwin screen, that pin is directly connected to the buzzer inside the screen.

According to this, the old screen is using pin PC6. But you know, it may be incorrect!
https://fabrizio.zellini.org/wp-content/uploads/2019/05/ender3dvsanet3d.png

**Comment by Kieraneasdale** [comment]
ok so for myself on the stock display with the ender 2 Pro 2020 the correct pin was PC6
