### ISSUE TITLE
Heater Issue After Upgrade

### ISSUE THREAD

**Issue by FlatEarthDave** [Klipper3d/klipper#4758]
Everything was working fine with my Ender 6, until I updated to the latest version of Klipper, and how I get an error about the heater not heating as expected. I hadn't changed anything else, and I wouldn't have ever got the error of I only printed PLA, as the error only comes up at around 225°C. I do not believe this to be a problem with my setup, as I have completely deleted and reinstalled everything, checked all the wiring, replaced thermistors with new ones, and still the error persists. Like I said, if I never got the temp past 220°C, I world never get the error, so I feel as though that is why the issue is not so widespread - people are printing in mostly PLA. It seems stupid to just disable the verify_heater check, because what if there is a real problem?

**Comment by Sineos** [comment]
3rd print with ASA @ 260°C running on v0.10.0-1-gb806d71e. Cannot confirm your observations. Please revert to discourse or discord as per https://www.klipper3d.org/Contact.html for further discussion
