### ISSUE TITLE
config temperature sensor_type lm75 case sensitive

### ISSUE THREAD

**Issue by findus4fun** [Klipper3d/klipper#4767]
Hello, I tried to use lm75 temperature sensor and got the following error:

Unknown temperature sensor '**lm75**'

looking at 

klippy/extras/lm75.py  

I figured out that I have to write it in uppercase

def load_config(config):
    # Register sensor
    pheaters = config.get_printer().load_object(config, "heaters")
    pheaters.add_sensor_factory("**LM75**", LM75)

So either the docs are wrong (**lm75**) or the code is (**LM75**).

By the way you can use LM75 also for TMP102 sensor. You only loose higher resolution of TMP102.

**Comment by KevinOConnor** [comment]
This should have been fixed with commit 5d9d91d3.

Thanks,
-Kevin
