### ISSUE TITLE
MEASURE_AXES_NOISE Causes Communication Error

### ISSUE THREAD

**Issue by ehtnevets** [Klipper3d/klipper#4770]
Send: measure_axes_noise
Communication timeout while idle, trying to trigger response from printer. Configure long running commands or increase communication timeout if that happens regularly on specific commands or long moves.

My adxl board has been working for a couple years. Last used was last week. I didn't get timeout usually even when no connection. I just got "got ff vs e5".

Thanks for help
[klippy.log](https://github.com/Klipper3d/klipper/files/7291212/klippy.log)

**Comment by Talha909** [comment]
same here

**Comment by ehtnevets** [comment]
It seems like after a firmware restart first attempt to communicate with the board always fails. So, if I send ACCELEROMETER_QUERY repeatedly until I get no error (usually 2nd attempt), MEASURE_AXES_NOISE will execute just fine. 

SHAPER_CALIBRATE always results in communication timeout for my system.

For now, this is my workaround.
