### ISSUE TITLE
Internal error on command:"SAVE_CONFIG"

### ISSUE THREAD

**Issue by Puffymania** [Klipper3d/klipper#4791]
When ever i try to SAVE_CONFIG i get an internal error and klipper shuts down. o can not locate the problem myself. included a Log with the erro
[klippy.log](https://github.com/Klipper3d/klipper/files/7316315/klippy.log)
r.

**Comment by bonjipoo** [comment]
I have this issue if I try to save config after setting an offset in mainsail.  Also an issue when you Save Config from V0 Display.  Causes Klipper to shutdown.
