### ISSUE TITLE
"Move out of range" error leaves heaters on

### ISSUE THREAD

**Issue by blalor** [Klipper3d/klipper#4807]
I started a print job (via `virtual_sd`) that had a move (prime line) beyond the `position_max` defined in my config. Klipper stopped processing moves and emitted an error, but did not turn off the heaters.  At a minimum the heaters should have been turned off, but it feels to me like this should have been an emergency-stop scenario.

Log attached: [klippy-no-fail.log.gz](https://github.com/Klipper3d/klipper/files/7350272/klippy-no-fail.log.gz)

The console, as shown by Fluidd, displayed the following, with timestamps:

```
21:34:41 !! Move out of range: 118.355 49.235 0.775 [4077.184]
21:35:30 $ SDCARD_RESET_FILE
21:35:38 $ TURN_OFF_HEATERS
```

When I noticed the toolhead had stopped moving, I quickly jumped to Fluidd and then hit the "clear print"(?) button when I saw the error.  Unfortunately I didn't see instruction to use `M112` before doing that. Hopefully the log still contains sufficient information.

I've also observed this behavior (print abort with heaters left on) when the stepper phase is incorrect; I don't know if there's a common code path.

**Comment by blalor** [comment]
These may well originate from the same source. The lack of error reporting and action -- just a note in the log -- is at best a major inconvenience to the user, and at worst a safety issue if the idle timeout isn't honored.  This happened to me again last night and after 10 minutes my extruder and bed were still being actively heated (my idle timeout is `900`).  As a user I would expect the same emergency shutdown behavior that occurs when the bed isn't heating at the expected rate.

**Comment by blalor** [comment]
This is still an issue.

**Comment by KevinOConnor** [comment]
There is already #3666 to track this - there is no reason to keep two tickets open.

-Kevin

**Comment by blalor** [comment]
Could you please label as such and close the issue?  The bot closing stale issues doesn't communicate that.
