### ISSUE TITLE
SET_GCODE_VARIABLE does not work with non-numeric values

### ISSUE THREAD

**Issue by pedrolamas** [Klipper3d/klipper#4816]
I've noticed that `SET_GCODE_VARIABLE` fails when used with strings.

Take the following example:

```ini
[gcode_macro TEST]
variable_v: ''
gcode:
  SET_GCODE_VARIABLE MACRO=TEST VARIABLE=v VALUE='value'
```

Calling the above macro will result in the following output:

```
$ TEST
Unable to parse 'value' as a literal
Unable to parse 'value' as a literal
```

Looking at the code, the issue seems to be related to this specific bit: https://github.com/Klipper3d/klipper/blob/0b918b357cb0c282d53cbdf59e1931a2054cd60a/klippy/extras/gcode_macro.py#L178-L181

**Comment by cmidgley** [comment]
Thanks, @pedrolamas for submitting a new ticket.  As mentioned in #4107, I also found the same problem (I have a bit of additional supporting information in that post as well).

**Comment by pedrolamas** [comment]
I've checked the [existing documentation](https://www.klipper3d.org/G-Codes.html#g-code-macro-commands) for SET_GCODE_VARIABLE and noticed this bit:

> The provided VALUE is parsed as a Python literal.

This explains that the `VALUE` will be Python evaluated, so if we want it to be considered a string, it needs to be quoted as described above.

Given this, I am closing this issue.
