### ISSUE TITLE
klipper rpi 2040 release doesn't connect on raspi 4 (mainsailos)

### ISSUE THREAD

**Issue by FotoFieber** [Klipper3d/klipper#4817]
The flashed PI Pico doesn't offer a serial tty when attached to a Raspi 4 with current mainsailos. dmesg attached.
klipper.log is irrelevant
[dmesg.txt](https://github.com/Klipper3d/klipper/files/7375848/dmesg.txt)
.
Klipper v0.10.0-66-g5c10001b

**Comment by eadz** [comment]
Tried on OSX, same kind of issue - seems usb serial on rp2040 isn't working.

**Comment by dalegaard** [comment]
When I compile with my pi(gcc 8.3.1) I also get this issue, but when I use my desktop(gcc 11.2.0) the resulting uf2 works fine. I'm going to get my probe set up again, but I won't be able to look further into this until early next week.
