### ISSUE TITLE
My Random Issues With Klipper (Maybe Get Some Help) And Why I'm Switching Back To Marlin

### ISSUE THREAD

**Issue by m70b1jr** [Klipper3d/klipper#4818]
Hey guys!
I've been trying to use Klipper for the past 2 weeks or so, and man. It's rough. It really is. As a heads up, I'm using an Ender 3 Max, with a creality 4.2.7 board.

So, I originally used Klipper with Octoprint, and it worked great. Managed to build my own firmware, flash it, and get it working with octoprint, but immediately noticed the quality was way worse than what marlin was producing. Same GCode, different firmwares. I did all the obvious things, such as making sure my bed was level, and then moved onto to tuning and configuring things such as my PIDs, acceleration, velocity, pressure advance, and more. The quality was still worse compared to marlin, GCode for GCode, (i'll upload photos later of the quality issues I was running into).

That wasn't the deal breaker for me. The deal breaker was my prints randomly stoppings on Octoprint, and having to resume them manually. I then switched to Fluidd, as people said Octoprint was a bottleneck for klipper (Even tho im on a raspberry pi 3b+) and the same issue happened on Fluidd, except my prints were pausing every 10 seconds, and I had to manually resume them (with no errors!)

Kinda blows, as I wanted to increase my printing experience. I guess I'll move back to Octoprint and Marlin for now.

**Comment by Gilabite** [comment]
sure did still not the place to post this, read the link.

**Comment by Gilabite** [comment]
That link has the places to discuss klipper issues ie discord and discourse, github is for development.
