### ISSUE TITLE
[Question] Is there a way to limit accel per axis (x/y)?

### ISSUE THREAD

**Issue by pando85** [Klipper3d/klipper#4819]
Hello guys,

First of all, thank you for this awesome project.

I found that Klipper doesn't support M201 gcode and I have a CoreXY printer where maximum accelerations for x and y are quite different. Is there a way to configure it?

**Comment by dalegaard** [comment]
This is not supported in klipper, there are some older issues talking about why. You should be able to find them using the search feature.

**Comment by pando85** [comment]
Thank you
