### ISSUE TITLE
Klipper no longer working on alfawise/longer 3D printers 

### ISSUE THREAD

**Issue by Sinclair5** [Klipper3d/klipper#4855]

**Comment by Sinclair5** [comment]
I can’t flash klipper onto my alfawise u30 main board anymore, mainsail doesn’t make a connection to the printer, all this happened after the last update . Please help me ,

**Comment by simonkuehling** [comment]
@Sinclair5, unfortunately this is not the right place to get help on configuration or installation problems with klipper. But there is an active and helpful community on several different channels for you to ask for help - like a discourse forum or discord chat server.

Have a look at https://www.klipper3d.org/Contact.html#help-it-doesnt-work for details!
