### ISSUE TITLE
Turning on/off printer mainboard from RPI

### ISSUE THREAD

**Issue by pankleks** [Klipper3d/klipper#4860]
Hello,

I would like to turn on/off printer board using RPI.
I tried to do it similarly to example of "caselight" -> https://github.com/Klipper3d/klipper/blob/master/config/sample-raspberry-pi.cfg

However problem is that when I shutdown "mcu" (printer main-board) - klipper service shutdowns/disconnects - and I can't control "board on/off" pin anymore.

I was assuming that since I have two "mcu's" printer + RPI - klipper should stay connected and able to control RPI I/O.

Is this possible? Thank you.

**Comment by Dragi2k** [comment]
Use moonraker for That

https://moonraker.readthedocs.io/en/latest/configuration/#power

**Comment by pankleks** [comment]
awesome - thank you!!!
