### ISSUE TITLE
Mcu shutdown timer too close

### ISSUE THREAD

**Issue by benjjyman** [Klipper3d/klipper#4866]
Have got log at moment, will later.
Just updated to today's version of klipper, 3 layers & 1 hour into a 8 hour print received message :

MCU 'mcu' shutdown: Timer too close

logs attached, never had any issues except ones that I created, Ive probably done something again, but if someone could tell me where & what to look for that would be a great help.

Thank
[fluidd-access.log](https://github.com/Klipper3d/klipper/files/7469107/fluidd-access.log)
[klippy (7).log](https://github.com/Klipper3d/klipper/files/7469117/klippy.7.log)
[moonraker.log](https://github.com/Klipper3d/klipper/files/7469120/moonraker.log)
klipper-errror.log - empty??

**Comment by samwells2000** [comment]
having the same issue here's my log/cf
[klippy.log](https://github.com/Klipper3d/klipper/files/7469081/klippy.log)
[printer.txt](https://github.com/Klipper3d/klipper/files/7469102/printer.txt)

this happens anytime I try to home the printer which moves a stepper, everything else works fine

**Comment by Deneteus** [comment]
Related? #4679

**Comment by benjjyman** [comment]
@Deneteus  Thanks for the lead, it may well be something to do with usb & ftdi , may be even ADXL345 as Ive just rewired the accelerometer, and attached more than one webcam (which keeps changing /dev/video0 to /dev/video3 which i havent beed able to fault find ) the problem for me atleast is  very intermittent as I have only had this happen twice in over 100 hours of printing

**Comment by Eifel-Joe** [comment]
I got same problem on my Voron 2.4 with Octopus Board. After a long time and much coffee i came to the conclusion, that maybe i made a mistake with compiling the new firmware for the Octopus. For the Octopus you have to set the clock frequency. So if i made a mistake on that part, it could be related to the timer error.
So i recompiled it with the correct settings in make menuconfig and reflashed the board. And that's it. Printer is up and running again.

**Comment by plloppii** [comment]
I'm seeing this issue as well.
Attaching my klippy.log that is relevant. I am seeing the issue on one of my machines and not on the other. 
I have my serial set to 115200, and I changed out the usb cable once. Any other tips in resolving this mcu timeout issue? 
[klippy.log](https://github.com/Klipper3d/klipper/files/7491794/klippy.log)

**Comment by dinosauria123** [comment]
I have met the same issue. But it was fixed.
I found rotation_distance in stepper_x, _y, _z was set as less than 1.
I am confused with step_distance as rotation_distance. (step_distance = 1/rotation_distance)
Please check your value of rotation_distance is less than 1 or not.

**Comment by benjjyman** [comment]
I personally found having to much stress on USB ports ( multiple webcam.txt, some of which were not plugged in plus, adxl345), when I cleared these the problem resolved. Running on armbian buster on orangepi 4 .

**Comment by widewing** [comment]
I have this issue as well, I run klipper in docker in my x86 server (Lenovo T420, precisely). It randomly stop when doing print. What can be the reason for this particular failure? I checked server load, memory uses, swap uses, they all look fine. I have other applications running in this server though, but they are not causing a lot usage. Attached [klipper.log](https://github.com/Klipper3d/klipper/files/7572578/klipper.log)

**Comment by benjjyman** [comment]
Widewing most people find it's due to USB connection errors, either faulty chip or config.
You might have better luck in the discord server though, as many people have faced similar issues with recent updates.

**Comment by widewing** [comment]
@benjjyman thanks for the hint! I do use USB hub for connection. Will try direct connect.

**Comment by plloppii** [comment]
> @benjjyman thanks for the hint! I do use USB hub for connection. Will try direct connect.

I've found improved performance by wiring a direct connection from the raspberry pi to the host MCU with UART.

**Comment by benjjyman** [comment]
> > @benjjyman thanks for the hint! I do use USB hub for connection. Will try direct connect.
> 
> I've found improved performance by wiring a direct connection from the raspberry pi to the host MCU with UART.

Cool just got my octopus board today will try uart see if that eliminates problem, thanks

**Comment by Sineos** [comment]
If this is still an issue please open a new post on https://klipper.discourse.group and we will be happy to assist
