### ISSUE TITLE
Option 'default_parameter_k' is not valid in section 'gcode_macro m900'

### ISSUE THREAD

**Issue by Alssund** [Klipper3d/klipper#4867]
After updating today I got error on step_distance! 
converted to Rotation distance without problems!
But I also got: Option 'default_parameter_k' is not valid in section 'gcode_macro m900'

This works before the update:

[gcode_macro m900]
default_parameter_K: 0
gcode:
  SET_PRESSURE_ADVANCE ADVANCE={K}

**Comment by zomfg** [comment]
#4864

**Comment by zellneralex** [comment]
See https://github.com/Klipper3d/klipper/blob/master/docs/Config_Changes.md#changes
