### ISSUE TITLE
Need help in configuring further

### ISSUE THREAD

**Issue by Ablacontigomo** [Klipper3d/klipper#4868]
Hello, I've transitioned yesterday from Marlin to Klipper and I'm having some issues.

I have an Ender 3 Pro with SKR v1.4 Turbo and TMC2209 on all axis. 

Attached [here](https://pastebin.com/kimrcxc5)  is my config file, I have it running on a Raspberry.
Did PID tuning, the bed is leveled good, belts are tightened, z axis is not missing steps, calibrated the extruder.

Attached [here](https://imgur.com/a/JDoiSdH) are the photos of the XYZ cube test. I measured it with calipers and it has 20x20x20. It has an elephant foot now, when I had marlin it never did that.

Printed with 0.4 nozzle, 0.2 layer height, 10% infill, max 700 acceleration on X,Y, 100 on Z, max jerk 8, retraction 6.3mm and 20 speed. I can provide any more details needed.

Thanks in advance to everyone for sustaining this project.

**Comment by brianmpickett** [comment]
This is not the place to be posting things like this. Good job on everything else. If you wish to find solutions to your issues then please by all means go to either of these two websites. These are your go to places for the "issues" you are encountering. The "issues" that you bring up in Github are related to the errors/malfunctioning of the actual Klipper firmware itself.  Oh yeah sorry I suppose there are three locations (well probably several if you include Reddit too but anyways here you go:

https://klipper.discourse.group/
https://www.facebook.com/groups/klipper
https://discord.klipper3d.org
