### ISSUE TITLE
v0.10.0-111-gdccd5554 Compile firmware For 328p failed

### ISSUE THREAD

**Issue by eikeime** [Klipper3d/klipper#4872]
compile firmware for 328p secondary mcu board after version v0.10.0-111-gdccd5554 report following error.

> Creating symbolic link out/board
  Building out/autoconf.h
  Compiling out/src/sched.o
  Compiling out/src/command.o
  Compiling out/src/basecmd.o
  Compiling out/src/debugcmds.o
  Compiling out/src/initial_pins.o
  Compiling out/src/gpiocmds.o
  Compiling out/src/stepper.o
  Compiling out/src/endstop.o
  Compiling out/src/trsync.o
  Compiling out/src/adccmds.o
  Compiling out/src/spicmds.o
  Compiling out/src/thermocouple.o
  Compiling out/src/i2ccmds.o
  Compiling out/src/pwmcmds.o
  Compiling out/src/spi_software.o
  Compiling out/src/sensor_adxl345.o
  Compiling out/src/lcd_st7920.o
  Compiling out/src/lcd_hd44780.o
  Compiling out/src/buttons.o
  Compiling out/src/tmcuart.o
  Compiling out/src/neopixel.o
  Compiling out/src/pulse_counter.o
  Compiling out/src/avr/main.o
  Compiling out/src/avr/timer.o
  Compiling out/src/avr/gpio.o
  Compiling out/src/avr/adc.o
  Compiling out/src/avr/spi.o
  Compiling out/src/avr/i2c.o
  Compiling out/src/avr/hard_pwm.o
  Compiling out/src/avr/watchdog.o
  Compiling out/src/avr/serial.o
  Compiling out/src/generic/serial_irq.o
  Building out/compile_time_request.o
Version: v0.10.0-111-gdccd5554
  Linking out/klipper.elf
/usr/lib/gcc/avr/5.4.0/../../../avr/bin/ld: address 0x800a2e of out/klipper.elf section `.data' is not within region `data'
/usr/lib/gcc/avr/5.4.0/../../../avr/bin/ld: address 0x800b98 of out/klipper.elf section `.bss' is not within region `data'
/usr/lib/gcc/avr/5.4.0/../../../avr/bin/ld: address 0x800a2e of out/klipper.elf section `.data' is not within region `data'
/usr/lib/gcc/avr/5.4.0/../../../avr/bin/ld: address 0x800b98 of out/klipper.elf section `.bss' is not within region `data'
collect2: error: ld returned 1 exit status
make: *** [Makefile:72: out/klipper.elf] Error 1

avr-gcc verison: 5.4.0
ld version: GNU ld (GNU Binutils for Debian) 2.35.2
os: armbian bullseye
Can compile mega2560 firmware with no error.
Tried compile with pc, successful.

**Comment by numanair** [comment]
I have the same problem. A Discord user said they did the following:
mngr0 — 10/29/2021 https://discord.com/channels/431557959978450984/431559228050636820/903699329468989480
```
end of story:
I modified .config putting =n on i2c,spi and adc
make clean; make -> and it works
here it worked because I had those edits in
now I hope klippy does not cry for these missing modules
```
This was not enough in my case. Also setting hardware GPIO to =n was required as well. I have not tested beyond compiling/linking yet.
