### ISSUE TITLE
SHAPER_CALIBRATE throws errors after todays stepper control changes

### ISSUE THREAD

**Issue by miklschmidt** [Klipper3d/klipper#4875]
After todays 4 commits (Nov 4), SHAPER_CALIBRATE now fails early and klipper transitions into shutdown state. SHAPER_CALIBRATE works again when reverting back to Klipper3d/klipper@913d099261399ba737b35752f3c3be6da618bb6a.

I have 2 users who reported the issue. Both are using an ADXL345 (confirmed working, noise within 30hz) connected to an SKR Pro 1.2.

Let me know if you need more info, i will reproduce on my own printers tonight.

[klippy.log](https://github.com/Klipper3d/klipper/files/7478460/klippy_1.2.log)
![IMG_0138](https://user-images.githubusercontent.com/751171/140420956-594c6a05-fdd3-473f-9fda-8474cc6be312.png)

UPDATE: third user reported the same problem.

**Comment by LUK48** [comment]
Please find log file 
[klippy (10).log](https://github.com/Klipper3d/klipper/files/7486240/klippy.10.log)

**Comment by RuiRocha1** [comment]
I have the same problem..
[klippy (1).log](https://github.com/Klipper3d/klipper/files/7489798/klippy.1.log)
.

**Comment by miklschmidt** [comment]
Fixed with @9ecddd1ba4fe6d481f01fa2b1d9175b927907156 thank you Kevin!
