### ISSUE TITLE
Raspi temp in display

### ISSUE THREAD

**Issue by daniellom30** [Klipper3d/klipper#4888]
Anyone who can give me an idea of ​​how to modify the information on the screen [display] so that instead of showing the feed rate it shows the temperature of the raspberry?

I already modified the position and the screen shows me the new glyph but I have no idea how to create the [display_template _raspi], so that it gives me the info

` [display_data _default_16x4 speed_factor] `
` position: 1, 10 `
` text:`
`   ~raspi~`
`   { render("_raspi") }`

` [display_template _raspi]`

` [display_glyph raspi]`
` data:`
`   ................`
`   ................`
`   **...*..***.***.`
`   *.*.*.*.*...*.*.`
`   **..***.***.***.`
`   *.*.*.*...*.*...`
`   *.*.*.*.***.*...`
`  ................`
`   ***.***.*.*.***.`
`   .*..*...***.*.*.`
`   .*..***.*.*.***.`
`   .*..*...*.*.*...`
`   .*..***.*.*.*...`
`   ................`
`   ................`
`   ................ `

**Comment by PepinoGz** [comment]
You can take this as an example:
https://github.com/alchemyEngine/VoronUsers/tree/master/firmware_configurations/klipper/alch3my
