### ISSUE TITLE
anycybic kossel delta plus not work autocalibrate

### ISSUE THREAD

**Issue by pasikov123** [Klipper3d/klipper#4892]
Installed the clipper firmware and set the printer-anycubic-cassel-plus-2017.cfg configuration, enabled the parameters:

[probe]
pin code: ^PD3
z_offset: 15,9
samples: 3

[delta_calibrate]
radius: 115
# If the original probe is used
horizontal_move_z: 20

Installed the clipper firmware and set the printer-anycubic-cassel-plus-2017.cfg configuration, enabled the parameters
when selecting the menu item delta cal. auto error 
22:36:48 Probe triggered prior to movement

Calibration sensor ver 2

**Comment by pandel** [comment]
Maybe you reversed the probe connectors on the board?

Check endstops/probe with: QUERY_ENDSTOPS
See: https://www.klipper3d.org/Config_checks.html#verify-endstops
