### ISSUE TITLE
rotation_distance still dependent of microsteps?

### ISSUE THREAD

**Issue by ehtnevets** [Klipper3d/klipper#4899]
[klippy.log](https://github.com/Klipper3d/klipper/files/7501368/klippy.log)

rotation_distance seems to be calculated based on microsteps: 16. My stepper_x axis only moves half the distance at microsteps: 8.

**Comment by jakep82** [comment]
This is the expected behavior. Your x axis is running in standalone mode, so you need to set the microsteps setting to match how you've configured the driver with jumpers.

**Comment by ehtnevets** [comment]
@jakep82 , thanks.


<img width="340" alt="Screen Shot 2021-11-08 at 7 47 02 PM" src="https://user-images.githubusercontent.com/5995634/140858522-080b305d-06c1-4862-a361-b11223600a86.png">

From the schematic for Minirambo, the microsteps is software adjustable (in case of X-axis it's PG0 & PG1).

How do I make Klipper adjust the 2 bits to match the microsteps config for Minirambo like the tmc driver.

**Comment by jakep82** [comment]
This isn't the correct place for support. Please ask on Discord or Discourse.

**Comment by ehtnevets** [comment]
Ok, thanks for the suggestion. 

I thought klipper set the MS1 & MS2 bits based on microsteps value for Minirambo integrated stepper drivers like it does for TMC driver.
