### ISSUE TITLE
Printer Shutdown middle print (on same position)

### ISSUE THREAD

**Issue by KSV-Git** [Klipper3d/klipper#4914]
On my Klipper install with Mainsail OS prints fail since 3 month. Before everything worked fine. If I print without filament it finishes but with filament it always fails at the same position. I have tried several GCode files and the reset will happen during print and can be reproduced for every file at the same position of the print (for each gcode this position is different but on the same file it will fail on the same position).
Using a PiZero on UART with an SKR mini E3 dip with old stepper drivers (A4988).
In the logs I can't find any clue why there are these restarts of the mcu.

Any advice?

[klippy.log](https://github.com/Klipper3d/klipper/files/7527294/klippy.log)

**Comment by theophile** [comment]
Your log indicates you're getting the "mcu: spontaneous restart" error. For possible solutions, see here: https://github.com/Klipper3d/klipper/issues/3161
