### ISSUE TITLE
Option 'step_pin' is not valid in section 'stepper_y1'

### ISSUE THREAD

**Issue by zrox86** [Klipper3d/klipper#4915]
Hey does someone know what the this error is about"Option 'step_pin' is not valid in section 'stepper_y1'", 

have a mks robin nano v3,  on a corexz printer and two y step motors, with normal setup (also one y stepper) works great, if i put a second one it comes the error above, i have checked the pins on the board on github 

[https://github.com/makerbase-mks/MKS-Robin-Nano-V3.X/wiki/Wiring_Pinout_and_Size](url)

all 4 rev. have the same pin setup for this setup

[klippy.log](https://github.com/Klipper3d/klipper/files/7528825/klippy.log)

**Comment by theophile** [comment]
Not sure if this is the reason for the error, but your [stepper_y1] config section is missing several required parameters. See here: https://github.com/Klipper3d/klipper/blob/master/docs/Config_Reference.md#stepper

**Comment by zrox86** [comment]
Hi theophile, thx for the comment, but I have copied the parameters for the second stepper motor from the config file of voron 2.4 (as an orientation point, tweaked to my needs).

the step pin pd6 is somehow the problem, I am not sure is it bcs of the new update of klipper and the resulting mcu flashing, maybe the the pin map is not correct, I posted the problem to see if i have a problem in my logic of configuring the config file to see if sombody does have the same issue :D

**Comment by zrox86** [comment]
I tried a different approach, used the configuration of pins for [stepper_y1] and reconfigured it as second extruder [extruder1], it seems klipper dont allow a second stepper for y axis also [stepper_y1] but a second extruder[extruder1], its logical but thought it would allow it. 

I found a solution for second stepper on y axis, configured the x (in klipper) as x (on board), z (in klipper) as y (on board) and  y (in klipper) as z (on board), bcs. on the board two z axis share the same driver.

It works :D, I will close the issue bcs found a workaround :D

**Comment by Ed-k** [comment]
I had the same problem, but I want to use stepper_x1 and stepper_y1.  This patch allows multiple motors for any axis in corexy - https://github.com/Klipper3d/klipper/pull/4974

**Comment by zrox86** [comment]
Thx for the ideas guys. My Idea with two motors on one driver (the workaround) have not worked properly.

 I used the code from here 
[https://github.com/Klipper3d/klipper/commit/bbd1ddadd189645fb5bcd263d991cdc7e99cf011](url)
and ported it to corexz.py like this

`self.rails = [ stepper.PrinterRail(config.getsection('stepper_x')),
                       stepper.LookupMultiRail(config.getsection('stepper_y')),
                       stepper.PrinterRail(config.getsection('stepper_z')) ]
        self.rails[0].get_endstops()[0][0].add_stepper(
            self.rails[2].get_steppers()[0])
        self.rails[2].get_endstops()[0][0].add_stepper(
            self.rails[0].get_steppers()[0])

<img width="941" alt="image" src="https://user-images.githubusercontent.com/83814243/160258299-05effa60-9d35-44e0-b831-c07ee50fc219.png">

[klippy.log](https://github.com/Klipper3d/klipper/files/8356442/klippy.log)

The issue still remains, would like to hear some sugestions bcs I am a nuby in programming.

**Comment by Sineos** [comment]
Please do not dig up old and closed topics. Support requests shall be handled via: https://klipper.discourse.group/
Please be so kind to place your issue there.
