### ISSUE TITLE
Print head drifts left on x-axis during PROBE_CALIBRATE

### ISSUE THREAD

**Issue by qcgilbert** [Klipper3d/klipper#4918]
When running probe calibrate the x-axis begins to slowly drift left.
[klippy.log](https://github.com/Klipper3d/klipper/files/7531212/klippy.log)

**Comment by bluepinner** [comment]
This is normal. Taken from the klipper documentation.... "This tool will perform an automatic probe, then lift the head, **### _move the nozzle over the location of the probe point_**, and start the manual probe tool."
