### ISSUE TITLE
Bed mesh size to printing part size label:enhancement 

### ISSUE THREAD

**Issue by mlkood** [Klipper3d/klipper#4919]
Can make bed mesh size of printing area . when printing area is small then bed mesh area is small not  all bed size.

Signed-off-by: Mario mariomobla@gmail.com

**Comment by Arksine** [comment]
This is already possible.  The mesh parameters can be passe to the `BED_MESH_CALIBRATE` G-Code.  The [documentation](https://www.klipper3d.org/Bed_Mesh.html#calibration) provides more details.

**Comment by ChipCE** [comment]
Check my script https://gist.github.com/ChipCE/95fdbd3c2f3a064397f9610f915f7d02

**Comment by Sineos** [comment]
If this is still an issue please open a new post on https://klipper.discourse.group and we will be happy to assist
