### ISSUE TITLE
Lost communication with MCU right after Homing (override)

### ISSUE THREAD

**Issue by Lazurx** [Klipper3d/klipper#4924]
Hello. 
Recently i got back to work on my 3d printer. Unfortunately i forgot the password to my Raspberry so I tried the method:
https://raspberrypi.stackexchange.com/questions/98353/forgot-password-for-username-pi
After this i conducted several dry runs on gocode already loaded to octopi since year or so (to test the new XY gantry). Because of lack of MIN or MAX switches i override homing with given coordinates.
In the meantime I inverted one dir pin in config file to match gantry moves with commands. Then i made a new gcode in CURA and tried do execute it in OctoPrint and then error came up and terminal prompting "Lost communication with MCU":

> Lost communication with MCU 'mcu'
> Once the underlying issue is corrected, use the
> "FIRMWARE_RESTART" command to reset the firmware, reload the
> config, and restart the host software.
> Printer is shutdown

I restarted whole system and tried to dry run on "old gcode" (which worked previously). The error come up right after executing HOMING.
Could you help resolving this problem?

[klippy.log](https://github.com/Klipper3d/klipper/files/7533765/klippy.log)
.

**Comment by Sineos** [comment]
Issue seems concluded. If you need support, we will be happy to assist on https://klipper.discourse.group
