### ISSUE TITLE
HELP command crashed if unicode characters in Marco description 

### ISSUE THREAD

**Issue by ronald5555** [Klipper3d/klipper#4926]
If you add in a macro a “description” containing unicode characters (like é or à as we use it in french) the HELP command crashes.
Replacing these characters with non accented characters and HELP works.

Example where HELP crashes:
[gcode_macro _no]
description: indique une action erronée.  <---- here we have a **é**

Example where HELP works
[gcode_macro _no]
description: indique une action erronee. <----- here the **é** has been replaced with a standard **e**

[klippy-3.log](https://github.com/Klipper3d/klipper/files/7536815/klippy-3.log)
![32e61474eb658ad10450668aa5f0dbf5117fd691](https://user-images.githubusercontent.com/68804341/141742889-488cda5c-0947-4218-88be-9d66c2b3fb09.png)

**Comment by Sineos** [comment]
Duplicate / same reason as #4794
