### ISSUE TITLE
KlipperScreen fails to connect until Klipper Restart

### ISSUE THREAD

**Issue by NikosSprocket** [Klipper3d/klipper#4929]
<!-- Directions have recently changed. Do not open this ticket without
 following the directions at: https://www.klipper3d.org/Contact.html --
[KlipperScreen.log](https://github.com/Klipper3d/klipper/files/7543671/KlipperScreen.log)
[klippy.log](https://github.com/Klipper3d/klipper/files/7543672/klippy.log)
From initial power-up of a Voron 2.4 running klipper v0.10.0-124-g5dcc377c and KlipperScreen v0.1.6-129-gf6fcb32 the KlipperScreen fails to connect to Klipper. Moonraker is operating as usual and everything looks good. After a "Klipper Restart" from Moonraker or KlipperScreen KlipperScreen is functional again. From the KlipperScreen.log looks like there is an issue with a Python call/variable?>

**Comment by NikosSprocket** [comment]
From initial power-up of a Voron 2.4 running klipper v0.10.0-124-g5dcc377c and KlipperScreen v0.1.6-129-gf6fcb32 the KlipperScreen fails to connect to Klipper. Moonraker is operating as usual and everything looks good. After a "Klipper Restart" from Moonraker or KlipperScreen KlipperScreen is functional again. From the KlipperScreen.log looks like there is an issue with a Python call/variable?

**Comment by jakep82** [comment]
Please report this to KlipperScreen. This is not a Klipper issue.

**Comment by zellneralex** [comment]
https://github.com/jordanruthe/KlipperScreen/issues/328

**Comment by NikosSprocket** [comment]
Sorry! I will put the info. in KlipperScreen.
