### ISSUE TITLE
Error when installing?

### ISSUE THREAD

**Issue by JoeK1973** [Klipper3d/klipper#4946]
Hi, I was wondering how i fix this error?

![image](https://user-images.githubusercontent.com/17706579/142727494-d64f07fd-16ca-45ad-9c90-8913d13921eb.png)

**Comment by Sineos** [comment]
See https://klipper.discourse.group/t/compiler-not-founf-for-skr-2-board/1166/2?u=sineos

**Comment by JoeK1973** [comment]
> See https://klipper.discourse.group/t/compiler-not-founf-for-skr-2-board/1166/2?u=sineos

That seems to have done the job! Thanks!
