### ISSUE TITLE
Issue with the Documentation Search Function on https://www.klipper3d.org/

### ISSUE THREAD

**Issue by Sineos** [Klipper3d/klipper#4963]
Browser:
* Firefox 94.0.1
* Chrome  95.0.4638.69

https://www.klipper3d.org/Rotation_Distance.html

![grafik](https://user-images.githubusercontent.com/4459312/143442320-c06f4747-908b-4192-8517-747d75556112.png)

When going to the same Chapter via the search function and highlighting:

https://www.klipper3d.org/Rotation_Distance.html?h=rotat

![grafik](https://user-images.githubusercontent.com/4459312/143444026-55e4b208-fcab-438d-a96c-277820c2681c.png)

**Comment by KevinOConnor** [comment]
I'd guess this is a defect in mkdocs.  I'm not sure how we'd be able to fix this in the Klipper build itself.

-Kevin

**Comment by Sineos** [comment]
https://github.com/squidfunk/mkdocs-material/issues/2068

Seems there is a fix available. Maybe @dingyifei could cross check

**Comment by KevinOConnor** [comment]
Okay.  It's possible to update the mkdocs-material version (it is specified in docs/_klipper3d/mkdocs-requirements.txt ).  However, it is unclear to me if this issue was addressed in the latest publicly released version.

-Kevin

**Comment by KevinOConnor** [comment]
It does seem that an upgrade to mkdocs-material v8.1.3 fixes this issue (commit 608cd38d).

Thanks.
-Kevin

**Comment by Sineos** [comment]
Fix confirmed 👍
