### ISSUE TITLE
Cannot set input_shaper shaper_type

### ISSUE THREAD

**Issue by Burtfaceman** [Klipper3d/klipper#4987]
When attempting to set an input shaper type in my config file, I get the following error:
![image](https://user-images.githubusercontent.com/81212159/144366545-ebcd65ea-d118-43ff-99ff-ffe5dba15ca9.png)

Here's the input_shaper section of my config file:
> [input_shaper]
> shaper_freq_x = 45.2
> shaper_freq_y = 45.5
> shaper_type = MZV

Config file attached
[printer.cfg.txt](https://github.com/Klipper3d/klipper/files/7639405/printer.cfg.txt)

**Comment by Gilabite** [comment]
Try it in lowercase mzv

**Comment by AndyWo83** [comment]
this is the newer input_shaper section:
![image](https://user-images.githubusercontent.com/45575213/144473047-f71a8370-0047-480d-aca9-605722770d1c.png)

And lowercase mzv is the better one...

**Comment by Burtfaceman** [comment]
Thanks, that worked. Documentation tends to use uppercase for shaper types. This behavior is unexpected.
