### ISSUE TITLE
Shutdown during a print

### ISSUE THREAD

**Issue by azais-corentin** [Klipper3d/klipper#4991]
I was printing overnight and this morning the print was stopped. The LCD screen was stuck showing normal temperatures (215°C and 60°C) but the hotend and bed were cold, and the motors were disabled. I removed power from the printer, but not the Pi and then issued a M112. 
I am attempting to print the same file again today and will update this issue if it fails again.

Update: The second try was successful.

[klippy.zip](https://github.com/Klipper3d/klipper/files/7654100/klippy.zip)

**Comment by Sineos** [comment]
Issue seems concluded. Please open a new one if new problems arise. Preferable use https://klipper.discourse.group for general support topics.
