### ISSUE TITLE
MCU Shutdown Timer Too Close, Robin Nano + RPI Zero.

### ISSUE THREAD

**Issue by blendfish** [Klipper3d/klipper#5002]
Updated to latest klipper firmware using Kiauh as normal, no longer able to print for any length of time before the above error happens.

This is on a Robin nano with RPI Zero.

If I slow down the print from the standard settings to 1000 acceleration then it seems to work ok.  I'm happy to upgrade the Pi but I'm not sure that's the real issue as it's been working on for at least a year.

None of the recommendations given seem to be the case, I monitored the CPU and it was around 50%, voltage comes directly from the robin nano motherboard via the 5v line.  Data comes from a direct wire to the RX/TX line and there's no issue with the RPI SD Card.

[klippy.log](https://github.com/Klipper3d/klipper/files/7668587/klippy.log)
[moonraker.log](https://github.com/Klipper3d/klipper/files/7668589/moonraker.log)

**Comment by blendfish** [comment]
Should have mentioned I'm using Fluidd as the frontend not octoprint.

**Comment by blendfish** [comment]
I did another test using an external 5v official pi supply (data still connected via UART pins.)  

![image](https://user-images.githubusercontent.com/95695204/145082172-71d5b144-4d2d-40a6-8533-55e37ed1e237.png)

Klipper went over 200% (not sure how load can be over 100%?)  
It happened a few times, mostly caused a few pauses in the print but it eventually gave up.

I've ordered the new Pi Zero 2 which is apparently much more powerful, though I doubt I'm getting 200%+ speed on any current pi.

**Comment by blendfish** [comment]
I discovered that going around the edges of these gears was the culprit.

![image](https://user-images.githubusercontent.com/95695204/145089391-8fac1d9c-49eb-4ae1-a59d-f9f547d8dcfe.png)

**Comment by Sineos** [comment]
Issue seems concluded. Please open a new one, if the problem persists with the new RPi
