### ISSUE TITLE
[Request] DWIN T5UID1 touchscreen support

### ISSUE THREAD

**Issue by LMS0815** [Klipper3d/klipper#5004]
Kindly consider implementing T5UID1 touchscreen support into Klipper master branch.
Where [dgus-display](https://github.com/Desuuuu/klipper/tree/dgus-display) is the most interesting branch/approaxh.

[Desuuuu/klipper](https://github.com/Desuuuu/klipper)
[Desuuuu/dgus-display](https://github.com/Desuuuu/klipper/tree/dgus-display)

This would add Touch Screen Support for:
Creality Ender 5+
Creality Ender 6
Creality Ender CR-10s
Creality Ender CR-X

**Comment by Volanaro** [comment]
2nd this,

**Comment by Witawat** [comment]
+1

**Comment by meesterwu** [comment]
4th this, thanks for all the great work!!!

**Comment by ld3300** [comment]
Are there any interested developers that could submit this as a pull request?  I believe that the primary repo maintainers are pretty heavily involved in some other development tracks.

**Comment by LaggAt** [comment]
I looked at the changes, which seems to be somewhat more than just the display code.

Just started an issue in the Desuuu repo, maybe we could get some help here:
https://github.com/Desuuuu/klipper/issues/113

**Comment by Sineos** [comment]
Here @KevinOConnor would need to chime in: 
As far as I understand the current situation, all display topics are more or less on hold due to the need for having a solid code foundation first, i.e. to avoid patching display variant upon display variant with all the associated code duplication and maintenance burden.

**Comment by Sineos** [comment]
That having said, it is preferable to continue such discussions on https://klipper.discourse.group

**Comment by hakuyouhiro** [comment]
Are we covering this at https://klipper.discourse.group/c/features/9 ? i can't see the topic created

**Comment by Sineos** [comment]
See https://klipper.discourse.group/t/dwin-t5uid1-touchscreen-support/2411

**Comment by PeggyFree** [comment]
I support this request since the printers SOVOL SV02 and SOVOL SV04 also use this DWIN T5UID1 touchscreen

**Comment by napter** [comment]
Is there any chance of this hpapeneing? It doesn't look like the discussion on the thread went anywhere. It would be great if there was support for the stock screen on the Ender 5 plus.

**Comment by Rokin05** [comment]
+1
The Longer LK4 Pro printer also use this screen (and Desuuuu fw work fine on it)
(and surely Alfawise u30 pro who is the ~same printer)

**Comment by blondsign** [comment]
That would be great

**Comment by teichertw** [comment]
still waiting ...

**Comment by stooged** [comment]
+1 for official support.

i have merged the current klipper repo to the dgus_reloaded fork for my own printers but i would love to see official support for the DWIN T5UID1 screens.

**Comment by fryc88** [comment]
I would love to see official support as well. I'm using fork of Desuuu git to keep it up to date with main klipper branch but official support is always easier to handle.
Also screen is getting more popular, few types of same screen series is being used in more and more new printers so there will be more interested people I guess.

**Comment by mirlang** [comment]
+1

**Comment by MacFly669** [comment]
+1

**Comment by stooged** [comment]
I ended up just following this video and installed klipperscreen.
The dgus was cool but doing this mod was worth it.

https://m.youtube.com/watch?v=wt8o4NNgknY

**Comment by fryc88** [comment]
Yeah, but he changed the screen, that's additional cost. Some people want to cut costs and didn't want to invest more.

**Comment by stooged** [comment]
> Yeah, but he changed the screen, that's additional cost. Some people want to cut costs and didn't want to invest more.

Yeah i know, it cost me about $50 for the screen.
The way i looked at it was i could keep merging the klipper updates to the dgus repo which takes time and put up with the limited functionality of the dgus screen or i could spend the 50 and unlock the full klipperscreen ui and have official update support.

I was all for official dgus support but it looks like that is not going to be a thing :(

**Comment by fryc88** [comment]
It's fairly easy to keep his branch updated, it can be merged with main branch pretty easy, even with automated merges weekly for exmaple ;) His files aren't involving anything major from Klipper, so it's doable.

**Comment by MacFly669** [comment]
+1

**Comment by PorcoMaster** [comment]
> It's fairly easy to keep his branch updated, it can be merged with main branch pretty easy, even with automated merges weekly for exmaple ;) His files aren't involving anything major from Klipper, so it's doable.

Hi, i don't know if i can ask this here, but you were able to update your klipper while using desuu firmware, i would love to test axis twist compensation, but desuu firmware is outdated from main branch, how did you update your firmware, is there any youtube or writen tutorial (preferred) 

thanks in advance, and if this is not the place, i will delete it.

**Comment by fryc88** [comment]
I've gathered all details into one guide while I was playing with my Sovol SV06plus with this screen, a friend of mine made auto update for this branch, it still works as far as i'm aware.
https://github.com/fryc88/klipper-sv06plus-screen

**Comment by fryc88** [comment]
I mainly mean branch. That gbkwiat is basically desuuus klipper branch but with auto merge weekly with main klipper branch so it's up to date. And if your screen is vertical in cr10 then it should be ok with these screen files too

**Comment by PorcoMaster** [comment]
> I mainly mean branch. That gbkwiat is basically desuuus klipper branch but with auto merge weekly with main klipper branch so it's up to date. And if your screen is vertical in cr10 then it should be ok with these screen files too

Unfortunately it's horizontal screen, if it were vertical, I would for sure try it out, I at least learned about verbose -v and -g, did not make any difference just take out a warning in orange, so I reverted back. 

But I really appreciate your help, I just hope someday they will support T5UID1 on official repo.

**Comment by fryc88** [comment]
It will never be added to official repo.
With orange not going away probably you missed some step or you need to give it more restart/refresh of updates to get rid of it, it won't go off on its own after adding parameters. 
With horizontal screen you can edit it or make your own firmware for it, however I'm pretty sure I've seen it somewhere too
