### ISSUE TITLE
Saved BED_MESH_PROFILE not visible in Heightmap 

### ISSUE THREAD

**Issue by MalsakerLures** [Klipper3d/klipper#5005]
I just updated to Klipper version: v0.10.0-172-g051133f8
Any bed_mesh_profiles saved using the command BED_MESH_PROFILE SAVE=<name> is stored on the config but are not visible or loadable under Heightmap.

When reviewing the config i can see the actual config has been written, but not visible under height map.

Attached are screenshots as well as klippy log
[klippy (6).log](https://github.com/Klipper3d/klipper/files/7671986/klippy.6.log)

<img width="841" alt="Skärmavbild 2021-12-07 kl  22 52 07" src="https://user-images.githubusercontent.com/44981544/145115288-044276ff-7ade-4c04-bc22-3b010e7c2342.png">

![Skärmavbild 2021-12-07 kl  22 45 24](https://user-images.githubusercontent.com/44981544/145115402-d73e01dd-6c52-4761-8d9b-0759915df64e.png)

**Comment by Sineos** [comment]
Your log contains:

```
Can't read autosave from config file - autosave state corrupted
```

and all the printer config information that is reflected in the log file do not contain any mesh information. I cannot really think of a reason, why this should happen, except manually tinkering with the `#*#` section or a corrupt SD card.
I would delete the entire `#*#` and repeat the process.

@KevinOConnor I wonder why Klipper does not shutdown on such an event

**Comment by MalsakerLures** [comment]
Deleted the everything below  the save config parameters. Restarted. Ran a new bed mesh and tried to save the config.

Config saved and verified as i saw the entries in the .cfg, but still not able to see the saved profiles under heightmap.

**Comment by MalsakerLures** [comment]
Ha, found the issue!

if the are sections other then the save_config the it dosent work. If i remove them, then it all works as expected.

 i had the following divider in my config previosly: #*#<——- Macro ——->

**Comment by Sineos** [comment]
Issue seems concluded. If you need support, we will be happy to assist on https://klipper.discourse.group
