### ISSUE TITLE
Heater extruder not heating at expected rate

### ISSUE THREAD

**Issue by way2fast** [Klipper3d/klipper#5006]
so since switching to klipper i have been having extruder heater failures.  its been happening at random times, sometimes when heating, sometimes 2hrs into a print.  im running an skr e3 mini v1.2, and my ender is converted to corexz based on switchwire parts.  since ive been having this issue i have run 3 different thermistors, and 2 heater cores.  i ran this setup on marlin before the conversion and never had a heater failure.  not entirely sure how to read the klipper log, but it looks like at one point just before a print was about to fail it seems like extruder pwm was dropping as the temp dropped from 215 down to almost 200 and then the print failed as a result.  is it possible the call for pwm on the heater is "lazy" for a lack of a better word?

oh and the heater block is insulated, and i have done the pid tune with the part cooling fans at full and at off, same random result.

any help would be much appreciated

![thumbnail_IMG_0485](https://user-images.githubusercontent.com/42668478/145117224-f4222bb4-bccd-447e-9362-09901a7c7fa9.jpg)

[klippy-2.log](https://github.com/Klipper3d/klipper/files/7672061/klippy-2.log)

.

**Comment by Sineos** [comment]
If this is still an issue please open a new post on https://klipper.discourse.group and we will be happy to assist
