### ISSUE TITLE
/tmp/printer Error

### ISSUE THREAD

**Issue by brnttws** [Klipper3d/klipper#5015]
I have followed all directions multiple times and i am still unable to get octoprint to Show Port /tmp/printer even after i add it to the "Additional serial Ports" box. 
[octoprint-logs.zip](https://github.com/Klipper3d/klipper/files/7696708/octoprint-logs.zip)

**Comment by Sineos** [comment]
If this is still an issue please open a new post on https://klipper.discourse.group and we will be happy to assist
