### ISSUE TITLE
Pin 'analog14' is not a valid pin name on mcu 'mcu'

### ISSUE THREAD

**Issue by macaroniart123** [Klipper3d/klipper#5019]
Im working with an ender 3 V2 with an MKS gen L v1 with TMC2208s modified as seen on 
https://www.youtube.com/watch?v=7VHwcEroHPk&t=669s
in the dynamic UART section

There are some changes to the klipper config file since 2/2019 so I am trying to make adjustments as I am going along, responding to the klipper errors 

One I cannot get past is: Pin 'analog14' is not a valid pin name on mcu 'mcu'

I am not sure how to adjust for this as it seems that it should be a valid pin name. 

Can someone help? Klipper log and config file below

Klipper log: https://pastebin.com/v3XdYu8K
Config file:  https://pastebin.com/6s8t93Fs

**Comment by Sineos** [comment]
Add the `[board_pins arduino-mega]` from here https://github.com/Klipper3d/klipper/blob/master/config/sample-aliases.cfg to your config

**Comment by Sineos** [comment]
Issue seems concluded. If you need support, we will be happy to assist on https://klipper.discourse.group
