### ISSUE TITLE
One or more steppers are unknown:

### ISSUE THREAD

**Issue by grrminator** [Klipper3d/klipper#5021]
https://pastebin.com/2MPyd7Uu

There is my CFG.

I am not sure if its an issue with syntax, any help is appreciated!

**Comment by Sineos** [comment]
Generally, please post your klippy.log

```
[controller_fan stepstick_fan] ###CONTROLLER FAN
pin: PH4
stepper: extruder, stepper_x, stepper_y, stepper_z, stepper_z1 heater_bed
idle_timeout: 120
```

Missing comma between stepper_z1 and heater_bed?

**Comment by Sineos** [comment]
Issue seems concluded. If you need support, we will be happy to assist on https://klipper.discourse.group
