### ISSUE TITLE
SKR Mini E3 v3 Support?

### ISSUE THREAD

**Issue by drak42** [Klipper3d/klipper#5026]
Hey,

Any idea when this will be supported in the master tree?

Thanks

**Comment by Sineos** [comment]
Should be supported with https://github.com/Klipper3d/klipper/pull/5049
Pin mapping can be found at https://github.com/bigtreetech/BIGTREETECH-SKR-mini-E3/tree/master/hardware/BTT%20SKR%20MINI%20E3%20V3.0/Hardware

**Comment by Sineos** [comment]
Seems the topic is concluded. Please do not hesitate to open a new issue on https://klipper.discourse.group if needed
