### ISSUE TITLE
Simultaneously Homing 3 Z Axes

### ISSUE THREAD

**Issue by TheRunnerPi** [Klipper3d/klipper#5027]
Hello together,

I want my printer to have 3 individual Z-axes. The print bed is then aligned with the Z-Tilt comand and a BlTouch. If the bed is very tilted, the nozzle may hit the print bed first.

Can I somehow make a normal Z-Homing before the Z-Tilt, so that all 3 Z-axes move upwards at the same time against an end stop? All 3 axes would have to start simultaneously and then stop individually via Sensorless Homing (TMC2209).

The print head would move to a corner beforehand and would then not be in the way. Then the bed would be halfway straight. Afterwards, the bed would move down a little and start the Z-Tilt from there.

Has anyone ever done this before? I could not find anything.
Thanks and greetings 
Daniel

Translated with www.DeepL.com/Translator (free version)

**Comment by EzDzO** [comment]
Hi,

I also had this problem, and I solved it this way.

First you can create a [homing_override] where you can specify your own homing procedure.

If you define both the virtual end stop and the end stop position in the [stepper_z] [stepper_z1] and [stepper_z2], when you give the command G28 Z the printer will home without using the probe. 

The problem with the bed is that
If I home the bed without first moving the extruder away I might crash into it
If I move the extruder before I know the position of the bed I might crash into the bed 

I decided to first home the z axis to the max point, so going away from the extruder, then when I run the z-tilt command it uses the probe automatically to compensate any error of the 3 steppers
