### ISSUE TITLE
 Unknown pin chip name 'probe'

### ISSUE THREAD

**Issue by macaroniart123** [Klipper3d/klipper#5033]
Hello, 

Im getting stuck at this point:
08:53:28 Klipper: Standby
08:53:32 Klipper: Connecting ...
08:53:32 Unknown pin chip name 'probe'

I am using teaching tech videos as a guide: https://www.youtube.com/watch?v=3DWqJeXK7yc

I read this part of klipper but do not think it has by answer?
https://www.klipper3d.org/BLTouch.html

Im following the 
Klipper log: https://pastebin.com/QB0ZTErV
Klipper config https://pastebin.com/C5j2sX35

Thank you!!

**Comment by hmortensen83** [comment]
Your config sections safe_z_home, bltouch and bed_mesh are indented. Remove tabs and whitespaces infront of every line in the config.

**Comment by Sineos** [comment]
Issue seems concluded. If you need support, we will be happy to assist on https://klipper.discourse.group
