### ISSUE TITLE
Lost communication with MCU Timeout issue

### ISSUE THREAD

**Issue by Cheap-Tricks** [Klipper3d/klipper#5036]
I have an x86 PC running 5x instances of Klipper - though this issue has happened with a Pi 3 and Pi 4 running between 2 to 4 instances of klipper each.

MCU Timeout will occur randomly, sometimes soon after or near the end of a print. No pattern can be observed. Some printers randomly do it very often, some printers nearly never at all. 

Attached is a sample log and some graphs.

I currently have 5x printers. 2 of the 5 will timeout often, the rest not so much.

![loadgraph](https://user-images.githubusercontent.com/62266308/146622441-a0c2ee58-8ef1-4399-90c0-9b38d0632e75.png)
![loadgraphm](https://user-images.githubusercontent.com/62266308/146622442-ad983302-1adb-4609-8284-08e50ef4ad05.png)

**Comment by Lyksel** [comment]
Why did you close it? Do you have a solution?
