### ISSUE TITLE
MCU shutdown and error

### ISSUE THREAD

**Issue by MatrixTechno** [Klipper3d/klipper#5044]
Whenever I try to connect the pi to my printer, I get one of these two errors. I will restart the firmware around 20 times before it actually works, this happens every time and I'm not sure why. 
![unknown](https://user-images.githubusercontent.com/96351993/146652619-b14025f0-b6df-41f2-a0ba-3ce209a39bec.png)
![unknown](https://user-images.githubusercontent.com/96351993/146652621-dec654be-fa98-4856-aabd-1a603a124648.png)

**Comment by Sineos** [comment]
What is your host computer? Anything else running on it, like webcams etc?

**Comment by MatrixTechno** [comment]
I'm using the original Pi model B Rev 2, I've since turned off my webcam and it seems to give me the error less, but I still get it. Is the original pi just not powerful enough? 
![image](https://user-images.githubusercontent.com/96351993/146685613-ed81f20b-9b56-4a50-8ea8-bedbe90d8375.png)

**Comment by Sineos** [comment]
I cannot comment on Pi model B Rev 2 as I never used it with Klipper. I have one as part of my home automation and I know it is slower than my analog watch.
It is even slower than a Pi Zero and they are known to be easily overwhelmed by Klipper.

**Comment by Sineos** [comment]
Seems the topic is concluded. Please do not hesitate to open a new issue on https://klipper.discourse.group if needed
