### ISSUE TITLE
Unable to upload printer.cfg

### ISSUE THREAD

**Issue by jacobcd** [Klipper3d/klipper#5047]
New install on ender 6. I cannot upload the printer.cfg or make any changes to any cfg files

error: Unable to open config file /home/pi/klipper_config/printer.cfg

[klippy (1).log](https://github.com/Klipper3d/klipper/files/7740556/klippy.1.log)
[moonraker.log](https://github.com/Klipper3d/klipper/files/7740557/moonraker.log)
.

**Comment by Sineos** [comment]
Most likely you you forgot some steps during installing moonraker, mainsail or fluidd. Please check the appropriate install instructions of the web-ui you are using.

Klipper expects its `printer.cfg` file to be in `/home/pi/klipper_config/` and apparently it is missing
