### ISSUE TITLE
Print stops - Cannot update MCU config as shown

### ISSUE THREAD

**Issue by Cheap-Tricks** [Klipper3d/klipper#5055]
During a long print, the printer seems to have stopped randomly - The log shows normal until "Klippy started" and then gives error "Cannot update MCU config as shown"
[logchunk.txt](https://github.com/Klipper3d/klipper/files/7756149/logchunk.txt)

**Comment by simonkuehling** [comment]
Looks like for some reason the Klippy service has been restarted mid print. But I guess you need to tell a bit more about the setup you are running. Also, initiating an emergency stop in that situation via `M112` will write a bunch of useful information into the log for debugging (like the last few gcodes processed etc)

Does a `FIRMWARE_RESTART` reset Klipper into operation in that state?
