### ISSUE TITLE
Temperature reading

### ISSUE THREAD

**Issue by tony21675** [Klipper3d/klipper#5081]
I recently upgraded my hot end to a E3D-V6. Once I put it on and updated klipper and mainsail to the newest version both my hot end and bed quit sending accurate temperatures. Both are reading around 200c with no heat being applied. I have tried 3 different thermistors thinking one could be bad with no luck.

[klippy-2.log](https://github.com/Klipper3d/klipper/files/7790752/klippy-2.log)
![Screenshot from 2021-12-29 16-23-25](https://user-images.githubusercontent.com/79947707/147710282-9b98bddf-d8c3-4243-99a9-a2910b72e23b.png)

**Comment by Sineos** [comment]
Most likely a wiring issue. Loose connector, broken cable, short circuit

**Comment by tony21675** [comment]
Later today when I get a chance I will take it all apart and put it together peace by peace and see where it might be wrong.

**Comment by tony21675** [comment]
Ok I disconnected both my hot end and bed (thermistor and power leads) still reading 180c plus. So I think my board is blown or something is wrong in my cfg file.

# This file contains common pin mappings for the BIGTREETECH SKR V1.4
# board. To use this config, the firmware should be compiled for the
# LPC1768 or LPC1769(Turbo).

# See docs/Config_Reference.md for a description of parameters.

[include mainsail.cfg]

[stepper_x]
step_pin: P2.2
dir_pin: P2.6
enable_pin: !P2.1
microsteps: 32
rotation_distance: 31
full_steps_per_rotation: 200
endstop_pin: tmc2209_stepper_x:virtual_endstop
homing_retract_dist: 0
position_endstop: -12
position_min: -12
position_max: 200
homing_speed: 40

[tmc2209 stepper_x]
uart_pin: P1.10
diag_pin: P1.29
driver_SGTHRS: 95
run_current: 0.400
stealthchop_threshold: 999999

[stepper_y]
step_pin: P0.19
dir_pin: P0.20
enable_pin: !P2.8
microsteps: 32
rotation_distance: 31
full_steps_per_rotation: 200
endstop_pin: tmc2209_stepper_y:virtual_endstop
homing_retract_dist: 0
position_endstop: -41
position_min: -41
position_max: 200
homing_speed: 40

[tmc2209 stepper_y]
uart_pin: P1.9
diag_pin: P1.28
driver_SGTHRS: 135
run_current: 0.400
stealthchop_threshold: 999999

[stepper_z]
step_pin: P0.22
dir_pin: P2.11
enable_pin: !P0.21
microsteps: 16
rotation_distance: 8
full_steps_per_rotation: 200
endstop_pin: probe:z_virtual_endstop
position_min = -3
position_max: 300
homing_speed: 50

[tmc2209 stepper_z]
uart_pin: P1.8
diag_pin: P1.27
run_current: 0.650
hold_current: 0.450
stealthchop_threshold: 999999

[stepper_z1]
step_pin: P1.15
dir_pin: P1.14
enable_pin: !P1.16
microsteps: 16
rotation_distance: 8
full_steps_per_rotation: 200

[tmc2209 stepper_z1]
uart_pin: P1.1
run_current: 0.650
hold_current: 0.450
stealthchop_threshold: 999999

[extruder]
step_pin: P2.13
dir_pin: P0.11
enable_pin: !P2.12
microsteps: 16
rotation_distance: 33.52968
full_steps_per_rotation: 200
nozzle_diameter: 0.400
filament_diameter: 1.750
pressure_advance = .1978
heater_pin: P2.7
sensor_type: EPCOS 100K B57560G104F
sensor_pin: P0.24
control: pid
pid_Kp: 21.684
pid_Ki: 0.723
pid_Kd: 162.629
min_temp: 0
max_temp: 1000

[tmc2209 extruder]
uart_pin: P1.4
run_current: 0.800
hold_current: 0.500
stealthchop_threshold: 1

[heater_bed]
heater_pin: P2.5
sensor_type: EPCOS 100K B57560G104F
sensor_pin: P0.25
control: pid
pid_Kp: 74.525
pid_Ki: 1.227
pid_Kd: 1131.852
min_temp: 0
max_temp: 250

[fan]
pin: P2.3

[mcu]
serial: /dev/serial/by-id/usb-Klipper_lpc1768_03040E0E5B165253BC58C54C050000F5-if00

[printer]
kinematics: corexy
max_velocity: 400
max_accel: 500
max_z_velocity: 10
max_z_accel: 100

[bltouch]
sensor_pin = !P1.27 #Z-Endstop
control_pin = P2.0 #SERVOS
x_offset: 0
y_offset: 45
#z_offset: 0
stow_on_each_sample: true
#probe_with_touch_mode: true

[safe_z_home]
home_xy_position: 80,80
speed: 50
z_hop: 10
z_hop_speed: 10

[screws_tilt_adjust]
screw1: -10,-22
screw1_name: right rear screw
screw2: 165,-22
screw2_name: left rear screw
screw3: 165,150
screw3_name: left front screw
screw4: -10,150
screw4_name: right front screw
horizontal_move_z: 15
speed: 50
screw_thread: CW-M3

[z_tilt]
z_positions: 97, 161 
            97, -15 
points: 97,161
        97, -15
speed: 50
horizontal_move_z: 15
retries: 20
retry_tolerance: .01

[bed_mesh]
speed: 50
horizontal_move_z: 5
mesh_min: 25,25
mesh_max: 185,185
algorithm: bicubic
fade_start: 1
fade_end: 5
move_check_distance: 3
probe_count: 5,3
mesh_pps: 2,2
bicubic_tension: 0.8
split_delta_z: .025
relative_reference_index: 7

[gcode_macro _TIMELAPSE_NEW_FRAME]
gcode:
 {action_call_remote_method("timelapse_newframe")}
 ; leave this in a separate macro!

[gcode_macro TIMELAPSE_TAKE_FRAME]
gcode:
  G10
  SAVE_GCODE_STATE NAME=SNAPSHOT
  G1 X175.0 F10000
  G1 Y100.0 F10000
  G4 P500 ;dwell
  M400    ;clear buffer
  _TIMELAPSE_NEW_FRAME
  G4 P250 ;moar dwelling
  M400
  RESTORE_GCODE_STATE NAME=SNAPSHOT MOVE=1
  G11
  

[gcode_macro TIMELAPSE_RENDER]
gcode:
  {action_call_remote_method("timelapse_render")}

[gcode_macro END_PRINT]
gcode:
        #Get Printer built volume dimensions
        {% set X_MAX = printer.toolhead.axis_maximum.x|default(100)|float %}
        {% set Y_MAX = printer.toolhead.axis_maximum.y|default(100)|float %}

        #Fix-up extruder
        G91                                            
        G1 E-2 F2700                                    
        G1 E-1.5 Z0.2 F2400                        
        G1 X5 Y5 F6000                               
        G1 Z10                                     
        G90                                        

        #Present print
        G1 Z{printer.toolhead.position.z + 50} F600
        G1 X100 Y100 F6000
        M106 S0                                      
        M104 S0                                       
        M140 S0                                 

        #Disable Steppers
        M84 X Y E

[gcode_macro START_PRINT]
gcode:
      #Get Printer built volume dimensions
      {% set X_MAX = printer.toolhead.axis_maximum.x|default(100)|float %}
      {% set Y_MAX = printer.toolhead.axis_maximum.y|default(100)|float %}
      {% set Z_MAX = printer.toolhead.axis_maximum.z|default(100)|float %}

      #Get Nozzle diameter and filament width for conditioning
      {% set NOZZLE = printer.extruder.nozzle_diameter|default(0.4)|float %}
      {% set FILADIA = printer.extruder.filament_diameter|default(1.75)|float %}

      #Set Start coordinates of priming lines
      #{% set X_START = 10.0|default(10.0)|float %}
      #{% set Y_START = 20.0|default(20.0)|float %}

      #Calculate Primer line extrusion volume and filament length
      #{% set PRIMER_WIDTH = 0.75 * NOZZLE %}                    
      #{% set PRIMER_HEIGHT = 0.70 * NOZZLE %}           
      #{% set PRIMER_SECT = PRIMER_WIDTH * PRIMER_HEIGHT %}    
      #{% set PRIMER_VOL = PRIMER_SECT * (X_MAX - 3 * X_START) %}    
      #{% set FILA_SECT = 3.1415 * ( FILADIA / 2.0)**2 %}          
      #{% set FILA_LENGTH = 1.55 * PRIMER_VOL / FILA_SECT %}      

      #Get Bed and Extruder temperature from Slicer GCode
      {% set BED_TEMP = params.BED_TEMP|default(60)|float %}
      {% set EXTRUDER_TEMP = params.EXTRUDER_TEMP|default(190)|float %}

      #Preheat nozzle and bed
      M104 S{EXTRUDER_TEMP} T0                        
      M140 S{BED_TEMP}                                

      #Home
      G28
      z_tilt_adjust
      BED_MESH_PROFILE LOAD=default

      #Heat nozzle and bed
      M190 S{BED_TEMP}                               
      M109 S{EXTRUDER_TEMP} T0                       

      #Precondition extruder
      #G92 E0     
      #G1 X{X_START} Y{Y_START} Z{PRIMER_HEIGHT} F6000.0     
      #G1 X{X_MAX - 2 * X_START} Y{Y_START} Z{PRIMER_HEIGHT} F2000.0 
      #G1 X{X_MAX - 2 * X_START} Y{Y_START + PRIMER_WIDTH} Z{PRIMER_HEIGHT} 
      #G1 X{X_START} Y{Y_START + PRIMER_WIDTH} Z{PRIMER_HEIGHT} F2000.0 
      #G92 E0            
      #G1 Z2.0 F600        
      #G1 Z0.2 F600        
      #G1 Z2.0 F600

########################################
# EXP1 / EXP2 (display) pins
########################################

[board_pins]
aliases:
    # EXP1 header
    EXP1_1=P1.30, EXP1_3=P1.18, EXP1_5=P1.20, EXP1_7=P1.22, EXP1_9=<GND>,
    EXP1_2=P0.28, EXP1_4=P1.19, EXP1_6=P1.21, EXP1_8=P1.23, EXP1_10=<5V>,
    # EXP2 header
    EXP2_1=P0.17, EXP2_3=P3.26, EXP2_5=P3.25, EXP2_7=P1.31, EXP2_9=<GND>,
    EXP2_2=P0.15, EXP2_4=P0.16, EXP2_6=P0.18, EXP2_8=<RST>, EXP2_10=<NC>
    # Pins EXP2_1, EXP2_6, EXP2_2 are also MISO, MOSI, SCK of bus "ssp0"

######################################################################
# "RepRapDiscount 128x64 Full Graphic Smart Controller" type displays
######################################################################

[display]
lcd_type: st7920
cs_pin: P1.19
sclk_pin: P1.20
sid_pin: P1.18
encoder_pins: ^P3.26, ^P3.25
click_pin: ^!P0.28
#kill_pin: ^!<RST>

[output_pin beeper]
pin: P1.30

#*# <---------------------- SAVE_CONFIG ---------------------->
#*# DO NOT EDIT THIS BLOCK OR BELOW. The contents are auto-generated.
#*#
#*# [bed_mesh default]
#*# version = 1
#*# points =
#*# 	  -0.265000, -0.105000, -0.062500, -0.082500, -0.215000
#*# 	  -0.192500, -0.050000, 0.000000, -0.047500, -0.202500
#*# 	  -0.162500, -0.057500, -0.050000, -0.102500, -0.245000
#*# tension = 0.8
#*# min_x = 25.0
#*# algo = bicubic
#*# y_count = 3
#*# mesh_y_pps = 2
#*# min_y = 25.0
#*# x_count = 5
#*# max_y = 185.0
#*# mesh_x_pps = 2
#*# max_x = 185.0
#*#
#*# [bltouch]
#*# z_offset = 2.000

**Comment by Sineos** [comment]
BTT SKR1.4? If yes, you have a third temp port with pin P0.23

**Comment by tony21675** [comment]
Yes it is giving false reading on both bed and hot end. Port 3 might be ok but port 1 and 2 both seem to be malfunctioning

**Comment by tony21675** [comment]
BTT SKR1.4 correct

**Comment by Sineos** [comment]
If the issue still persists, please do not hesitate to open a new topic on https://klipper.discourse.group
