### ISSUE TITLE
Bed_Mesh move out of range kills the calibrate process

### ISSUE THREAD

**Issue by d4mer** [Klipper3d/klipper#5083]
When performing the bed mesh calibrate process if you request a move that is out of range of the min/max in the config file, the entire calibrate process is killed and you have to start over. 

This is extremely frustrating and should not work like this.

If an out of range move is requested, we should see the error in the console and should be allowed to rectify the request and be able to continue with the same calibration process. We should not have to start the entire process again.

[bed_mesh]
speed: 120
horizontal_move_z: 5
mesh_min: 35,12
mesh_max: 285, 285
probe_count: 5,3

[klippy.log](https://github.com/Klipper3d/klipper/files/7792460/klippy.log)

**Comment by Sineos** [comment]
A `Move out of range` is a serious error and by all means justifies a shutdown.
Since getting the limits correct is a one-time task it does not really warrant any code change IMO.

Please direct this to https://klipper.discourse.group for potential further discussions
