### ISSUE TITLE
Killing bed mesh process because of a move out of range is not at all justified

### ISSUE THREAD

**Issue by d4mer** [Klipper3d/klipper#5085]
Issue 5083 was closed for an unjustified reason. The functionality described is not warranted even if a move out of range is very serious. More over, on the end stop calibrate process, if you receive an error the process doesn't stop and does let you continue, ergo this is incomplete functionality. 

**There is absolutely no justifiable reason why the process absolutely must be killed** other than lack of time to code it.

When performing the bed mesh calibrate process if you request a move that is out of range of the min/max in the config file, the entire calibrate process is killed and you have to start over.

This is extremely frustrating and should not work like this.

If an out of range move is requested, we should see the error in the console and should be allowed to rectify the request and be able to continue with the same calibration process. We should not have to start the entire process again.

[bed_mesh]
speed: 120
horizontal_move_z: 5
mesh_min: 35,12
mesh_max: 285, 285
probe_count: 5,3

**Comment by Sineos** [comment]
Again, please direct your discussion to https://klipper.discourse.group. The developer is reading there and if he thinks it is worth to implement then he will answer. Apart from this you are welcome to invest the time to code it.
