### ISSUE TITLE
Klipper/OctoPrint Bed issue

### ISSUE THREAD

**Issue by captkmk** [Klipper3d/klipper#5107]
Hello, Ender 5 plus can show a connection to Octoprint it says unable to connect to MCU, I get a lot of features that I can control in OctoPrint, what stands out is after the connection is up and running that the hotend section reads 0.0 (C) and the Bed section goes blank well it shows this symbol  -
And the stock screen displays  (ender-5 plus, CREALITY) no control there and really that's ok but I ask for fresh ideas on this one.

Thanks in Advance

**Comment by Sineos** [comment]
Please post your issue on https://klipper.discourse.group together with your `klippy.log` file

**Comment by Sineos** [comment]
Continue on discourse
