### ISSUE TITLE
Printer error causes full system panic

### ISSUE THREAD

**Issue by cicinovec** [Klipper3d/klipper#5116]
Today I had an error with heater (wire broken) and the system cancelled the print. Safety feature works nicely.
But after the error, the whole system went haywire with pop-up windows all over the screen.
It was impossible to do any available soft restart method, only solution was to power down printer including the Raspberry pi.

Can someone please check the log, if it is Klipper or Octoprint issue? 

Thank you

[octoprint.log](https://github.com/Klipper3d/klipper/files/7824290/octoprint.log)
[plugin_klipper_debug.log](https://github.com/Klipper3d/klipper/files/7824291/plugin_klipper_debug.log)

**Comment by Sineos** [comment]
This is definitively not a Klipper issue. Once Klipper shuts down, it stays shuts down and it does not produce any pop-ups. Please post either on https://klipper.discourse.group or the relevant Octoprint forums.

I'd check the Octoprint settings, if Octoprint tries to continue, despite the shutdown:
* Serial Connection --> Behavior --> Error handling
* Serial Connection --> Firmware & Protocol --> Emergency commands
* Funky Octoprint GCODE scripts or macros
