### ISSUE TITLE
strange bed mesh behavior

### ISSUE THREAD

**Issue by Sterbo88** [Klipper3d/klipper#5121]
by now I have tried everything, I am bent on printing a circle and from any point I start (rear, right, left, front, 45º fill, 0º fill) wherever I start, in that point the nozzle is generally high and then it goes to adapt with the proceed ... increasing the size of the circle the problem is more externally and that's it ... the z compensation I see that it works ... but strange ... I have a ratrig vcore 3 500x500 and I keep the plate warm for hours, but the result does not change
![B4997174-26D1-4753-94C4-73F76027551C](https://user-images.githubusercontent.com/90569738/148581130-0d12e6e6-106c-47fe-bc16-54805890f7e1.jpeg)
![50BA01AA-8FD3-4B2D-AB24-7E4275B510F3](https://user-images.githubusercontent.com/90569738/148581161-e1763894-0861-4984-a6a1-7769d08b00d2.jpeg)
![DB33E560-89ED-413A-B3D6-3E14E7A93E9C](https://user-images.githubusercontent.com/90569738/148581198-9946b1f0-5019-47eb-bd8b-f466423d4f9b.jpeg)
![281349FB-530B-42B8-BBBD-0C16572C263D](https://user-images.githubusercontent.com/90569738/148581334-43e61e2a-f9d1-44a8-a254-4de116856ebd.jpeg)

in the photos of the circles printed with black filament you can see how in certain conditions the slicer makes a slice at the end (where it begins to print) ... and that is fine, instead the start was high.

I believe that if it were a mechanical problem, the point where the nozzle is high would remain in the same place ....  I hope you can help me

**Comment by Sineos** [comment]
Please revert to https://klipper.discourse.group and potentially open a new topic there. There are already similar topics, like https://klipper.discourse.group/t/impossible-bed-mesh-leveling-cr10spro-v2/204/45
