### ISSUE TITLE
menuconfig stm32f401 shall not display CAN interface

### ISSUE THREAD

**Issue by cooked** [Klipper3d/klipper#5122]
While in make menuconfig, selecting STM32F401 as processor model, CAN is available in the communication interface list. However the F401 has no CAN capability according to the datasheet https://www.st.com/resource/en/datasheet/stm32f401cc.pdf

**Comment by KevinOConnor** [comment]
Thanks.  Should be fixed now (commit 4c8d24ae).

-Kevin

**Comment by cooked** [comment]
confirmed. working as expected now. thanks
