### ISSUE TITLE
bytes_invalid=7 print lean

### ISSUE THREAD

**Issue by bihailantian655** [Klipper3d/klipper#5123]
if print a cylinde
mega2560 +ramps 1.6
machine with marlin work fun ，

same machine with klipper print will incline like a Leaning Tower of Pisa

bytes_read=106438 bytes_retransmit=496 bytes_invalid=7 send_seq=5730 receive_seq=5718 .

in the klippy log ， there are a lots of bytes_invalid=7 , is this normal?

**Comment by Sineos** [comment]
If the issue still persists, please do not hesitate to open a topic on https://klipper.discourse.group together with the full klippy.log
