### ISSUE TITLE
Prusa mk2.5s can’t config 

### ISSUE THREAD

**Issue by Jceed117** [Klipper3d/klipper#5128]
i legitimately cannot get any sort of config to work on my mk2.5s.  Started with the mk2 clone profile.  Then tried the generic mini Rambo.  And even  using the mk3 but changing pins and removing things but nothing seems to work. I’d post my errors but it seems to be everything lol

**Comment by Sineos** [comment]
Use https://github.com/Klipper3d/klipper/blob/master/config/generic-mini-rambo.cfg as a basis and open a new topic on https://klipper.discourse.group posting your `klippy.log` file
