### ISSUE TITLE
TMC driver error SKR 2

### ISSUE THREAD

**Issue by DrifterKy** [Klipper3d/klipper#5130]
keep getting this error message:
TMC 'stepper_y' reports error: DRV_STATUS: 00100044 s2ga=1(ShortToGND_A!) ola=1(OpenLoad_A!) cs_actual=16
I can't find anyone else who has had this same issue, have I blown my TMC2209?

**Comment by Camper-man** [comment]
Hey, I had same issue on 'stepper_z'. And yea, it looks like the stepper driver is dead. Which is weird because it was a brand-new board.
