### ISSUE TITLE
Cant get BLtouch to work with skr mini e3 v1.2

### ISSUE THREAD

**Issue by KIKI66666yt** [Klipper3d/klipper#5131]
Hello, I'm trying to configure Klipper to use my bltouch I have on my ender 3 with a BTT SKR mini V1.2 but I keep on getting the error 

"Probe virtual endstop only useful as endstop pin

Once the underlying issue is corrected, use the "RESTART"
command to reload the config and restart the host software.
Printer is halted"

I couldn't figure out why it is doing this. I tried searching up the error, and I found nothing that would help me. Here is my config. 
[config.zip](https://github.com/Klipper3d/klipper/files/7834390/config.zip)

**Comment by Sineos** [comment]
Change
```
[stepper_z]
...
endstop_pin: probe:virtual_endstop
...
```

to

```
[stepper_z]
...
endstop_pin: probe:z_virtual_endstop
...
```
