### ISSUE TITLE
FLsun QQS Firmware -224 doesn't connect to the MCU

### ISSUE THREAD

**Issue by peterlpop** [Klipper3d/klipper#5141]
I have a FLSun - running https://github.com/CobraPi/Klipper-Firmware-FLSUN-QQ-S-Pro-Delta-Printer
It's been running for months - it's great. Thanks for Klipper for all my 4 printers. 

I decided to upgrade the firmware a week ago - using Kiauh, it showed -224 in Kiauh
Then I had to downgrade to above git precompiled -164 (it shows ga1af78cb on CobraPi, but I can't find that commit on Klipper. )

Regardless, with 164 it works but with 224 it will hang at boot or after firmware reset (fluidd) and after 60 seconds it shows "unknown". 

Now I realize I will be told to put this on Fulidd or Kiauh but after 4 days of play, including no Fluidd or Kiauh but straight klipper (like I used to have on my Ender 3, K200 or K280 printers), it's for sure something between my STM32F103 and Klipper 0.10.0-224. (and 225)

I'd be glad to use my printer's robin_mini to check future updates or to downgrade it to earlier 0.10 firmware. Issue I have is I went to several back in October and I had configuration errors (rotation - since it works with -164 and I can't tell which commit that really is, I figured I'd ask around here.

**Comment by Sineos** [comment]
Please open a topic on https://klipper.discourse.group and post your klippy.log file.
Please note that we will only support Klipper from the official sources
