### ISSUE TITLE
Unable to load panel preheat

### ISSUE THREAD

**Issue by xArgentiusx** [Klipper3d/klipper#5151]
Hello everybody,

since the last Update of klipperscreen it is not possible to get to the Preheat Section from the Main Menu.
The Screen show: Unable to load panel preheat.
When i go to Action/ Temprature the Preheat Section worked. but not from Homescreen. It worked very well, since the last update
[KlipperScreen.log](https://github.com/Klipper3d/klipper/files/7864935/KlipperScreen.log)

best regards
David

**Comment by Sineos** [comment]
Please post your issue on https://klipper.discourse.group. There is a dedicated KlipperScreen section.
