### ISSUE TITLE
corner problem

### ISSUE THREAD

**Issue by Biglilo** [Klipper3d/klipper#5166]
Hello,

This is frist to use github, and my English is not good, sorry. 

I printed something like this:
[https://github.com/Biglilo/Hello/blob/master/image/sliced.png](url)

But when it printed, it like this:
[https://github.com/Biglilo/Hello/blob/master/image/printed.png](url)

The corner looks like zoom out. I measured the distance X, Y is OK. Now I don't know what happend and which parameter control the corner printing.

My board is MKS Monster8, driver is MKS TMC2225, use raspberry pi 4, OS is fluiddpi-rpi-lite-v1.16.2.
My printer.cfg is here:
[https://github.com/Biglilo/Hello/blob/master/cfg/printer_MKS_Monster8.cfg](url)

How I can control the corner printing?

Thanks and greetings
Biglilo

**Comment by Sineos** [comment]
Please open a topic on https://klipper.discourse.group
This is not a Klipper issue. Judging from the images it looks like an extrusion / mechanical problem
