### ISSUE TITLE
Printer shutting down in the middle of BED_MESH_CALIBRATE

### ISSUE THREAD

**Issue by hapklaar** [Klipper3d/klipper#5169]
While doing a BED_MESH_CALIBRATE sometimes the printer shuts down before it finishes with message "Probing failed due to printer shutdown"

When I try again it usually completes.

In klippy.log (last occurence @ line 52547) I see the following problem:

```
TMC 'stepper_z2' reports GSTAT:      00000004 uv_cp=1(Undervoltage!)
Transition to shutdown state: TMC 'stepper_z2' reports error: GSTAT:      00000004 uv_cp=1(Undervoltage!)
```

Do I have a PSU problem, bad driver or maybe Klipper issue? It seems to always happen for stepper_z2.

[klippy.zip](https://github.com/Klipper3d/klipper/files/7883567/klippy.zip)

**Comment by Sineos** [comment]
Please refer to the similar discussions on https://klipper.discourse.group, like https://klipper.discourse.group/search?q=Undervoltage
