### ISSUE TITLE
Klipper stopped working after webcam plugged into PI

### ISSUE THREAD

**Issue by Urminme** [Klipper3d/klipper#5171]
I recent tried using a webcam with my new voron 2.4 and once i plugged it in and restarted the system loads on my voron screen but every time i try to acssess it my computer says conection interupted, I dont have any log to give as i can acssess my system. I also tried to SSH  and this wont work now either

**Comment by Sineos** [comment]
This is not a Klipper issue. Please open a topic on https://klipper.discourse.group along with more information. This looks like a problem with your SBC
