### ISSUE TITLE
Mid print shutdown

### ISSUE THREAD

**Issue by pmarkiewicz** [Klipper3d/klipper#5177]
This happened few times already, print just stopped, I cannot see any pattern. Excatly same file prints ok and next time crashes.
Log attached with M112
[klippy-1.txt](https://github.com/Klipper3d/klipper/files/7904299/klippy-1.txt)

**Comment by Sineos** [comment]
GH is only used to share development results, so it is very unlikely to get any further responses here.
Please post your request on https://klipper.discourse.group/
