### ISSUE TITLE
SKR3 mini v3 turbo

### ISSUE THREAD

**Issue by orge1970** [Klipper3d/klipper#5187]
My host runs on 100% and crashes because of this.
I run on Rpi 3 and moon raker on ender 3 pro

What can cause this ?
[klippy.log.download.zip](https://github.com/Klipper3d/klipper/files/7920474/klippy.log.download.zip)
d

**Comment by Sineos** [comment]
Please open a topic on https://klipper.discourse.group. This is not the right place to discuss such topics as it focuses on Klipper development.
