### ISSUE TITLE
MCU 'mcu' shutdown: Timer too close with SKR Mini E3 1.2 and Debian VM

### ISSUE THREAD

**Issue by Anon0ne** [Klipper3d/klipper#5192]
```
MCU 'mcu' shutdown: Timer too close
This often indicates the host computer is overloaded. Check
for other processes consuming excessive CPU time, high swap
usage, disk errors, overheating, unstable voltage, or
similar system problems on the host computer.
Once the underlying issue is corrected, use the
"FIRMWARE_RESTART" command to reset the firmware, reload the
config, and restart the host software.
Printer is shutdown
```

I am using a Debian VM on my PowerEdge R710, and it has 4 cores and 4 gigs of ram. I have had tons of successful prints, until this latest one. I am even a little bit slower than normal due to printing PETG and not PLA. I have had this issue several times with OctoPrint as well. I will have several successful prints, and then all of a sudden I will have a print that fails about 25% or 50% through. I cannot figure out any issues on the PC end, there aren't errors in the DMESG, and there is very little CPU/RAM usage on the VM. Attached are my logs, this issue has been intermittent until this print. Usually I can clear the bed, restart the print and it will finish. Not this time! I have attached the GCODE also for that print.

[CE5_Ender3_DD_Adapter_BMG_HMGen5.zip](https://github.com/Klipper3d/klipper/files/7929644/CE5_Ender3_DD_Adapter_BMG_HMGen5.zip)

[klippy (8).log](https://github.com/Klipper3d/klipper/files/7929638/klippy.8.log)
[moonraker (4).log](https://github.com/Klipper3d/klipper/files/7929639/moonraker.4.log)

**Comment by Sineos** [comment]
Being an intermittent issue, please post on https://klipper.discourse.group. Other who might have the same constellation can chime in.
Github shall only be used for development purposes. Thanks.
