### ISSUE TITLE
BTT SKR 1.4 neopixel not working properly

### ISSUE THREAD

**Issue by masgar** [Klipper3d/klipper#5193]
Klipper version v0.10.0-237-g28b568a6
Connected 3 RGB (WS2812B) chained leds to neopixel pins on SKR 1.4 tried set_led command with following result:

SET_LED LED=leds RED=1.0 GREEN=0.0 BLUE=0.0 --> ALL LED OFF
SET_LED LED=leds RED=0.0 GREEN=1.0 BLUE=0.0 --> LED 1 OFF, LED 2 and 3 PURPLE
SET_LED LED=leds RED=0.0 GREEN=0.0 BLUE=1.0 --> ALL LED WHITE
SET_LED LED=leds RED=0.0 GREEN=1.0 BLUE=1.0 --> ALL LED GREEN
SET_LED LED=leds RED=1.0 GREEN=1.0 BLUE=1.0 --> ALL LED WHITE

and so on.

I changed color_order with RGB and GBR and also RGBW and GBRW even if my leds are RGB with different but always wrong result.

Tried my leds with and Arduino UNO using both neopixel and fastled libraries and they work fine.
Installed neopixel python library on my raspberry running klipper and created a simple script to test colors and indexes and worked fine.

Tried another SKR 1.4 board in case my one has some fault but no changes.

Here my led.cfg I import in printer.cfg:

[neopixel leds]
pin: P1.24
chain_count: 1
color_order: GRB
initial_RED: 1.0
initial_GREEN: 0.0
initial_BLUE: 0.0
#initial_WHITE: 0.0

I also changed the ~/klipper/klippy/extras/neopixel.py to add BGR color_order like in FR #5160 
Don't know what else to try.

Thanks.

**Comment by jakep82** [comment]
Neopixels use 5v logic.  The SKR 1.4 uses 3.3v logic.  In some cases neopixels will work with 3.3v logic, but it's not guaranteed.  If you have an Uno, just add it as a second MCU in Klipper and use that to control the neopixels since it uses 5v logic.

**Comment by Sineos** [comment]
With the SKR 1.4 you can use https://www.biqu.equipment/collections/expansion-board/products/bigtreetech-dcdc-mode-v1-0-power-module3d-printer-parts to provide 5V to the NPWR pins

**Comment by masgar** [comment]
I installed the BTT DCDC module and checked with a multimeter and I have the 5v

Thanks

**Comment by masgar** [comment]
I have it. And also set the proper jumper. 

Thanks

Inviato da iPhone

**Comment by jakep82** [comment]
5v power isn't the problem.  Unless that DCDC converter has a logic level shifter, you're still feeding the neopixel 3.3v logic from the gpio pin.

**Comment by Sineos** [comment]
Not the DCDC, this just supplies enough power to drive the LED. The LED-PWM (1.24) pin should have this functionality (although I never tested it with my board):
![grafik](https://user-images.githubusercontent.com/4459312/151058019-456dde58-bd05-4454-b2f3-1b914a015192.png)

https://www.nexperia.com/products/analog-logic-ics/asynchronous-interface-logic/buffers-inverters-drivers/series/74LVC1G125.html

**Comment by masgar** [comment]
Seems Jakep82 is right. I added an Arduino UNO and used to drive my leds and it worked like a charm. So I wated my money by purchasing the BTT DCDC module....

I wonder if I can replace the UNO with a Nano to save spac

Thanks

**Comment by Gilabite** [comment]
yes a nano will work too

**Comment by jakep82** [comment]
> Seems Jakep82 is right. I added an Arduino UNO and used to drive my leds and it worked like a charm. So I wated my money by purchasing the BTT DCDC module....
> 
> I wonder if I can replace the UNO with a Nano to save spac
> 
> Thanks

You might still be able to use the SKR to control the neopixels, but you'll need to experiment with resistors on the data line.  That said this has veered entirely off topic, and is not a Klipper issue.  If you want to have a discussion on driving Neopixels from various control boards, that conversation should happen on Discourse.

<https://learn.adafruit.com/adafruit-neopixel-uberguide/best-practices>

**Comment by masgar** [comment]
Jakep agree with you is not a Klipper issue. Thanks for precious help.

**Comment by Sineos** [comment]
Just for future reference: I connected a WS2812B strip with 120 LEDs to my BTT SKR 1.4T with DCDC module installed and it works as expected.

```
[neopixel leds]
pin: P1.24
chain_count: 120
color_order: GRB
initial_RED: 0.0
initial_GREEN: 0.0
initial_BLUE: 0.0
```
