### ISSUE TITLE
MAX31865 and TMC5160 on shared SPI bus doesn't work (stm32f429)

### ISSUE THREAD

**Issue by Serbitor** [Klipper3d/klipper#5198]
I have an stm32f429 board (octopus pro).
I have two TMC5160 stepper modules installed and an on-board MAX31865, these are all wired (by the board) to SPI1.

When both TMC5160 and MAX31865 are configured using hardware SPI no temperature readings are possible and the printer goes immediately into shutdown.

After removing the configuration for TMC5160 drivers entirely and restarting firmware, the MAX31865 readings start working and provide the correct values.

If I convert all three devices (TMC5160 *2 and MAX31865) to use software SPI all three devices work correctly. 

The relevent pins are these:
spi1_sclk: PA5
spi1_miso: PA6
spi1_mosi: PA7
TMC5160 stepper_x cs:  PD11
TMC5160 stepper_x cs:  PC4
MAX31865 cs: PF8

Broken config sections with hardware SPI:

```
[tmc5160 stepper_x]
cs_pin: PD11
spi_bus: spi1
run_current:  2.500

[tmc5160 stepper_y]
cs_pin: PC4
run_current:  2.500
hold_current: 2.000
spi_bus: spi1

[extruder]
step_pin: PE6
dir_pin: PA14
enable_pin: !PE0
microsteps: 16
rotation_distance: 4.54
nozzle_diameter: 0.330
filament_diameter: 1.750
heater_pin: PA2
control: pid
[klippy.log](https://github.com/Klipper3d/klipper/files/7945183/klippy.log)

min_temp: 0
max_temp: 300
pid_Kp: 15.247
pid_Ki: 0.664
pid_Kd: 87.479
pressure_advance: 0.06
sensor_type: MAX31865
sensor_pin: PF8
spi_bus: spi1
rtd_nominal_r: 1000
rtd_reference_r: 4300
```

Working config sections with software SPI:

```
[tmc5160 stepper_x]
cs_pin: PD11
spi_software_sclk_pin: PA5
spi_software_miso_pin: PA6
spi_software_mosi_pin: PA7
run_current:  2.500
hold_current: 2.000

[tmc5160 stepper_y]
cs_pin: PC4
run_current:  2.500
hold_current: 2.000
spi_software_sclk_pin: PA5
spi_software_miso_pin: PA6
spi_software_mosi_pin: PA7

[extruder]
step_pin: PE6
dir_pin: PA14
enable_pin: !PE0
microsteps: 16
rotation_distance: 4.54
nozzle_diameter: 0.330
filament_diameter: 1.750
heater_pin: PA2
control: pid
min_temp: 0
max_temp: 300
pid_Kp: 15.247
pid_Ki: 0.664
pid_Kd: 87.479
pressure_advance: 0.06
sensor_type: MAX31865
sensor_pin: PF8
spi_software_sclk_pin: PA5
spi_software_miso_pin: PA6
spi_software_mosi_pin: PA7
rtd_nominal_r: 1000
rtd_reference_r: 4300
```

Config example for working hardware SPI on MAX31865
```
#[tmc5160 stepper_x]
#cs_pin: PD11
#spi_bus: spi1
#run_current:  2.500

#[tmc5160 stepper_y]
#cs_pin: PC4
#run_current:  2.500
#hold_current: 2.000
#spi_bus: spi1

[extruder]
step_pin: PE6
dir_pin: PA14
enable_pin: !PE0
microsteps: 16
rotation_distance: 4.54
nozzle_diameter: 0.330
filament_diameter: 1.750
heater_pin: PA2
control: pid
min_temp: 0
max_temp: 300
pid_Kp: 15.247
pid_Ki: 0.664
pid_Kd: 87.479
pressure_advance: 0.06
sensor_type: MAX31865
sensor_pin: PF8
spi_bus: spi1
rtd_nominal_r: 1000
rtd_reference_r: 4300
```

**Comment by Serbitor** [comment]
[klippy.log](https://github.com/Klipper3d/klipper/files/7945192/klippy.log)

**Comment by Serbitor** [comment]
I have reports that this also happens on the F446 version of the board.

**Comment by bigtreetech** [comment]
Hello, Please test https://github.com/Klipper3d/klipper/pull/5250

**Comment by Serbitor** [comment]
Initial test (no printing) looks good. I will update once i try printing. Thanks!

**Comment by Serbitor** [comment]
It doesn't look like this fixes things, i must have made an error when playing earlier.
Certainly running the modified firmware now and it fails in the same way as before.
Thanks for looking into this!

**Comment by KevinOConnor** [comment]
It is thought that this is now fixed (commits 99d55185 and e3cbe7ea).

-Kevin

**Comment by Serbitor** [comment]
Looks good to me! print running now. Thanks!

**Comment by popshansen** [comment]
I can confirm the shared spi is working, I do have BTT Octopus Pro with TMC5160Pro and Fysctec mini12864 connected.
At first after the mcu update, it didn't work (unable to write tmc spi 'stepper_x' register globalscaler).
I don't use the MAX31865 so when I added those two lines:

[static_digital_output disable_max31865]
pins: !PF8

It worked.

/Lars

**Comment by SemperDiscere** [comment]
> I can confirm the shared spi is working, I do have BTT Octopus Pro with TMC5160Pro and Fysctec mini12864 connected. At first after the mcu update, it didn't work (unable to write tmc spi 'stepper_x' register globalscaler). I don't use the MAX31865 so when I added those two lines:
> 
> [static_digital_output disable_max31865] pins: !PF8
> 
> It worked.
> 
> /Lars

I can confirm this resolves the issue.
Octopus Pro
TMC5160
No Max31865
No LCD
