### ISSUE TITLE
Pi won't communicate given USB-ID

### ISSUE THREAD

**Issue by bogeyf14** [Klipper3d/klipper#5218]
##Issues: 

Could not get klipper via mainsail to communicate with BTT Octopus

##Conditions:
Used the following command to acquire the USB-id
![USB-ID](https://user-images.githubusercontent.com/34655838/151907636-c7843a29-0863-4ddc-adc6-1781a786348f.jpg)

and entered it into the config
![config](https://user-images.githubusercontent.com/34655838/151907693-185ca012-a961-41d7-910f-188d8cb84444.jpg)

Klipper would not connect to the board. 

##Solution 

Once I changed the "serial:" line to 
"serial: dev/ttyACM0"

The boards would then communicate

**Comment by jakep82** [comment]
Remove {} from your serial device line.

**Comment by bogeyf14** [comment]
🤦
