### ISSUE TITLE
Toolhead Drift While running Test_Resonances

### ISSUE THREAD

**Issue by bogeyf14** [Klipper3d/klipper#5232]
**Issue:**  Toolhead drifts in the negative X direction while running TEST_RESONANCES for both x or Y axis
https://photos.app.goo.gl/UtKrojTV2axSZtcaA

**Clues:** 
- The steppers have an odd sound when the toolhead drifts
- negative X drift means that both steppers are synchronized
- shaper_calibrate graph shows multiple minor peaks where drift is occurring. 120Hz peak is the true natural frequency of the machine.

**Hardware:** 
- Mellow Super infinity HV
- BTT tmc5160 Pro @ [48V]([url](url))

**Driver Config:**
```
[stepper_x]
step_pin: PE2  # Drive0
dir_pin: !PC5
enable_pin: !PF11
microsteps: 32
rotation_distance: 40
endstop_pin: tmc5160_stepper_x:virtual_endstop ##PC0     #PG12  # IO0
position_endstop: 0
position_max: 120
homing_speed: 70
homing_retract_dist: 0
homing_positive_dir: false

[tmc5160 stepper_x]
cs_pin: PC4
spi_bus: spi3
diag1_pin: ^!PG12
interpolate: False
run_current: .8#1   # for 52mms max hold is 1.060 
sense_resistor: 0.075
driver_SGT: 1#1 @1.2amp
```

**Klippy Log:**
[klippy.log](https://github.com/Klipper3d/klipper/files/8004485/klippy.log)

![shaper_calibrate_y](https://user-images.githubusercontent.com/34655838/152561726-56bd593d-6729-4e16-bf22-d1b38ca4d951.png)
A

**Comment by Sineos** [comment]
Please do not cross post
