### ISSUE TITLE
BiquBX was addded to Klipper but temp not working

### ISSUE THREAD

**Issue by nicedevil007** [Klipper3d/klipper#5236]
Hey guys, I was happy to see that the BiquBX's mainboard was added to Klipper.
We started today on configuring everything with the example cfg provided by https://github.com/Klipper3d/klipper/commit/c15d38b973a56978535f36c0fe61f5f8de468248

Unfortunately the bed temperature isn't working at all, so maybe there seems to be still an issue with the board? It was working with marlin before.

![image](https://user-images.githubusercontent.com/17103076/152660635-8d6a9a8d-82cb-49ed-90d9-561d7e1902a3.png)

**Comment by adelyser** [comment]
There is an issue with the ADC for the STM32H7. I think I have a fix and I'm testing it, hopefully I can get a PR up soon for it.

FYI: There isn't an issue with your hardware, this is a confirmed problem with the ADC.

**Comment by nicedevil007** [comment]
Could it be the case, that it is just reading 200°C too much?

**Comment by adelyser** [comment]
No, it's an issue with the peripheral being reset when it shouldn't be.

**Comment by nicedevil007** [comment]
and that leads to 200°C more on the ADC? wtf, but ty for clearing this up, hope you can fix it, otherwise we can only print PLA xD

**Comment by adelyser** [comment]
I have a fix submitted in PR #5239, if you want to try that.

**Comment by nicedevil007** [comment]
So the PR was applied by updating Klipper over WebUI (mainsail)

![image](https://user-images.githubusercontent.com/17103076/152729604-09eb089e-07fe-4f42-af9d-3c229dc6fbcc.png)

Unfortunately it doesn't fix the issue, temp of bed still 220°C without heating anything

![image](https://user-images.githubusercontent.com/17103076/152729649-442e48a8-875b-4bd0-b5ec-8f43576c180b.png)

**Comment by adelyser** [comment]
The fix has been confirmed by several users now. So you updated klipper, did you clean, rebuild, and re-flash the mainboard? That is required for this fix.

**Comment by ZeroCoolAT** [comment]
Hi adelyser,

thanks for the fix, tipps and information to re-flash.
Got it now running (after re-flash) with the correct temperature.

Geat job!

**Comment by nicedevil007** [comment]
Yeah it did work for me now as well, just thought that there would be a Warning or Error in the webui that is telling me that we have to reflash (was the case for other firmware changes in the past)... thats why I didn't do it on my first attemp.

Thank you very much!
