### ISSUE TITLE
Klipper is crashing after filament sensor triggering.

### ISSUE THREAD

**Issue by AssafKatan** [Klipper3d/klipper#5238]
Hello I have the klipper firmware on my cr10spro v2 and it worked great, but now when I try to use the filament sensor mid print it is just crashing the klipper right away.
But that only happen after few hours of print, like if I just cut the filament after an hour or so it is working great.
I can't really tell the problem
Adding the config and the logs.
[printer.zip](https://github.com/Klipper3d/klipper/files/8010491/printer.zip)

**Comment by schnello** [comment]
Hello.


[dgus_display] is a option from original Klipper git?

**Comment by Sineos** [comment]
Closed as invalid. Not original Klipper
