### ISSUE TITLE
Homing failed due to printer shutdown

### ISSUE THREAD

**Issue by M7medd** [Klipper3d/klipper#5241]
hello
first sorry about my english 
i run klipper on raspbery pi 3 and btt octopus v1.1 when i trying homing if there any retract distance in any one of the axes the printer restart immediatly after retract i set retract distance for all axes to zero and homing done when i tried to bed mesh calibrate or screw tilt calibrate the issue show up again ((Probing failed due to printer shutdown))
please i need your help fast
[klippy.log](https://github.com/Klipper3d/klipper/files/8017953/klippy.log)

**Comment by dallerman** [comment]
"Transition to shutdown state: MCU 'mcu' shutdown: Timer too close
This often indicates the host computer is overloaded. Check
for other processes consuming excessive CPU time, high swap
usage, disk errors, overheating, unstable voltage, or
similar system problems on the host computer."

On line 1323 of the logfile you can see the following lines. PI3 is not the most powerful machine so try a clean install of your PI config

**Comment by M7medd** [comment]
okay i tried pi 4 with new sd card and same issu
[klippy.log](https://github.com/Klipper3d/klipper/files/8018382/klippy.log)
e

**Comment by dallerman** [comment]
Did you use the same install as for PI3 or did you do a clean install?

**Comment by M7medd** [comment]
i did a clean install with new sd card

**Comment by M7medd** [comment]
@dallerman okay i found the problem
at the begining in the make menu of klipper to make the firmware.bin file the default clock reference is 8 MHZ but the octopus is 12 MHZ
![after](https://user-images.githubusercontent.com/13569159/152872111-c99bc65f-346c-4d18-8c1e-bd217a34dc3d.PNG)
![before](https://user-images.githubusercontent.com/13569159/152872119-8e343e56-c7f9-4eb6-aeec-2f176ab3a50b.PNG)
thanks for your help 
i'll close it
