### ISSUE TITLE
Python 3: BED_MESH_CALIBRATE error: Invalid y-axis table length

### ISSUE THREAD

**Issue by CODeRUS** [Klipper3d/klipper#5248]
After switching to python3 bed mesh calibration works incorrectly.

With python2 it probes points:
```
--x--
-xxx-
xxxxx
-xxx-
--x--
```

after switching to python3:
```
-xx-
xxxx
xxxx
-xx-
```

mesh config:
```
[bed_mesh]
speed: 80
horizontal_move_z: 18
mesh_radius: 110
round_probe_count: 5
```

[klippy.log](https://github.com/Klipper3d/klipper/files/8025770/klippy.log)

**Comment by CODeRUS** [comment]
in file https://github.com/Klipper3d/klipper/blob/master/klippy/extras/bed_mesh.py#L319

```
new_r = (x_cnt / 2) * x_dist
```

in python2 it returns int:
```
>>> (5 / 2) * 55
110
```

in python3 float:
```
>>> (5 / 2) * 55
137.5
```

solution is to simple use `int()`, but i am wondering if there more complex issues caused by this change

**Comment by KevinOConnor** [comment]
@Arksine - do you have any thoughts on this?  We can make the behaviour the same between python versions with `(x_cnt // 2) * x_dist` if that is desired.

-Kevin

**Comment by Arksine** [comment]
Yeah, I agree that we need to use integer division there.  I looked through the rest of the module and I think that is the only one we missed.
