### ISSUE TITLE
Feature Request: more responsive Z_adjust for first layer adjustment

### ISSUE THREAD

**Issue by lorroi** [Klipper3d/klipper#5271]
So I've been trying out Klipper coming from Marlin as I was interested in the neat features it comes with. I use an inductive bed probe that drifts a bit with temperature, so one that I value a lot in Marlin in the Z-live adjust feature. 
Klipper also has this feature, however it is very laggy. When I observe the first layer being layed dowon and notice the nozzle is too close/far away from the bed, and then use the Z_adjust feature on the LCD screen or in Mainsail it takes 5-10 seconds to have an effect (whereas in Marlin Z-live adjust takes effect the moment I turn the knob). 
Would it be possible to implement the z_adjust to be instantaneous (at least while in the first layer)?

Thanks :)

PS: I run klipper on a RasPi model 3 B, and an SKR 1.4 Turbo.

**Comment by Sineos** [comment]
As already noted when you opened this topic: GitHub shall only be used for development purposes. Please be so kind to open such topics on https://klipper.discourse.group/ as Feature Request
