### ISSUE TITLE
new board: robin nano 1.3 cannot upload firmware on sdcard (it works for name: firmware.bin)

### ISSUE THREAD

**Issue by pappicio** [Klipper3d/klipper#5272]
I've found all needed to upload klipper firmware on 3d printer by script:
 'robin-nano-13': {
        'mcu': "stm32f407xx",
        'spi_bus': "swspi",
        'spi_pins': "PC8,PD2,PC12",
        "cs_pin": "PC11",
        "firmware_path": "robin_nano35.bin",
        "current_firmware_path": "robin_nano35.cur"
}
but give me error when upload firmware, while if I delete the last 2 lines:
 'robin-nano-13': {
        'mcu': "stm32f407xx",
        'spi_bus': "swspi",
        'spi_pins': "PC8,PD2,PC12",
        "cs_pin": "PC11",
 }
all works, but no update, cos I find on sdcard "firmware.bin" but it needs "robin_nano35.bin" file to flash it on mobo.
thanks

**Comment by Sineos** [comment]
As already noted when you opened this topic: GitHub shall only be used for development purposes. Please be so kind to open such topics on https://klipper.discourse.group 

Otherwise also see here:
https://www.klipper3d.org/SDCard_Updates.html#caveats
