### ISSUE TITLE
!! BLTouch failed to deploy

### ISSUE THREAD

**Issue by selimayaz** [Klipper3d/klipper#5276]
maybe too many asked but i've stacked here. bltouch commands work (pindown, pinup, self_test, reset) but when homing it's failed to deploy. cables are ok updates installed (also fresh install with new sd) any suggestions? "and how to add klippy.log :D"

16:59:30 
$ [FIRMWARE_RESTART]()
16:59:38 
// Failed to verify BLTouch probe is raised; retrying.
16:59:40 
// Failed to verify BLTouch probe is raised; retrying.
16:59:41 
// Klipper state: Ready
16:59:43 
$ [G28]()
16:59:47 
!! BLTouch failed to deploy
16:59:48 
// Failed to verify BLTouch probe is raised; retrying.
16:59:49 
// Failed to verify BLTouch probe is raised; retrying.

**Comment by Sineos** [comment]
As already noted when you opened this topic: GitHub shall only be used for development purposes. Please be so kind to open such support topics on https://klipper.discourse.group/ and attach your klippy.log file there.

Where to find the log: `/tmp/klippy.log` on your Raspberry Pi or similar SBC
