### ISSUE TITLE
Move out of range

### ISSUE THREAD

**Issue by Steven2k6** [Klipper3d/klipper#5279]
Hey, I set up klipper and I had to change the rotaion distance right.
After I did that, I get this output: "Move out of range: 280.993 267.732 25.300 [15.079]"
This happens after the homing and I tested a bit and I guess it is there, where the printer really starts printing.

**Comment by ld3300** [comment]
Hi @Steven2k6,

This is almost always either a configuration problem or an issue with relative vs absolute position settings.  If you go to to the discord server and post the issue and your printer.cfg in the print-help channel you are likely to get help.  Feel free to also send me the file and I can look it over.  The discord is: [https://discord.com/channels/431557959978450984/802921046452731944](https://discord.com/channels/431557959978450984/802921046452731944)

**Comment by Steven2k6** [comment]
Okay, thanks, should I send it to you in this issue?

**Comment by jakep82** [comment]
We don't use GitHub for help requests.  Please post this request on Discord or Discourse.

<https://www.klipper3d.org/Contact.html#help-it-doesnt-work>

**Comment by Steven2k6** [comment]
Thanks guys, I got help, have a nice day
