### ISSUE TITLE
add long file name (LNF) on ffconf.h and .py related files

### ISSUE THREAD

**Issue by pappicio** [Klipper3d/klipper#5282]
Hi, why we are locked on 8+3 namefile, my motherboard wants firmware called:robin_nano35.bin, is longer, I also added on ffconf.h long file name, but give error on spi_flash.py at retreive fileinfo on robin_nano.bin fileinfo when validate uploaded firmware.

**Comment by Sineos** [comment]
What board are you using exactly?
As stated in the documentation, it will not work for Robin v1 and v2 variants and Robin E3 is already supported.

Due to short comings with v1 and v2 (IIRC, something with resetting the board after the upload) this feature will not be implemented

**Comment by Sineos** [comment]
Topic seems concluded. If you need further assistance please open a topic on https://klipper.discourse.group/
