### ISSUE TITLE
Wrong "pin xx is reserved for spi" request

### ISSUE THREAD

**Issue by Schnabulation** [Klipper3d/klipper#5283]
In trying to enable a BTT 12864 Mini display I built a special cable to connect the EXP3 port of my mainboard to the EXP1 and EXP2 port of the display.
I can then configure the respective pins in my configuration, however I always get the error that some of the pins from the EXP3 port are reserved for SPI2. I know the display works without a SPI-connection but I can not start Klipper with this configuration because it always requests these port to be configured for SPI2.

Is there a setting that can override this request?

Board: Creality V 4.2.2

printer.cfg - respective section
`[display]`
`lcd_type: uc1701`
`cs_pin: PB13`
`a0_pin: PB15`
`rst_pin: PB12`
`encoder_pins: ^PB14, ^PB10`
`click_pin: ^!PB2`
`#spi_software_miso_pin: PC7`
`#spi_software_mosi_pin: PB11`
`#spi_software_sclk_pin: PB12`

`[neopixel mini12864]`
`pin: PC6`
`chain_count: 3`
`color_order: RGB`
`initial_RED: 0.4`
`initial_GREEN: 0.4`
`initial_BLUE: 0.4`

**Comment by Sineos** [comment]
As already noted when you opened this topic: GitHub shall only be used for development purposes. Please be so kind to open such topics on https://klipper.discourse.group/ together with your klippy.log fiel.

**Comment by Schnabulation** [comment]
I have created this ticket because I believe this is an issue and not a personal request. But in this case I will go ahead and post the request on discourse.

**Comment by Schnabulation** [comment]
To update on that - in case anyone reads this: It is possible to connect the stock mainboard to the 12864 mini, but you need to extra pins from the connector right above the EXP1 connector on the board (labeled SWDIO and SWCLK).

**Comment by exiom-hk** [comment]
> To update on that - in case anyone reads this: It is possible to connect the stock mainboard to the 12864 mini, but you need to extra pins from the connector right above the EXP1 connector on the board (labeled SWDIO and SWCLK).

Hi, Sorry for reopening this ticket as I could not find a way to contact the original poster @Schnabulation, but I would very much like to know the pin out and config to make this work. Thanks!

**Comment by Schnabulation** [comment]
Hi @exiom-hk

I have posted a wiring diagram over on reddit - you can find it in this thread: https://www.reddit.com/r/klippers/comments/sw9mej/12864_mini_display_working_with_stock_creality

I hope this helps you!
