### ISSUE TITLE
Emergency Shutdown requires full powering off RPi

### ISSUE THREAD

**Issue by FlatEarthDave** [Klipper3d/klipper#5285]
When using the emergency shutdown, "Restart Firmware" no longer works. The error message `Shutdown due to webhooks request
Once the underlying issue is corrected, use the
"FIRMWARE_RESTART" command to reset the firmware, reload the
config, and restart the host software.
Printer is shutdown` will not change, no matter how long you wait. A full shutdown is necessary, as a reboot through the Fluidd GUI still shows the error.

It's possible it is a Fluidd problem, but I have no way of telling, that I know of.

**Comment by Sineos** [comment]
As already noted when you opened this topic: GitHub shall only be used for development purposes. Please be so kind to open such support topics on https://klipper.discourse.group/ and attach your klippy.log file there.
