### ISSUE TITLE
MCU 'mcu' shutdown: Timer too close

### ISSUE THREAD

**Issue by AndehX** [Klipper3d/klipper#5288]
I have  Tronxy X5SA-Pro with the Chitu v6 board.  I can print for quite a while (like around 12 hours) before randomly getting this error, which ruins my print.  Running Klipper on a RPi 3B, which is running standard Raspbian.  I've attached part of klippy.log.  Can anyone tell me what the hells going on?  It's driving me insane.
[klippy.log](https://github.com/Klipper3d/klipper/files/8103780/klippy.log)

**Comment by cbc02009** [comment]
This is best discussed on the discourse forums, not on github. Github is for developer issues.

**Comment by myung** [comment]
I have a X5SA and I have same problem. Since few day ago.

**Comment by AndehX** [comment]
I've wired up the serial connection from my raspberry pi directly to the mainboard to bypass the USB to serial chip, to see if this helps, as I've read that these cheap boards can use knock-off clone chips.  I'll update if i still have issues.

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
