### ISSUE TITLE
About 5015 Fan Speed ReMapping

### ISSUE THREAD

**Issue by yyxp1989** [Klipper3d/klipper#5289]
Hello, my printing fan has been modified with a 5015 blower fan. When I print ABS, I need 15% fan speed, but there is a problem with the speed regulation. The minimum speed of this fan is M106 S197, 76%. How do I remap S197 - S255 to 1%-100%?

[fan]
pin: rpi:gpio14
max_power: 1.0
kick_start_time: 1.00
hardware_pwm: False
off_below: 0.76

**Comment by cbc02009** [comment]
these questions are best asked on the klipper discourse forum: https://klipper.discourse.group/ or on discord. Github issues are only for development, so you won't find any help here, sorry.

**Comment by yyxp1989** [comment]
> 您好，我的打印风扇已经改装为5015鼓风机。打印ABS时，需要15%的风扇转速，但是调速有问题。这个风扇的最低转速是M106 S197，76%。如何将 S197 - S255 重新映射为 1%-100%？
> 
> [风扇] pin：rpi：gpio14 max_power：1.0 kick_start_time：1.00 hardware_pwm：False off_below：0.76
