### ISSUE TITLE
IDEX Sensorless Homing

### ISSUE THREAD

**Issue by SiCFPV** [Klipper3d/klipper#5292]
Hello, 

I have a Fysetc Spider V1.1 with TMC2209 and after checking all config, It's everything working, but when I set SET_TMC_FIELD at 255 for the dual_carriage, doesn´t seem to work. it's moving and I changed the pin but no success. I tried already a few combinations, also changed X stepper driver to match with the DiagX+. 
Stepper X runs normal and works like it should. Any ideias on what's happening?
[klippy.log](https://github.com/Klipper3d/klipper/files/8104842/klippy.log)

**Comment by Sineos** [comment]
As already stated when you opened the ticket: Issues here are for development only. Please be so kind to place your support request on: https://klipper.discourse.group/
