### ISSUE TITLE
Object cooling fan PWM

### ISSUE THREAD

**Issue by AntoszHUN** [Klipper3d/klipper#5293]
Hi!

I'd like to know about the object cooling fan. I have a little problem and I can't find an answer anywhere. I hope you can help.

The object cooling fan operates at 0-255 PWM. This means 0-100%.
That's okay.

My problem is that if my subject wants a minimum cooling of say 5% i.e. M106 S13 then the PWM value will be 13. My fan won't start.

I looked at the commands in a console. For me, the fan starts at M106 S35. This is already 14% fan speed. But I need 5% cooling or 10% for an item. In this case, the fan will no longer run.

My question is that there is an option, command, code that can be solved as in the case of Marlin with fan PWM scaling.

Example highlighted from Marlin: PWM Fan Scaling
 *
 * Define the min / max speeds for PWM fans (as set with M106).
 *
 * With these options the M106 0-255 value range is scaled to a subset
 * to ensure that the fan has enough power to spin, or to run lower
 * current fans with higher current. (e.g. 5V / 12V fans with 12V / 24V)
 * Value 0 always turns off the fan.
 *
 * Define one or both of these to override the default 0-255 range.
 * /
#define FAN_MIN_PWM 35
#define FAN_MAX_PWM 255

Here the fan speeds are already clear. This scaling solves the problem for Marlin. So if the fan switches to 1%, it is already rotating very slowly. In this way, the cooling of the fan could be specified (brought to a real value).

Thanks in advance for your help.

By: AntoszHUN

**Comment by jakep82** [comment]
We don't use GitHub for feature requests. This is also a dup of #2165 which was discussed and ultimately not merged.
