### ISSUE TITLE
[extruder_stepper] not working with tmc2310 Drivers

### ISSUE THREAD

**Issue by sven2009** [Klipper3d/klipper#5296]
Hi,

[extruder_stepper extruder1]
extruder: extruder
...

[tmc2130 extruder1]
...

results in "Unknown stepper extruder1"

Thanks you for your work,
best regards
Sven

**Comment by Sineos** [comment]
Verify your settings according to https://www.klipper3d.org/Installation.html
As mentioned by @adawalli, GH is only used for development purposes. Please open a topic on https://klipper.discourse.group/ with your klipp.log attached.

**Comment by sven2009** [comment]
this is not a feature it is an bug(report)

**Comment by Sineos** [comment]
With almost 100% certainty it is a config or hardware issue. If you want support open a ticket on Discourse and attach your klippy.log
