### ISSUE TITLE
Corrupted Firmware on MCUs 

### ISSUE THREAD

**Issue by G54F800** [Klipper3d/klipper#5298]
After 2 months of operation my v2.4 Voron it lost connection to MCU in the middle of a print and connection could not be re-established.
All normal attempts with restart, reboot, power-out, cable checks  etc had no effect. I then found out that /dev/serial was missing indicating that neither MCUs USB host contoller had contact with the RPI. Removal of both of the MCUs SD-cards showed that these where both working properly. I then replaced the FIRMWARE.CUR with the orginal firmware.bin file and this fixed the problem, so my conclusion is the firmware got corrupted. It looks to me as if it has resemblance to #3868 Lost MCU report. The  RPI is powered by a separate original RPI power adapter so Im ruling out any power surge problem.
This is a standard V2.4 using SKR 1.4Ts in standard configuration in accordance with voron documentation. The RPI is an RPI4 8GB.
[klippy.log](https://github.com/Klipper3d/klipper/files/8116281/klippy.log)

Update : Turns out the same printjob will crash at the exact same point when tried again .....so the error can be reproduced. Dont know what that indicates .......
 
 
[octoprint.log](https://github.com/Klipper3d/klipper/files/8116345/octoprint.log)

**Comment by Sineos** [comment]
As already stated when you opened the ticket: Issues here are for development only. Please be so kind to place your support request on: https://klipper.discourse.group/
