### ISSUE TITLE
BUGREPORT: [extruder_stepper] not working with tmc2310 Drivers

### ISSUE THREAD

**Issue by sven2009** [Klipper3d/klipper#5301]
Hi,

i think extruder_stepper doesn't register itself as a real stepper

-----
[extruder_stepper my_extra_stepper1]
extruder = extruder
step_pin = PD1
dir_pin = PD0
enable_pin = !PD2
microsteps = 256
rotation_distance = 22.458

[tmc2130 my_extra_stepper]
cs_pin = PC12
sense_resistor = 0.075
run_current = 0.800
microsteps = 256
stealthchop_threshold = 0
spi_software_mosi_pin = PG15
spi_software_miso_pin = PB6
spi_software_sclk_pin = PB3

-----
results in:

Traceback (most recent call last):
  File "/home/pi/klipper/klippy/klippy.py", line 158, in _connect
    self.send_event("klippy:mcu_identify")
  File "/home/pi/klipper/klippy/klippy.py", line 248, in send_event
    return [cb(*params) for cb in self.event_handlers.get(event, [])]
  File "/home/pi/klipper/klippy/extras/tmc.py", line 355, in _handle_mcu_identify
    self.stepper = force_move.lookup_stepper(self.stepper_name)
  File "/home/pi/klipper/klippy/extras/force_move.py", line 56, in lookup_stepper
    raise self.printer.config_error("Unknown stepper %s" % (name,))
Error: Unknown stepper my_extra_stepper

Thanks you for your work,
best regards
Sven

[klippy.log](https://github.com/Klipper3d/klipper/files/8120496/klippy.log)

**Comment by Sineos** [comment]
Duplicate
