### ISSUE TITLE
[Request] Add a lump detector feature to the Hall filament width sensor

### ISSUE THREAD

**Issue by rongith** [Klipper3d/klipper#5302]
I decided to add the Hall filament width sensor to my printer. It is a great idea.
But my first concern was to try to catch lumps on the filament before it enter the extruder. Some low viscosity filaments have not so good diameters. It is not rare that there are lumps on the filament as big as 2.2mm. Those don't enter hotends (E3Dv6 is 2.0 mm inner diameter and Dragon is 1.9mm ID). If it occurs, you got a 1.5kg part ruined. I would like a feature to pause printer before cutting the lump and restart.
There is a runout filament sensor feature triggered by small diameter (1.0 default). But there is no trigger implemented for a ceiling diameter (per exemple 2.0).
Then I done a quite hugly patch for hall_filament_width_sensor.py. I use the same procedure as for the runout:
````
33a34
>         self.lump_dia=config.getfloat('lump_diameter', 2.0)
126c127
<         # Check runout
---
>         # Check anomaly (runout or lump)
128c129
<             self.diameter > self.runout_dia)
---
>             self.diameter > self.runout_dia and self.diameter < self.lump_dia)
````

The condition of the function self.runout_helper.note_filament_present is modified. For that new feature, it's name is questionable.

I'm not fluent at all with git then I didn't open a pull request.

**Comment by OSHW-Rico** [comment]
Do you have a picture of that lump on your filament?

**Comment by rongith** [comment]
There it is.
![20220308_182227](https://user-images.githubusercontent.com/7966342/157353169-9fe5b9fd-8c57-4db1-9016-ca2ab3f4a2a4.jpg)

**Comment by dewi-ny-je** [comment]
Independently from how often such a case may happen in real life (which is likely not often), I think the feature makes sense: it's consistent with the presence of a lower limit.

**Comment by rongith** [comment]
When you have the filament stuck in your hotend, you first think about heatcreep. And it may be not heat creep but a lump. Here I can tell what it is.

**Comment by Sineos** [comment]
Please be so kind to either:
* Issue a pull request so that the devs can review and decide
* Open a topic https://klipper.discourse.group/ to further discuss about this
Otherwise this topic will dangle here forever and be eventually closed.
