### ISSUE TITLE
MCU 'mcu' shutdown: ADC out of range

### ISSUE THREAD

**Issue by xsasx** [Klipper3d/klipper#5304]
BIGTREETECH SKR Mini E3 V2.0

Octoprint

Ender 3v2

 Firmware version: v0.10.0-278-g7c964e5f
[klippy.log](https://github.com/Klipper3d/klipper/files/8125669/klippy.log)

it stopps during print and said mcu failure etc after restart it shows bed temp over 700C
if i switch the termistor with the one from hotend  under octoprint the value does not change
pretty wired cause if the thermistor is broken it should change the value

Has anyone a clue for me ?

**Comment by Sineos** [comment]
As already stated when you opened the ticket: Issues here are for development only. Please be so kind to place your support request on: https://klipper.discourse.group/
