### ISSUE TITLE
GPIO pin macros not firing correctly

### ISSUE THREAD

**Issue by Zeonia** [Klipper3d/klipper#5307]
After extensive digging, I can't find any other explanation than this a bug. 

I am working on a Voron 2.4 using:
- [klippy.log](https://github.com/Klipper3d/klipper/files/8132865/klippy.log)
- Octopus board (reflashed to latest firmware)
- Raspberry Pi 4 Model B (uplated to latest klipper)
- Fluidd (latest)

Everything is working fine on the machine generally, and I am trying to build a hardware button w/macro. The button itself is a simple microswitch which shorts the GPIO pin to ground.

I have installed the pi mcu software as well as per the documentation [here](https://www.klipper3d.org/RPi_microcontroller.html#why-use-rpi-as-a-secondary-mcu)

I have also pulled the GPIO pins I am using UP:

```
raspi-gpio get 25
GPIO 25: level=1 fsel=0 func=INPUT pull=UP
```

If I create a simple macro:

```
[gcode_button BUTTON_GPIO25]
pin: !pi:gpio25
press_gcode: 
  { action_respond_info("GPIO 25 was pressed") }
```

This works exactly as I would expect. The button fires, press fires, release fires, and tapping the button over and over writes to the console correctly.

If I change the macro to anything more complicated, the button stops working correctly:

```
[gcode_button BUTTON_GPIO25]
pin = !pi:gpio25
press_gcode = 
	SET_HEATER_TEMPERATURE HEATER=extruder TARGET=220
	SET_HEATER_TEMPERATURE HEATER=heater_bed TARGET=60
	G4 P3000
	TURN_OFF_HEATERS
```

When I press the button the first time it works. If I press the button a second time once the macro completes and the heaters shut off, the button does not work, and only works again on the third press. Klipper doesn't appear to be clearing the pressed state of the button when it is busy. 

If I run ``QUERY_BUTTON button=BUTTON_GPIO25`` after pressing and releasing it the first time, the state is stuck in PRESSED.

Doesn't matter what I put in the macro, anything more than a simple console output causes the same issue. If I hold my finger down on the button until after the macro completes, everything works fine. So somewhere, the release event from the pi mcu is being lost because the printer is busy running the macro and not listening for the release.

**Comment by Sineos** [comment]
And as already stated when you opened the ticket: Issues here are for development only. Please be so kind to place your support / feature request on: https://klipper.discourse.group/
