### ISSUE TITLE
PID Tuning of heater_generic

### ISSUE THREAD

**Issue by GregoryHlavac** [Klipper3d/klipper#5310]
Utilizing SAVE_CONFIG seems to be omitting a part of the definition when committing the PID parameters if you're using the macro to submit the configuration change to file after running a tune.

```
[heater_generic chamber]
gcode_id = Chamber
heater_pin = P_RELAY
sensor_type = MAX31856
sensor_pin = None
min_temp = 0
max_temp = 250
```

Definition above, when using SAVE_CONFIG to submit the changes and restart klipper seems to cut this off and generate the below.

```
#*# <---------------------- SAVE_CONFIG ---------------------->
#*# DO NOT EDIT THIS BLOCK OR BELOW. The contents are auto-generated.
#*#
#*# [chamber]
#*# control = pid
#*# pid_kp = 44.807
#*# pid_ki = 0.732
#*# pid_kd = 685.548
```

Whereas the correct definition in the auto-saved portion should be
```
#*# <---------------------- SAVE_CONFIG ---------------------->
#*# DO NOT EDIT THIS BLOCK OR BELOW. The contents are auto-generated.
#*#
#*# [heater_generic chamber]
#*# control = pid
#*# pid_kp = 44.807
#*# pid_ki = 0.732
#*# pid_kd = 685.548
```

**Comment by Sineos** [comment]
As already stated when you opened the ticket: Issues here are for development only. Please be so kind to place your support request on: https://klipper.discourse.group/

Also please attach your klippy.log file and the steps to reproduce 

> when committing the PID parameters if you're using the macro to submit the configuration change to file after running a tune.
