### ISSUE TITLE
MCU Shutdown error - (ADC pin).

### ISSUE THREAD

**Issue by red-line-rider** [Klipper3d/klipper#5323]
MCU (ADC pin) Error.

I have an ender 3 1st Gen with Some modifications. The modifications are as follows.

Raspberry pi (Running Octoprint)
-With original Raspi 2.5 Amp Adapter
BL touch
SKR mini E3 V3
Magnetic bed with PEI coated sheet
High tension (Yellow) springs

Initially i was running Marlin on the stock melzi board. (with a bypass kit for BLtouch). Then i saw some reviews on Klipper. I shifted to Klipper with the same config. First i would like to say that the firmware is friggin awesome, the ease of use is by and large better than any else.

On the stock setup i would keep getting MCU Shutdown Errors. So i thought i would upgrade the mainboard (could only get the SKR mini E3 V3 where i live). But even Then the same error is popping up.

```
MCU 'mcu' shutdown: Not a valid ADC pin

Once the underlying issue is corrected, use the

"FIRMWARE_RESTART" command to reset the firmware, reload the

config, and restart the host software.

Printer is shutdown

Once the underlying issue is corrected, use the "RESTART"

command to reload the config and restart the host software.

Protocol error connecting to printer
```

After going through the Log file i understood the ADC part. Since then i have Checked the extruder, the bed but it looks like all the thermistors are working. I even disconnected and reconnected all the wires. But no dice.

Please guide me on how to solve this. Im not a programmer and my skills with computers are OK.

[klippy.log](https://github.com/Klipper3d/klipper/files/8184181/klippy.log)

Thx.

**Comment by Sineos** [comment]
As already stated when you opened the ticket: Issues here are for development only. Please be so kind to place your support request on: https://klipper.discourse.group/
