### ISSUE TITLE
[FR] Enhancement for cancel print like emergency stop (no wait for code)

### ISSUE THREAD

**Issue by hawkeyexp** [Klipper3d/klipper#5324]
Klipper wait's for requested cancel while he is waiting for temp (extruder or bed for example).

Cancel print should be executed more directly like a emergency stop which is not waiting for code.

**Comment by Sineos** [comment]
As already stated when you opened the ticket: Issues here are for development only. Please be so kind to place your support request on: https://klipper.discourse.group/
