### ISSUE TITLE
ADXL345 Input Shaper install - No Such File or Directory error

### ISSUE THREAD

**Issue by amv101** [Klipper3d/klipper#5327]
Installing Input Shaper with the ADXL345 on the Pi 4. I get this error when trying to run the very first script via putty....

pi@octopi:~ $ ~/klippy-env/bin/pip install -v numpy
-bash: /home/pi/klippy-env/bin/pip: No such file or directory

[klippy.log](https://github.com/Klipper3d/klipper/files/8192668/klippy.log)

Checking the directory with FTP, there is no >klippy-env directory. Anyone have any ideas?

Edit: This environment was installed using the OctoKlipper image from the Pi Imager.

Thanks in advance!

**Comment by Sineos** [comment]
Older OctoPi-Klipper images had a bug. For a solution see following post.
https://klipper.discourse.group/t/unable-to-install-numpy-no-such-file-or-directory/2203/2?u=sineos

And as already stated when you opened the ticket: Issues here are for development only. Please be so kind to place your support / feature request on: https://klipper.discourse.group/
