### ISSUE TITLE
using adxl accelerometer for skew bed correction

### ISSUE THREAD

**Issue by RomanOvchinnikov** [Klipper3d/klipper#5339]
is it possible to use adxl accelerometer to detect bed skew? or to automatic skew bed correction?
maybe it is useble to detect different belt tention on coreXY printers.

**Comment by Sineos** [comment]
And as already stated when you opened the ticket: Issues here are for development only. Please be so kind to place your support / feature request on: https://klipper.discourse.group/ and attach your klippy.log file

Similar topics are already raised: 
https://klipper.discourse.group/t/frame-squareness-using-accelerometer/1343/12
https://klipper.discourse.group/t/precise-belt-tension-for-corexy/367
https://github.com/Klipper3d/klipper/pull/5224
