### ISSUE TITLE
Support for Helical Interpolation

### ISSUE THREAD

**Issue by consolecwby** [Klipper3d/klipper#5342]
I am trying to find a control that can do helical interpolation for an experiment in making 3D printed springs and maybe eventually nuts and bolts. 
Yes I know I can do incremental G1 but I am trying to make my g code procedurally generated, without having to model then slice any given spring size.
The two standard programming formats are using arc centers
G02(or G03) X.. Y.. Z.. I.. J.. K.. F..
Or using radius
G02 (or G03) X.. Y.. Z.. R.. F..
Where the G17, G18, or G19 must be defined

**Comment by Sineos** [comment]
And as already stated when you opened the ticket: Issues here are for development only. Please be so kind to place your support / feature request on: https://klipper.discourse.group/

Following topic might provide useful insights: https://klipper.discourse.group/t/velocity-accel-limits-in-nested-loop/1944
