### ISSUE TITLE
Error 'step_pin' is not valid in section 'stepper_z1'

### ISSUE THREAD

**Issue by DevooUP96** [Klipper3d/klipper#5350]
Hello all i have a Octopus board with COREXY configuration dual Z, this my first time to setup klipper but i have this error that i cant figure out someone can help me ? thx !

[stepper_z]
step_pin: PF11
dir_pin: PG3
enable_pin: !PG5
microsteps: 16
rotation_distance: 8
endstop_pin: PG10
position_endstop: 0
position_max: 200
homing_speed: 12
#second_homing_speed: 1

[stepper_z1]
step_pin: PG4
dir_pin: PC1
enable_pin: !PA0
microsteps: 16
rotation_distance: 8
![immagine_2022-03-12_162352](https://user-images.githubusercontent.com/30018309/158024084-24fb7ae3-40ba-4c43-956d-86c30590ba2f.png)

**Comment by Sineos** [comment]
As already stated when you opened the ticket: Issues here are for development only. Please be so kind to place your support / feature request on: https://klipper.discourse.group/
Also attach your klippy.log there
