### ISSUE TITLE
Z-Axis problems on BG SKR V2

### ISSUE THREAD

**Issue by DaMusikant** [Klipper3d/klipper#5352]
Hi folks,

I set up the SKR V2 on my old RepRap Neo.
After some issues which could be fixed, the Z-Axis makes still trouble.

Here are some general Information:
All drivers are TMC2225, I declared them as TMC2208 due to the missing configs for them.
X, Y and the Extruder are working fine.
The Z-Axis is mounted to an spindle with 1mm of pitch.

I already got the Z-Axis to work. But with an increadibly loud noise. But mostly it's just horrofying noise and nothings move.
I changed everything already with the working axis and the placement on PCB itself with no sucksess.

So there must be an issue on the config. But I can't figure out what. Changing the rotating distance makes no difference, also microsteps, run_current or stealthchop

Can you help me please?
Thank you :)

[octoprint-systeminfo-20220313173624.zip](https://github.com/Klipper3d/klipper/files/8240278/octoprint-systeminfo-20220313173624.zip)

**Comment by Sineos** [comment]
As already stated when you opened the ticket: Issues here are for development only. Please be so kind to place your support / feature request on: https://klipper.discourse.group/
Also attach your `klippy.log` there
