### ISSUE TITLE
Support for more than 2 carriages on different gantries

### ISSUE THREAD

**Issue by kazolar** [Klipper3d/klipper#5353]
I built a printer a few years back which has 2 y gantries and 2 x carriages per gantry. It is currently running a modified rrf2 firmware, which is outdated, and my most recent quad duplication prints have shown the board struggles with more complex geometry. I am trying to figure out if moving to klipper is an option (with a couple of octopus or boards). I can see there is not really a way to define tools as which x and y axis they should be using. It's only x or y remapping, but not both. I don't much care for mirror modes, but duplication -- with 2 3, or 4 tools have been useful in the past (shields printing for ppe). I know this is a rather niche configuration, the cost to move to rrf3 is pretty high, also accelerometer/input shaping is more intuitive on klipper. My python knowledge is just good enough to see that the changes to idex module aren't super straight forward to expand past 2 carriages, especially with 2 gantries. Some more info -- my y gantries have 2 steppers each, which currently are able to home independently through logic gates, which I would like to ditch in favor of handling gantry de-skewing in firmware. Total stepper count is 16, with 4 independent z steppers, 2 x steppers per gantry, and 2 y steppers per gantry.  My gantry circuit is done the way it is due a absolute hard limit of 14 steppers on the duet 2 platform. 
I have not seen anyone ask about this as something that klipper could support, and seeing how quickly new features are added, I figured to ask before dropping a bunch of cash on rrf3 hardware.

**Comment by Sineos** [comment]
As already stated when you opened the ticket: Issues here are for development only. Please be so kind to place your support / feature request on: https://klipper.discourse.group/
