### ISSUE TITLE
MCU 'rpi' error during config: Unable to open spi device

### ISSUE THREAD

**Issue by danilov7624** [Klipper3d/klipper#5354]
After updating Klipper to the latest version, Klipper does not start until the ADXL345 connection section exists in the configuration file. Before that, there were no problems.
[klippy.log](https://github.com/Klipper3d/klipper/files/8241054/klippy.log)

**Comment by Sineos** [comment]
As already stated when you opened the ticket: Issues here are for development only. Please be so kind to place your support / feature request on: https://klipper.discourse.group/
