### ISSUE TITLE
BLTouch failed to verify sensor state after loop

### ISSUE THREAD

**Issue by MajkNest** [Klipper3d/klipper#5355]
Hi, when I am looping a g-code after one completed print I get `BLTouch failed to verify sensor state`
I checked the wiring, switch to new BLtouch,  

If I print the same G-code separately, everything works well.

I think is a bug because of the previous version of Klipper loop works well.

Any advice what else can I try?

[klippy.log](https://github.com/Klipper3d/klipper/files/8244844/klippy.log)

**Comment by Sineos** [comment]
As already stated when you opened the ticket: Issues here are for development only. Please be so kind to place your support / feature request on: https://klipper.discourse.group/
