### ISSUE TITLE
Unable to set tmc2209 stepper current using uart

### ISSUE THREAD

**Issue by Quickuser75** [Klipper3d/klipper#5356]
HI, I am having problem with klipper with tmc2209 drivers I have 4 drives on my voron setup and I am unable to change the current down using the printer.cfg
I have the standard setup that is listed on the fluid voron file, but no mater what I put in the run_current nothing changes the steppers are running at maximum current I am using the latest build

**Comment by Quickuser75** [comment]
Oh in adding, I have a BTT octopus pro

**Comment by Sineos** [comment]
As already stated when you opened the ticket: Issues here are for development only. Please be so kind to place your support / feature request on: https://klipper.discourse.group/
Also attach your `klippy.log` there
