### ISSUE TITLE
Error GSTAT:      00000002 drv_err

### ISSUE THREAD

**Issue by ManuelPeiro** [Klipper3d/klipper#5357]
Hi,

I am finishing assembly a corexy printer, with Octopus pro 429 and tmc 2209.... And when o order move the motors. Any of them, I hear how the motor star turning.. And receive this error.

i receive this error when try homing...

TMC 'stepper_x' reports error: GSTAT:      00000002 drv_err=1(ErrorShutdown!)

Some idea can be?  Googling I cant find these error code

**Comment by Sineos** [comment]
As already stated when you opened the ticket: Issues here are for development only. Please be so kind to place your support / feature request on: https://klipper.discourse.group/
Also attach your `klippy.log` there

**Comment by ManuelPeiro** [comment]
Thx
