### ISSUE TITLE
Force sensor settings

### ISSUE THREAD

**Issue by MikiFX91** [Klipper3d/klipper#5358]
Hi everyone, I'm trying to use a miniature force sensor as a Z probe.

The sensor works very similar to a microswitch, it is positioned above the hotend and has the same offset as the nozzle. It needs no power and closes the circuit between GRN and SIG when the nozzle touches the print bed.

I've tried many ways to configure stepper_z but it always gives me the same error:
`Option 'position_endstop' is not valid in section 'stepper_z'`

and this is the last configuration I tried:
```
[stepper_z]
step_pin: PB8
dir_pin: PB7
enable_pin: !PB9
microsteps: 16
rotation_distance: 8
endstop_pin: probe:z_virtual_endstop
position_max: 300
position_min: -0.2
homing_speed: 5
second_homing_speed: 3
full_steps_per_rotation: 400
[tmc2209 stepper_z]
uart_pin: PB5
run_current: 0.80
sense_resistor: 0.110
stealthchop_threshold: 999999

[probe]
pin: ^PE0
z_offset: 0
x_offset: 0
y_offset: 0

[bed_mesh]
speed: 200
horizontal_move_z: 10
mesh_min: 0, 0
mesh_max: 360, 360
probe_count: 5, 5
mesh_pps: 2, 2
algorithm: bicubic
bicubic_tension: 0.2

[safe_z_home]
home_xy_position: 180, 180
speed: 200
z_hop: 10
z_hop_speed: 30
```
The printer does not have any kind of physical endstop. 
What am I doing wrong?

**Comment by Sineos** [comment]
As already stated when you opened the ticket: Issues here are for development only. Please be so kind to place your support / feature request on: https://klipper.discourse.group/
Also attach your `klippy.log` there
