### ISSUE TITLE
Internal error on command:"G2"

### ISSUE THREAD

**Issue by Talha909** [Klipper3d/klipper#5363]
[klippy.log](https://github.com/Klipper3d/klipper/files/8308805/klippy.log)
I have updated all the things. The machine total updated today. But when i gave the command of print. After G29 its complete the bed mesh and print the first line and gave me the fallowing error message. 

Internal error on command:"G2"

The error random. Sometime machine print and some time it gave the error. Its like 10 out 15 prints commands

**Comment by Sineos** [comment]
As already stated when you opened the ticket: Issues here are for development only. Please be so kind to place your support / feature request on: https://klipper.discourse.group/
Also attach your `klippy.log` there
