### ISSUE TITLE
Amount of Z-axis movement is unstable

### ISSUE THREAD

**Issue by yhira1023** [Klipper3d/klipper#5368]
When I printed in spiral mode, Although the flow rate is constant, the movement amount of the Z axis is uneven. 
As a result, the width of the print changes periodically. 

![IMG_2752](https://user-images.githubusercontent.com/70953099/159251816-1cfba972-6df0-4966-8760-c659fb2a841f.jpeg)

the gcode file is made by Cura.
This issue does not occur with marlin on same printer same gcode file.
[TXXPRO_test_c_spiral2.ZIP](https://github.com/Klipper3d/klipper/files/8315059/TXXPRO_test_c_spiral2.ZIP)

As strange point ,Looking at mainsail on printing.
Flow : stable
Z-position : increase unstably

Are there any factors that change the amount of increase in the Z axis? 
or Is it truncated by some calculation? 

My environments
Tronxy X5SA Pro + Orbiter v1.5 
Cura v4.13.1
Klipper /mainsail up to date 
[printer.zip](https://github.com/Klipper3d/klipper/files/8315063/printer.zip)

**Comment by Sineos** [comment]
As already stated when you opened the ticket: Issues here are for development only. Please be so kind to place your support / feature request on: https://klipper.discourse.group/
Also attach your `klippy.log` there

**Comment by yhira1023** [comment]
Okay ,I try support request.
Thank you.
