### ISSUE TITLE
Delayed GCode Error 

### ISSUE THREAD

**Issue by Imlbrown** [Klipper3d/klipper#5373]
I have 4 delayed gcode macros, 3 which check for heater fan (hotend and 2 enclosure heater fans) blocks and I just added a 4th to control bed heater fans for enclosure temp.

The delayed gcode is failing with the error.

Script running error
Traceback (most recent call last):
  File "/home/pi/klipper/klippy/extras/delayed_gcode.py", line 34, in _gcode_timer_event
    self.gcode.run_script(self.timer_gcode.render())
  File "/home/pi/klipper/klippy/gcode.py", line 216, in run_script
    self._process_commands(script.split('\n'), need_ack=False)
  File "/home/pi/klipper/klippy/gcode.py", line 198, in _process_commands
    handler(gcmd)
  File "/home/pi/klipper/klippy/gcode.py", line 272, in cmd_default
    raise gcmd.error(self.printer.get_state_message()[0])
CommandError: Lost communication with MCU 'mcu'
Once the underlying issue is corrected, use the
"FIRMWARE_RESTART" command to reset the firmware, reload the
config, and restart the host software.
Printer is shutdown

If I start the printer and set the extruder, bed and enclosure temps going and let the printer sit idle it will run for hours with no issue. When I start printing, usually within about 10 minutes, the error will occur and one of the fan check macros will start reading 0 for fan RPM and pause the print, but fluid still shows the fans at speed and fluctuating slightly. I was on the latest v0.10.0-320 and moved backed to straight up v0.10.0, but the issue occurs on both versions of firmware. And I did re-flash the spider controller board and linux process when making the firmware change. I have two camera running, so I shutdown webcamd in case it was an overloading issue, but error still occurs.

I am running klipper on a Pi4 and Spider v2.2 controller board using Fluidd.

[klippy.log](https://github.com/Klipper3d/klipper/files/8336165/klippy.log)

**Comment by Sineos** [comment]
As already stated when you opened the ticket: Issues here are for development only. Please be so kind to place your support / feature request on: https://klipper.discourse.group/
Also attach your `klippy.log` there.
