### ISSUE TITLE
STM32H743VI does not work on USB

### ISSUE THREAD

**Issue by fghlw** [Klipper3d/klipper#5381]
I made a board base on STM32H743VI (8MHz crystal, no bootloader),  after burn in, both on PA11&12 / PB14&15 no access. If currently only support "SE BX" board? 
I made a test program that my board work well, all port are ok.

**Comment by Sineos** [comment]
As already stated when you opened the ticket: Issues here are for development only. Please be so kind to place your support / feature request on: https://klipper.discourse.group/
