### ISSUE TITLE
Default idle_timeout is safety hazard due to M84

### ISSUE THREAD

**Issue by richfelker** [Klipper3d/klipper#5384]
The default `idle_timeout` action is `TURN_OFF_HEATERS` and `M84`. On a machine where the Z position does not hold without power to the steppers, and where the toolhead moves up in Z rather than the bed moving down, this will drop the still-hot nozzle onto whatever is below it, melting a printed part still present there, damaging the bed surface, or similar. The default should probably only turn off the heaters, or at least wait for heaters to cool below 50˚C or so before turning off the steppers.

I don't really care about this for myself; I'd changed the default action a long time ago. But I just spoke to a (newer?) user who hit the `M84` on timeout during pause and was frustrated by it, and realized it was also a safety hazard.

The same probably applies to emergency shutdown, but I don't know a good solution in that case because it may be important to have the steppers unpowered for different conflicting safety reasons.

**Comment by Sineos** [comment]
Please be so kind to address such topics on https://klipper.discourse.group. Thank you.
