### ISSUE TITLE
Small layer shifts on model geometry changes

### ISSUE THREAD

**Issue by jbo18** [Klipper3d/klipper#5393]
Having a really weird issue on my printer. I get very small layer shifts, and only at cross-sectional changes in the model. I asked for help on the Discord and managed to stump the people trying to help me so maybe I can get some help here.

In this picture, you can see two layer shifts, roughly corresponding to the beginning and ending of a chamfer on a vertical hole in the model around the midsection of the model, and some issues where the solid skin on the bottoms of the internal holes start.

<img src=https://i.imgur.com/dpuE2EB.jpg>

And here you can see a simple extrusion calibration square, 3 solid layers on the bottom. As soon as it gets to the end of the last solid layer, bam - shifts a fraction of a millimeter and prints perfectly from there on. I have observed it 3 or 4 times on this model alone. there are no noises indicating missed steps, I watched the first 8 layers on the last one.

<img src=https://i.imgur.com/4TveNbt.jpg>

I've looked into all the usual suspects for layer shifting - belts are tight, enough (but not too much) motor current, Z-axis moves smoothly (shouldn't have mattered for the x-axis anyway but whatever), replaced X-axis stepper driver, tried disabling stealthchop, even swapped from USB to serial communication. Hotend and bed temps are stable while printing. All software/firmware up to date. Does it with every slicer I've used. Never had issues running Marlin with the same setup. I can send STL and gcode files if it would help - this is driving me almost literally insane. I have seen this reported numerous times and every time the issues get closed without a resolution for various reasons.

Printer is a modified Ender 3 Pro. Hardware:
- Original heated plate with glass on top
- SKR 1.3
- Raspberry Pi 3B+ running Fluidd
- TMC2208 in UART mode on all steppers
- BLTouch 3.1
- 2x 5015 fans on nozzle
- 1x 5015 fan on stepper drivers
- 1x 4020 fan for hotend
- Micro-Swiss all-metal hotend
- Original Creality motors on Y, Z, and E
- FSYETC motor on X

Logs:

[moonraker.log](https://github.com/Klipper3d/klipper/files/8401426/moonraker.log)
[klippy.log](https://github.com/Klipper3d/klipper/files/8401427/klippy.log)

**Comment by jakep82** [comment]
https://www.klipper3d.org/Contact.html#help-it-doesnt-work
