### ISSUE TITLE
Mainsail-Klipper  configuration problem

### ISSUE THREAD

**Issue by soumyajit02** [Klipper3d/klipper#5394]
I tried to use my raspberry pi model 3b+ as a secondary Mcu to control some cooling fan and lights beside the Arduino Mega 2560 which is the main control board for the printer axis movement related stuff. 
Followed every instruction described in rpi as a secondary mcu at: https://www.klipper3d.org/RPi_microcontroller.html
changed the printer.cfg according to it as described by the reference document but keeps getting the error...
```
MCU 'rpi' shutdown: Unable to open out GPIO chip line
Once the underlying issue is corrected, use the
"FIRMWARE_RESTART" command to reset the firmware, reload the
config, and restart the host software.
Printer is shutdown
```
**This is my klippy.log:**
[klippy.log](https://github.com/Klipper3d/klipper/files/8403251/klippy.log)

**My printer.cfg:**
[printer.cfg.txt](https://github.com/Klipper3d/klipper/files/8403283/printer.cfg.txt)

**when I am not including those fans and relays in my code everything is working fine that should verify that klipper is working fine and it's installation is proper but defining the pins as: 
pin: rpi:gpiochip0/gpio any pin number             
is giving me that error.
I am defining my secondary mcu (Raspberry pi) as 'rpi'. 
I would also like to mention that I was using fluid with klipper before and at there  everything was working as they should, then I tried to remote access my printer outside my home network and neither octopi or mainsail worked for me.** 

**This is what my gpioinfo shows also I enabled SPI so that I could control the pins**

pi@mainsail:~ $ gpioinfo
gpiochip0 - 54 lines:
        line   0:      unnamed       unused   input  active-high
        line   1:      unnamed       unused   input  active-high
        line   2:      unnamed       unused   input  active-high
        line   3:      unnamed       unused   input  active-high
        line   4:      unnamed       unused   input  active-high
        line   5:      unnamed       unused   input  active-high
        line   6:      unnamed       unused   input  active-high
        line   7:      unnamed   "spi0 CS1"  output   active-low [used]
        line   8:      unnamed   "spi0 CS0"  output   active-low [used]
        line   9:      unnamed       unused   input  active-high
        line  10:      unnamed       unused   input  active-high
        line  11:      unnamed       unused   input  active-high
        line  12:      unnamed       unused   input  active-high
        line  13:      unnamed       unused   input  active-high
        line  14:      unnamed       unused   input  active-high
        line  15:      unnamed       unused   input  active-high
        line  16:      unnamed       unused   input  active-high
        line  17:      unnamed       unused   input  active-high
        line  18:      unnamed       unused   input  active-high
        line  19:      unnamed       unused   input  active-high
        line  20:      unnamed       unused   input  active-high
        line  21:      unnamed       unused   input  active-high
        line  22:      unnamed       unused   input  active-high
        line  23:      unnamed       unused   input  active-high
        line  24:      unnamed       unused   input  active-high
        line  25:      unnamed       unused   input  active-high
        line  26:      unnamed       unused   input  active-high
        line  27:      unnamed       unused   input  active-high
        line  28:      unnamed       unused   input  active-high
        line  29:      unnamed       unused   input  active-high
        line  30:      unnamed       unused   input  active-high
        line  31:      unnamed       unused   input  active-high
        line  32:      unnamed       unused   input  active-high
        line  33:      unnamed       unused   input  active-high
        line  34:      unnamed       unused   input  active-high
        line  35:      unnamed       unused   input  active-high
        line  36:      unnamed       unused   input  active-high
        line  37:      unnamed       unused   input  active-high
        line  38:      unnamed       unused   input  active-high
        line  39:      unnamed       unused   input  active-high
        line  40:      unnamed       unused   input  active-high
        line  41:      unnamed       unused   input  active-high
        line  42:      unnamed       unused   input  active-high
        line  43:      unnamed       unused   input  active-high
        line  44:      unnamed       unused   input  active-high
        line  45:      unnamed       unused   input  active-high
        line  46:      unnamed       unused   input  active-high
        line  47:      unnamed       unused  output  active-high
        line  48:      unnamed       unused   input  active-high
        line  49:      unnamed       unused   input  active-high
        line  50:      unnamed       unused   input  active-high
        line  51:      unnamed       unused   input  active-high
        line  52:      unnamed       unused   input  active-high
        line  53:      unnamed       unused   input  active-high
gpiochip1 - 2 lines:
        line   0:      unnamed       "led0"  output  active-high [used]
        line   1:      unnamed       unused   input  active-high
gpiochip2 - 8 lines:
        line   0:      unnamed       unused  output  active-high
        line   1:      unnamed       unused  output  active-high
        line   2:      unnamed       unused  output  active-high
        line   3:      unnamed       unused  output  active-high
        line   4:      unnamed       unused   input  active-high
        line   5:      unnamed       unused  output  active-high
        line   6:      unnamed       unused  output  active-high
        line   7:      unnamed       "led1"   input  active-high [used]

**I need help....
Someone pls help me out its been 2 days, I can't figure it on my own...**

**Comment by Sineos** [comment]
As already stated when you opened the ticket: Issues here are for development only. Please be so kind to place your support / feature request on: https://klipper.discourse.group/

**Comment by soumyajit02** [comment]
> As already stated when you opened the ticket: Issues here are for development only. Please be so kind to place your support / feature request on: https://klipper.discourse.group/

thanks but tell me where to place this specific issue...
