### ISSUE TITLE
Feature Request - Event on MCU communication / other failure

### ISSUE THREAD

**Issue by kickit2** [Klipper3d/klipper#5395]
I recently had an MCU lockup caused by a failed cooling fan which caused extruder and bed temp to go full power without restraint, reaching each of their max.  This not only caused damage to the machine, but could have been a fire.  It'd be desirable to have an event / trigger fire on MCU communication loss or other MCU error that could be used with a macro or otherwise - in my case to trigger a relay and cut power to the printer.  As far as I can tell, no such event / trigger exists at this time.

**Comment by Sineos** [comment]
#3666
