### ISSUE TITLE
SCREWS_TILT_CALCULATE - Option to use degrees for improved accuracy

### ISSUE THREAD

**Issue by ewb-git** [Klipper3d/klipper#5397]
Hello,

To be brief, when chasing incredibly low variance in bed flatness, using degrees over minutes allows for more accuracy, and more fine adjustment.

For example, 1 minute of error = 1.666% error (100/60=1.666). When using degrees, 1 degree of error = 0.277% (100/300=0.277). I forget the term for this, so pardon me writing out the simple math to explain.

I think this is a very easy change that can make the bed leveling procedure more accurate, for those who want it. There could be an option added under [screws_tilt_adjust] to:
`display: minutes` or `display: degrees` or `display: minutes, degrees` 

Thank you very much for the consideration!

P.S.
An option to raise the Z axis a specified amount after probing would be useful. Many Prusa users have a magnetic sheet covering the screws, so have to manually raise Z to remove the sheet since `SCREWS_TILT_CALCULATE` parks at the specified horizontal_move_z value.

**Comment by Sineos** [comment]
As already stated when you opened the ticket: Issues here are for development only. Please be so kind to place your support / feature request on: https://klipper.discourse.group/
