### ISSUE TITLE
"MCU 'mcu' shutdown: Timer too close"  in the middle of a print

### ISSUE THREAD

**Issue by p3c1** [Klipper3d/klipper#5401]
Hello,
in the middle of a print klipper just stopped with the error  "MCU 'mcu' shutdown: Timer too close".
I am not able to understand what can cause this. 

Here is the klippy.log if someone can help me understand the issue.

Thanks

[klippy.log](https://github.com/Klipper3d/klipper/files/8457077/klippy.log)

**Comment by Sineos** [comment]
As already stated when you opened the ticket: Issues here are for development only. Please be so kind to place your support / feature request on: https://klipper.discourse.group/
