### ISSUE TITLE
MCU 'mcu' shutdown: Rescheduled timer in the past.

### ISSUE THREAD

**Issue by gnutison** [Klipper3d/klipper#5403]
Hi, 
It has never happened before, it suddenly stops. I printed same parts with the same settings before without any issues. After resetting the firmware, i can print the same thing again without any issues. Somehow Klippylog is empty, so don't know where to look at.
SKR MINI E3v3, Pi Zero 2W.
[printercfg.txt](https://github.com/Klipper3d/klipper/files/8459377/printercfg.txt)
![FhVG2b0](https://user-images.githubusercontent.com/94188985/162628254-a1bff712-a69e-4bc6-886b-654fba18c497.png)

**Comment by th33xitus** [comment]
You failed/ignored to follow the directions you were pointed at while opening this (invalid) issue.
https://www.klipper3d.org/Contact.html
