### ISSUE TITLE
Anycubic vyper LCD screen config

### ISSUE THREAD

**Issue by JackyHe398** [Klipper3d/klipper#5407]
HI i just start to play klipper and i don't really know how i can config the pins. But i try my best to find the information i need.

I am using a anycubic vyper with mainsail os. I cannot look for anyone who config the LCD screen of vyper so i decided to figure it out. Here is what i get:
The pin is 
- +5V RESET TX3 RX3 GND

and procide something like this
- 29 PB10 LCD_TX (Usart 2)
- 30 PB11 LCD_RX
 
Are those information enough for me to config the machine? if yes, can anybody give me a example file so that i can copy those pins to the file(my knowledge about this is like white sheet, nothing in my mind TT).  If no, what information I am missing?

**Comment by Sineos** [comment]
As already stated when you opened the ticket: Issues here are for development only. Please be so kind to place your support / feature request on: https://klipper.discourse.group/
