### ISSUE TITLE
Internal Error on Command BED_SCREWS_ADJUST

### ISSUE THREAD

**Issue by Julfried** [Klipper3d/klipper#5416]
I recently added the BED_SCREWS_ADJUST section to my printer config. I worked for a few calinbrations but now i am getting an Internal Error on this command. I do not know what happend, so maybe someone could help me out with this issue.

Appreciate your awesome work. Thank you.
[klippy.log](https://github.com/Klipper3d/klipper/files/8483806/klippy.log)

**Comment by Sineos** [comment]
As already stated when you opened the ticket: Issues here are for development only. Please be so kind to place your support / feature request on: https://klipper.discourse.group/

**Comment by Julfried** [comment]
Im am so sorry. I am closing this.
