### ISSUE TITLE
Internal error during connect: MCU_stepper instance has no attribute 'steppers'

### ISSUE THREAD

**Issue by PatrickYCY** [Klipper3d/klipper#5418]
When include ercf's config have error as the tittle,
Attached the Klippy log for reference
Machine: Voron 2.4 350, MCU 1 BTT OCTOPUS V1.1, MCU 2 BTT Mini SKR E3 V2.0
[klippy (2).log](https://github.com/Klipper3d/klipper/files/8490586/klippy.2.log)

**Comment by Sineos** [comment]
As already stated when you opened the ticket: Issues here are for development only. Please be so kind to place your support / feature request on: [klipper.discourse.group](https://klipper.discourse.group/)
