### ISSUE TITLE
STM32F103 delivers wrong SPI speed

### ISSUE THREAD

**Issue by cooked** [Klipper3d/klipper#5424]
A control board based on the STM32F103 delivers the wrong SPI speed. The speed looks like to be 1/2 of the configured one 

When default SPI parameters are used, for example to communicate with a TMC, the speed should be 4M, while 2M (lin picture, ittle deviation is due to the signal/scope framing)  is measured on the clock line. 
The issue might be related to the fact that the default Klipper SPI, SPI2, is on APB1 where the maximum running frequency is 36MHz and not 72MHz  

![image](https://user-images.githubusercontent.com/1381353/163672317-bda15779-fddf-4fb1-8eea-fd0ac73e3211.png)
![image](https://user-images.githubusercontent.com/1381353/163672418-a815b8e3-332b-425c-a68d-6fb60d88c7b1.png)
![image](https://user-images.githubusercontent.com/1381353/163672472-33c56082-ef34-427a-8786-4ebd12f6d568.png)

**Comment by KevinOConnor** [comment]
As far as I know, the code does what it is intended to do.  They key code is in src/stm32/spi.c:
```c
    // Calculate CR1 register
    uint32_t pclk = get_pclock_frequency((uint32_t)spi);
    uint32_t div = 0;
    while ((pclk >> (div + 1)) > rate && div < 7)
        div++;
    uint32_t cr1 = ((mode << SPI_CR1_CPHA_Pos) | (div << SPI_CR1_BR_Pos)
                    | SPI_CR1_SPE | SPI_CR1_MSTR | SPI_CR1_SSM | SPI_CR1_SSI);
```

The `get_pclock_frequency()` function returns 36000000 on stm32f103 (see stm32f1.c for details).  That loop will result in `div=3` which is a division of16 and 36000000 / 16 == 2250000 frequency.  That's the highest frequency that the spi clock can be programmed to without exceeding the requested 4Mhz clock.

-Kevin

**Comment by cooked** [comment]
Thanks for clarifying. The reference does not describe that and is somewhat vague in regard 
![image](https://user-images.githubusercontent.com/1381353/163733679-6f0c49a2-f74e-4b18-a0f4-22aa16f102e1.png)

**Comment by Sineos** [comment]
@cooked If the topic is concluded, please be so kind to close the issue.
