### ISSUE TITLE
Where's my serial port for ender 3 v 2 .. 4.2.2

### ISSUE THREAD

**Issue by ahmedbadran732000** [Klipper3d/klipper#5425]
<
I'm facing 
"~/klipper $ ls /dev/serial/by-id/*"
it respond with 
ls: cannot access '/dev/serial/by-id/*': No such file or directory
plz help

I used RASPI imager + RASPI 4 4gb>

**Comment by Sineos** [comment]
As already stated when you opened the ticket: Issues here are for development only. Please be so kind to place your support / feature request on: [Klipper Discourse](https://klipper.discourse.group/)
