### ISSUE TITLE
Skr mini v3 mcu error 

### ISSUE THREAD

**Issue by Andriuzzs** [Klipper3d/klipper#5429]
Hi all i have this error 
MCU 'mcu' shutdown: Rescheduled timer in the past
This generally occurs when the micro-controller has been
requested to step at a rate higher than it is capable of
obtaining.
Once the underlying issue is corrected, use the
"FIRMWARE_RESTART" command to reset the firmware, reload the
config, and restart the host software.
Printer is shutdown

I tryed to slower myprint and some time this error apear some time not using the same gcode. What main reason can be? I use skr mini v3 direct extruder dual z  printer ender 3. Presure advance is set.

- [ ] 
[klippy.log.txt](https://github.com/Klipper3d/klipper/files/8503952/klippy.log.txt)

[printer.cfg.txt](https://github.com/Klipper3d/klipper/files/8503845/printer.cfg.txt)

**Comment by Sineos** [comment]
https://klipper.discourse.group/t/ender-3-skr-mini-v3-mcu-error/2630
