### ISSUE TITLE
Thermal runaway on Ender 3

### ISSUE THREAD

**Issue by jdanders** [Klipper3d/klipper#5430]
Edit: I have now taken the time to understand the logs, and it's pretty clear the Pi got disconnected from the MCU, with the last stat being:
```
Stats 9908.4: gcodein=2318820 mcu: mcu_awake=0.086 mcu_task_avg=0.000248 mcu_task_stddev=0.000241 bytes_write=10671832 bytes_read=2228163 bytes_retransmit=703 bytes_invalid=4394 send_seq=229431 receive_seq=229426 retransmit_seq=229431 srtt=0.003 rttvar=0.000 rto=3.200 ready_bytes=614 stalled_bytes=5582 freq=16000046 heater_bed: target=100 temp=99.9 pwm=1.000 sysload=0.36 cputime=333.872 memavail=1749128 print_time=9901.681 buffer_time=2.395 print_stall=0 extruder: target=245 temp=244.7 pwm=0.709
```
Since bed pwm was a `1` and extruder pwm was `0.709` things got toasty. I think the issue I want to raise is this:
**If the mcu gets disconnected from the Pi, shouldn't the mcu turn off the heaters?**

Second question:
**Is there some way to figure out why the mcu got disconnected so I can prevent it in the future?**

TMI below:

I had a thermal runaway event on my Ender 3 yesterday, and I can't figure out what happened. I was 2.75hrs into a 34 hour print and as far as I can tell, the z axis was lowered by several mm (enough to embed the nozzle in the print), Klipper fw stopped entirely, but both hotend and bed heaters were left on full power. 

I noticed things had stopped and did a firmware reset. When it came back online, the hotend was 438C and the bed was 130C. At that point Klipper wouldn't let me control anything because the sensors were outside safe range. When they cooled off enough I pulled the nozzle out of the print and pulled the klipper log (attached).

I've looked at the log, but it looks like things just stopped (search for "Stats 11360.5"). As far as I can tell, it was about 24 minutes between things stopping and my noticing it was broken. (see edit below for Octoprint history)

**Can anyone give me a hint as to how Klipper ended up dying with the heaters turned on?** Sorry if there's not enough log data now, it was a bad time to diagnose and I shut everything off because I had to leave.

[thermal-runaway-ender.log](https://github.com/Klipper3d/klipper/files/8506413/thermal-runaway-ender.log)

**Edit:** 
Turns out shutting of the power to the system was okay: my browser still had the temperature history up.

![image](https://user-images.githubusercontent.com/15146675/163835383-89eb5d5c-6f62-4600-aa52-2326a82cf7a3.png)
T-5 minutes is the point when I restarted Klipper FW, and then shortly thereafter I set the target temp back to 245/100 so I could remove the nozzle from the print.

I don't know what's happening at T-30 through T-24 minutes. First the actual temperatures drop to 0 (because the firmware died?), then some time later it looks like the target temps toggle back and forth between 245/100 and 0/0. **What would cause the targets to oscillate like that?**

The OctoKlipper logs are also still in my browser. The first time stamp in the attached log after the incident is 18:11. On the gui, leading up to that I have several of these errors:
```
18:10:19 Klipper: Standby
18:10:19 Klipper: Standby
18:10:22 Klipper: Standby
18:10:22 Klipper: Standby
18:10:22 Lost communication with MCU 'mcu'
18:10:22 Lost communication with MCU 'mcu'
Once the underlying issue is corrected, use the
"FIRMWARE_RESTART" command to reset the firmware, reload the
config, and restart the host software.
Printer is shutdown
```

This is probably me trying to control the printer before issuing the firmware restart. Does "Lost communication with the MCU" mean that the firmware is dead at that point?

The firmware restart in the Octoklipper logs shows the ADC range error:
```
18:11:17 Klipper state: Disconnect
18:11:20 Klipper state: Ready
18:11:22 Klipper state: Shutdown
18:11:27 MCU 'mcu' shutdown: ADC out of range
```

**Edit 2:**
After looking more closely at the log, the first issue actually shows up after Stats 9907.4.
```
Timeout with MCU 'mcu' (eventtime=9908.386273)
Transition to shutdown state: Lost communication with MCU 'mcu'
```
Any hints why that happened?

**Comment by Sineos** [comment]
As already stated when you opened the ticket: Issues here are for development only. Please be so kind to place your support / feature request on: [Klipper Discourse](https://klipper.discourse.group/)

Also this is already addressed here: https://github.com/Klipper3d/klipper/issues/3666
