### ISSUE TITLE
Z offset 

### ISSUE THREAD

**Issue by Lee-Martin-KOS** [Klipper3d/klipper#5432]
Hi everyone hope all is doing well,

I have a Dbot corexy trying to go over to klipper from marlin 2.0 but having issues with my z offset it is 10mm above my print bed at z0 with calibrated z offset in klipper.

I have a virtual z endstop with a servo deploying mechanical endstop to probe the bed i currently have 2 z stepper motors with 1 start lead screws.

i would like to use what i currently have if i would go to bl touch dont think the problem will go away, i a way i think my problem is with my z steppers and 1 start lead screws and klipper is probably build on the 4 start common lead screws.

id there a work around for me to do i really don't want to go back to marlin because of a small issue like this.

oh yes another issue at the bottom of my config file is the save configs that klipper writes its for some reason not working, i can calibrate everything my z offset even pid tuning they not being read by klipper.

please let me know if you need anything your help would be appreciated.

Regards
Martin

**Comment by Sineos** [comment]
As already stated when you opened the ticket: Issues here are for development only. Please be so kind to place your support / feature request on: [Klipper Discourse](https://klipper.discourse.group/)
Also attach your `klippy.log` file there.
