### ISSUE TITLE
How to add asm file into build system?

### ISSUE THREAD

**Issue by kaidegit** [Klipper3d/klipper#5434]
Hi,

I want to port klipper to a new MCU. I noticed that the startup file are wrote in C files in klipper. However, the startup file offered by manufacturer of the MCU is wrote in an ASM file. I want some help to add the file into build system.

Thanks

**Comment by Sineos** [comment]
This is a question that is best placed in the "Developers" section of https://klipper.discourse.group

Generally your question is also rather unspecific. If you search the sources here you will find quite a few places where asm is directly included: https://github.com/Klipper3d/klipper/search?q=asm

**Comment by kaidegit** [comment]
For example, Most of MCU’s library like STM32 Cube Library offered by ST always start the MCU from startup_stm32xxxx.S file. However, klipper firmware start the MCU from a C file. So the build system of klipper seem not design to compile .S file. 

What issue  or PR can be searched are all about inline assembly, aka write some asm in C file, not in a hole ASM file.

**Comment by Sineos** [comment]
https://klipper.discourse.group/t/how-to-add-asm-file-into-build-system/2653
