### ISSUE TITLE
continuous layer shifts in only one direction

### ISSUE THREAD

**Issue by k-laus344** [Klipper3d/klipper#5435]
Hi I built a custom 3D printer (900x1200x650) and i wanted to use klipper. Everything works fine except that i have a continuous layershift in positive y-axis direction. I eliminated all hardware problems that could cause this behaviour. I also changed the drivers, to TMC2209 v1.2 cause i read that the driver also can be a problem due to pulse width problems. What can be the reason for this? Please help! 
[printer.cfg.zip](https://github.com/Klipper3d/klipper/files/8521905/printer.cfg.zip)
[klippy (1).log](https://github.com/Klipper3d/klipper/files/8521909/klippy.1.log)

**Comment by k-laus344** [comment]
![WhatsApp Image 2022-04-20 at 15 00 36](https://user-images.githubusercontent.com/104078720/164243073-1a2ae472-fd6f-44da-a7d0-23a87e71479c.jpeg)

**Comment by Sineos** [comment]
https://klipper.discourse.group/t/continuous-layershifting-in-positive-y-axis-direction/2650
