### ISSUE TITLE
Reset RP2040 on Jetson Nano via USB

### ISSUE THREAD

**Issue by Wasserhahn123** [Klipper3d/klipper#5438]
Hey Guys,
i'm running Klipper on a Jetson Nano 4GB. As external Microcontroller i use a Raspberrypi Pico (RP2040). Whenever there's an error or something wrong, i need to unplug the MCU and reconnect it. I read that recently the USB-Reset with Raspberrypi 3/4 is supported. Could somebody point me the way that USB-reset works, so i can code a similar solution for the Jetson Nano? Or does somebody have a solution for that problem?
I appreciate all the help i can get.

**Comment by Sineos** [comment]
As already stated when you opened the ticket: Issues here are for development only. Please be so kind to place your support / feature request on: [Klipper Discourse](https://klipper.discourse.group/)
