### ISSUE TITLE
BTT SKR no connection after Update

### ISSUE THREAD

**Issue by mpx1986** [Klipper3d/klipper#5447]
update Klipper and reflash Klipper on the BTT SKR 2. The Pi find the Board but in Mainsail is no connection to it.

[moonraker (1).log](https://github.com/Klipper3d/klipper/files/8544337/moonraker.1.log)
[klippy.log](https://github.com/Klipper3d/klipper/files/8544338/klippy.log)

**Comment by Sineos** [comment]
As already stated when you opened the ticket: Issues here are for development only. Please be so kind to place your support / feature request on: [Klipper Discourse](https://klipper.discourse.group/)
