### ISSUE TITLE
[FR] SAVE_CONFIG without restarting the machine

### ISSUE THREAD

**Issue by yzheka** [Klipper3d/klipper#5456]
I would like to see a usefull (as for me) feature to be able to update printer.cfg without restarting firmware. It will be usefull for example for adjusting z offset on-the-fly: start a print->fine tune z offset to get perfect first layer->save offset to a config without interrupting the print process. With this feature one will not forget to update config after print finish

**Comment by Sineos** [comment]
As already stated when you opened the ticket: Issues here are for development only. Please be so kind to place your support / feature request on: [Klipper Discourse](https://klipper.discourse.group/)

**Comment by yzheka** [comment]
Ok, sorry. I will close it
