### ISSUE TITLE
uart setup for btt octopus can be dangerous .

### ISSUE THREAD

**Issue by marcin76** [Klipper3d/klipper#5458]
When try to update klipper firmware for latest one , by mistake I chose wrong usart port . As a result my hotend start heating without any control.
I have found that one of USART2 control pin: PA2 and PA3, on BTT octopus  are used for control hotend. As a result after wrong selection when u flash firmware to board hotend will heating all the time without any control ( no fan for hotend or anything)

<img width="401" alt="Screenshot 2022-04-25 at 20 03 05" src="https://user-images.githubusercontent.com/4108611/165164793-16e369aa-db1f-460f-a418-7d79d6efe483.png">
<img width="443" alt="Screenshot 2022-04-25 at 20 03 24" src="https://user-images.githubusercontent.com/4108611/165164802-bde0c401-ceeb-4e82-9671-c304f34649c4.png">

![IMG_0335](https://user-images.githubusercontent.com/4108611/165165927-465d1d7b-b19d-4ef6-b256-f2bd80c20464.jpeg)

**Comment by Sineos** [comment]
As already stated when you opened the ticket: Issues here are for development only. Please be so kind to place your support / feature request on: [Klipper Discourse](https://klipper.discourse.group/)
