### ISSUE TITLE
after update klipper will not allow heat bed to reach certain temps

### ISSUE THREAD

**Issue by Takohtuesdays** [Klipper3d/klipper#5463]
I have 3 printers 2 ender 2 pro's with same board (creality 4.2.7) and setup and config, and a voron switchwire with an skr mini e3 v2 with EPCOS 100K B57560G104F type thermistor sensors, I updated klipper and reflashed mcu on all printers and now i cannot reach 105c on all printers when i have been able to in the past (one of the enders is brand new). I doubt it's hardware related due to the fact that all 3 printers are giving error: Heater heater_bed not heating at expected rate
See the 'verify_heater' section in docs/Config_Reference.md
for the parameters that control this check.

[Ender 3 pro 1 klippy.log](https://github.com/Klipper3d/klipper/files/8579566/Ender.3.pro.1.klippy.log)
[Ender 3 pro 2 klippy.log](https://github.com/Klipper3d/klipper/files/8579567/Ender.3.pro.2.klippy.log)
[Voron SW klippy.log](https://github.com/Klipper3d/klipper/files/8579568/Voron.SW.klippy.log)

**Comment by Sineos** [comment]
As already stated when you opened the ticket: Issues here are for development only. Please be so kind to place your support / feature request on: [Klipper Discourse](https://klipper.discourse.group/)
