### ISSUE TITLE
After Updating - Nothing works

### ISSUE THREAD

**Issue by SpaWn12** [Klipper3d/klipper#5467]
I updated Klipper on my printer with mks 1.4 and TMC2130 

The comunication with spi didn't work.

I get the error:  Unable to write tmc spi 'stepper_x' register GCONF
[klippy.log](https://github.com/Klipper3d/klipper/files/8591388/klippy.log)

Nothing changed by the wiring, just updateding the firmware.

**Comment by SpaWn12** [comment]
Now I get the error

TMC 'stepper_x' reports error: DRV_STATUS: 00000000 cs_actual=0(Reset?)
Once the underlying issue is corrected, use the
"FIRMWARE_RESTART" command to reset the firmware, reload the
config, and restart the host software.
Printer is shutdown
Klipper state: Not ready
[klippy.log](https://github.com/Klipper3d/klipper/files/8591985/klippy.log)

**Comment by bill-orange** [comment]
Syntax looks odd in your config file for sensorless homing.  You have  driver_sgt = 20.  I think it should be something like driver_SGT: -64 

See if that makes a difference.

**Comment by SpaWn12** [comment]
I started from scratch.
Now it’s working.

**Comment by Sineos** [comment]
Closed as concluded. For the future please open such requests on https://klipper.discourse.group
