### ISSUE TITLE
Fysetc Spider breaks after recent update

### ISSUE THREAD

**Issue by Sjoerd** [Klipper3d/klipper#5475]
Several people (including me) are experiencing issues with the latest Klipper update and a Fysetc Spider.
The Fysetc board doesn't seem to respond to anything anymore, also re-flashing the bootloader doesn't solve the problem.

Raspberry Pi 3 B+
Fysetc Spider V1.1

**Comment by Sineos** [comment]
As already stated when you opened the ticket: Issues here are for development only. Please be so kind to place your support / feature request on: [Klipper Discourse](https://klipper.discourse.group/)
