### ISSUE TITLE
Heat bed probe drops out while printing

### ISSUE THREAD

**Issue by that-should-work** [Klipper3d/klipper#5478]
About a month ago, the thermistor on the bed would drop to -40~-50C.
Replaced the thermistor, no go
Replaced the stock CR10 board with an skr2, no go

When running manually, the probe reads the bed fine and I can move all the cables without it dropping.
When a print is started the bed heats to temp, a purge line is printed.
Within seconds of starting the skirt, the probe drops to -50C and I get an ADC fault that shuts everything down. This has been repeatable.
Probe fault last 10-15s before reading correctly again.
[klippy.log](https://github.com/Klipper3d/klipper/files/8612500/klippy.log)

**Comment by ld3300** [comment]
@that-should-work I have responded to you on discord

-David
