### ISSUE TITLE
error in driving

### ISSUE THREAD

**Issue by GiuseppeSiragusa** [Klipper3d/klipper#5479]
the guide indicates this command to generate the png file, it is incorrect
~/klipper/scripts/calibrate_shaper.py /tmp/resonances_x_*.csv -o /tmp/shaper_calibrate_x.png

the correct command is:

~/klipper/scripts/calibrate_shaper.py /tmp/calibration_data_x_*.csv -o /tmp/shaper_calibrate_x.png

**Comment by Sineos** [comment]
The information is correct:
* resonances_x_*.csv is created by `TEST_RESONANCES AXIS=X`
* raw_data_x_*.csv is created by `TEST_RESONANCES AXIS=X OUTPUT=raw_data`
* calibration_data_x_*.csv is created by `SHAPER_CALIBRATE`

`SHAPER_CALIBRATE` is the command for auto tuning (from Octoprint or other WebUI) and does not need offline processing. 

All documentation that uses _resonances_x__\*_.csv_ /  _raw_data_x__\*_.csv_ data, says to use `TEST_RESONANCES` for the `calibrate_shaper.py` command.  

There is only the one minor point that the docs do not explicitly mention that you can **also** use _calibration_data_x__\*_.csv_ to do the offline processing but this is not the typical use case.
