### ISSUE TITLE
STM32G0 I2C PIN and Function Error in SKR MINI E3 V3 board

### ISSUE THREAD

**Issue by gghyoo** [Klipper3d/klipper#5490]
https://github.com/Klipper3d/klipper/blob/7e76bd561a451172f8d03001445a3bd21e3866d7/src/stm32/stm32f0_i2c.c#L25

This line should change to :
```C
#if CONFIG_MACH_STM32G0
    { I2C1, GPIO('B', 8), GPIO('B', 9), GPIO_FUNCTION(6) },
#else
    { I2C1, GPIO('F', 1), GPIO('F', 0), GPIO_FUNCTION(1) },
#endif
```

**Comment by Sineos** [comment]
A pull request would be very much appreciated. This would ensure the developers are looking at it and reviewing such changes.

**Comment by Sineos** [comment]
Continued with https://github.com/Klipper3d/klipper/pull/5493
Thanks for the PR, appreciated!
