### ISSUE TITLE
Thermal Runaway only when printing

### ISSUE THREAD

**Issue by jappyjan** [Klipper3d/klipper#5498]
I use Klipper on my Ender 3 Pro.
This setup worked for months without problems.

Suddenly whenever i print something after reaching about 2mm Z-Height (no matter what i print),
Klipper shuts down with a thermal runaway error.

When i heat the nozzle without printing i can keep the temperature for hours (when making sure its not reset to 0 after the timeout)
without getting any errors, also it hold the temperature just fine.

I already did a PID Tune but that did not help.

What can i do to figure out what the problem is, i dont want to randomly buy a new heater/thermistor without knowing that those are actuably broken...

**Comment by Sineos** [comment]
As already stated when you opened the ticket: Issues here are for development only. Please be so kind to place your support / feature request on [Klipper Discourse](https://klipper.discourse.group/)

Also attach your klippy.log file there
