### ISSUE TITLE
Problem with BLTOUCH after flash linux process for pi 3b mcu for use adxl345

### ISSUE THREAD

**Issue by throsan93** [Klipper3d/klipper#5499]
Hi, i flash "linux process" en the pi3b for use adxl345 accelerometer, but after that, the bltouch is always triggered and always report 
20:01:55
Klipper state: Ready
20:01:52
Failed to verify BLTouch probe is raised; retrying.
20:01:50
Failed to verify BLTouch probe is raised; retrying.

the bltouch is working before the flash

Id attach the klippy log

thx!

Br, throsan93

[klippy (2).log](https://github.com/Klipper3d/klipper/files/8672378/klippy.2.log)

**Comment by Sineos** [comment]
As already stated when you opened the ticket: Issues here are for development only. Please be so kind to place your support / feature request on [Klipper Discourse](https://klipper.discourse.group/)

Also attach your klippy.log file there
