### ISSUE TITLE
Unable To Start/Select Print After Update.

### ISSUE THREAD

**Issue by pinolt** [Klipper3d/klipper#5500]
Fluidd
Klipper
Moonraker
OS Package 

Were updated on the 13th of May 2022, since the update I am unable to select a print regardless of the method : _click printer icon_ or _right click -> print_.

Please help me out,
Thanks
[klippy.log](https://github.com/Klipper3d/klipper/files/8683850/klippy.log)

**Comment by dflorea4231** [comment]
This is what I see from the moonraker.log file

[moonraker (1).log](https://github.com/Klipper3d/klipper/files/8684325/moonraker.1.log)

```
Traceback (most recent call last):
  File "/home/pi/moonraker/moonraker/websockets.py", line 253, in execute_method
    result = await callback(params)
  File "/home/pi/moonraker/moonraker/websockets.py", line 362, in func
    result = await callback(
  File "/home/pi/moonraker/moonraker/components/klippy_apis.py", line 75, in _gcode_start_print
    return await self.start_print(filename)
  File "/home/pi/moonraker/moonraker/components/klippy_apis.py", line 118, in start_print
    await self.klippy.wait_started()
  File "/home/pi/moonraker/moonraker/klippy_connection.py", line 115, in wait_started
    await asyncio.wait_for(
  File "/usr/lib/python3.9/asyncio/tasks.py", line 494, in wait_for
    raise exceptions.TimeoutError() from exc
asyncio.exceptions.TimeoutError
```

**Comment by hathawayoutthere** [comment]
[moonraker.log](https://github.com/Klipper3d/klipper/files/8684505/moonraker.log)

I am also having this issue after udpating Klipper/Moonraker an hour ago.

All commands work, but gcode uploads fail and any existing files cannot be printed.

I keep getting: "Internal Server Error"

**Comment by teeedubb** [comment]
Can confirm this issue. Reverting to the prior commit solves it.

**Comment by pinolt** [comment]
> Can confirm this issue. Reverting to the prior commit solves it.

How does one do this?

**Comment by pinolt** [comment]
> I have this same issue. Just installed some new hardware today after being down for a couple of months and didn't know there was an update released today. Unable to print, but I can send all sorts of commands to the printer, as I was able to do my bed leveling and z offset, testing the extruder function and PID tunning. Everything works except for trying to actually send a job to print.
> 
> This is what I see from the moonraker.log file
> 
> [moonraker (1).log](https://github.com/Klipper3d/klipper/files/8684325/moonraker.1.log)
> 
> ```
> Traceback (most recent call last):
>   File "/home/pi/moonraker/moonraker/websockets.py", line 253, in execute_method
>     result = await callback(params)
>   File "/home/pi/moonraker/moonraker/websockets.py", line 362, in func
>     result = await callback(
>   File "/home/pi/moonraker/moonraker/components/klippy_apis.py", line 75, in _gcode_start_print
>     return await self.start_print(filename)
>   File "/home/pi/moonraker/moonraker/components/klippy_apis.py", line 118, in start_print
>     await self.klippy.wait_started()
>   File "/home/pi/moonraker/moonraker/klippy_connection.py", line 115, in wait_started
>     await asyncio.wait_for(
>   File "/usr/lib/python3.9/asyncio/tasks.py", line 494, in wait_for
>     raise exceptions.TimeoutError() from exc
> asyncio.exceptions.TimeoutError
> ```

Any ideas on how to resolve the issues experienced with moonraker?

**Comment by Sineos** [comment]
As already stated when you opened the ticket: Issues here are for development only. Please be so kind to place your support / feature request on [Klipper Discourse](https://klipper.discourse.group/)

Also attach your klippy.log / moonraker.log file there

**Comment by pinolt** [comment]
> As already stated when you opened the ticket: Issues here are for development only. Please be so kind to place your support / feature request on [Klipper Discourse](https://klipper.discourse.group/)
> 
> Also attach your klippy.log / moonraker.log file there

Thank you

**Comment by hathawayoutthere** [comment]
Here is a temporary fix. I found (performed when ssh'd into the pi)

cd moonraker

git reset --hard 3d9f5dc6d9d106973dc636b1512d0ce26720ce34 && git clean -f

sudo systemctl restart moonraker

**Comment by Xilius** [comment]
> 

Thanks this helped!

**Comment by Arksine** [comment]
Sorry guys, this was a bug I introduced in a recent commit.  It should be fixed now.
