### ISSUE TITLE
Unknown pin chip name 'tmc2209_manual_stepper_selector_stepper

### ISSUE THREAD

**Issue by mattr254** [Klipper3d/klipper#5501]
Hello all,
Quick background I'm trying to run a SKR MINI E3 V3 as a second MCU for a MMU2s. I'm trying to use a virtual endstop for one of the motors. I'm having difficulty trying to get it to work. I've tried multiple syntaxes ( _ )  and even renamed the following motor to make it less confusing, I have comm with the motor and can command it where to go I just can't get the virtual endstop to function. Any help would be greatly appreciated as I couldn't find anything except for z probes... When I try to do anything I get the following message "Unknown pin chip name 'tmc2209_manual_stepper_selector_stepper" 

# Z : MMU2S color selector
[manual_stepper selector_stepper]
step_pin: mmboard:PB0
dir_pin: !mmboard:PC5
enable_pin: !mmboard:PB1
# 80 step/mm
microsteps: 16
rotation_distance: 4
velocity: 30 #35
accel: 100
#endstop_pin: ^mmboard:PC2 # ENDSTOP SENSE
endstop_pin: tmc2209_manual_stepper_selector_stepper:virtual_endstop
homing_retract_dist: 0

[tmc2209 manual_stepper selector_stepper]
uart_pin: mmboard:PC11
tx_pin: mmboard:PC10
uart_address: 1
run_current: 1.000
sense_resistor: 0.110
stealthchop_threshold: 999999
diag_pin: ^mmboard:PC2
driver_SGTHRS:50

**Comment by Sineos** [comment]
As already stated when you opened the ticket: Issues here are for development only. Please be so kind to place your support / feature request on [Klipper Discourse](https://klipper.discourse.group/)

Also attach your klippy.log file there
