### ISSUE TITLE
BME280 not working on Klipper

### ISSUE THREAD

**Issue by MaryGave** [Klipper3d/klipper#5503]
Hello, I have a problem with the BME280 sensor, after connecting the sensor, the application on the phone for raspberry service correctly detects the sensor and you can see the readings that are updated on a regular basis, I added all the necessary information to the configuration file, but mainsail shows zero readings and the application on the phone no longer detects sensor only when I restart the raspberry application shows the readings again.

[temperature_sensor chamber]
sensor_type: BME280
i2c_address: 118
i2c_mcu: rpi
i2c_bus: i2c.1
i2c_speed: 100000

**Comment by Sineos** [comment]
As already stated when you opened the ticket: Issues here are for development only. Please be so kind to place your support / feature request on [Klipper Discourse](https://klipper.discourse.group/)

Also attach your klippy.log file there
