### ISSUE TITLE
Getting various TMC issues since adding a 12864mini LCD

### ISSUE THREAD

**Issue by Rudis1261** [Klipper3d/klipper#5505]
I have no idea where to start debugging this 🙈  

My printer setup is:
- Annex K3
- BTT Octopus 8 * TMC2209s
- 300w 24V PSU
- BTT 12864 v1.0 with the reset resistor removed (it was resetting the printer all the time)

I added the BTT 12864 LCD to my printer, and ever since I have been getting various TMC driver issues (TMC2209s sensorless homing). The printer performs 100% fine, but as soon as I add the `[display]` block, it becomes very unstable, and randomly gives one of many TMC fault codes. 

The config I got from all the BTT repos, and should be fine, and I have double-checked them against a Voron 2.4 config, which seem to be correct, except the neopixel index order, but that should be fine. 

```
########################################
# EXP1 / EXP2 (display) pins
########################################

[board_pins]
aliases:
    # EXP1 header
    EXP1_1=PE8, EXP1_2=PE7,
    EXP1_3=PE9, EXP1_4=PE10,
    EXP1_5=PE12, EXP1_6=PE13,    # Slot in the socket on this side
    EXP1_7=PE14, EXP1_8=PE15,
    EXP1_9=<GND>, EXP1_10=<5V>,

    # EXP2 header
    EXP2_1=PA6, EXP2_2=PA5,
    EXP2_3=PB1, EXP2_4=PA4,
    EXP2_5=PB2, EXP2_6=PA7,      # Slot in the socket on this side
    EXP2_7=PC15, EXP2_8=<RST>,
    EXP2_9=<GND>, EXP2_10=<5V>

###############################################
#	mini12864 LCD Display
###############################################
[display]
#  mini12864 LCD Display
lcd_type: uc1701
cs_pin: EXP1_3
a0_pin: EXP1_4
rst_pin: EXP1_5
encoder_pins: ^EXP2_5, ^EXP2_3
click_pin: ^!EXP1_2
contrast: 63
spi_software_miso_pin: EXP2_1
spi_software_mosi_pin: EXP2_6
spi_software_sclk_pin: EXP2_2

[neopixel btt_mini12864]
#  To control Neopixel RGB in mini12864 display
pin: EXP1_6
chain_count: 3
initial_RED: 1
initial_GREEN: 0
initial_BLUE: 0
color_order: RGB

#  Set RGB values on boot up for each Neopixel. 
#  Index 3 = display, Index 1 and 2 = Knob
[delayed_gcode setdisplayneopixel]
initial_duration: 1
gcode:
       SET_LED LED=btt_mini12864 RED=1 GREEN=0 BLUE=0 INDEX=1 TRANSMIT=0
       SET_LED LED=btt_mini12864 RED=1 GREEN=0 BLUE=0 INDEX=2 TRANSMIT=0
       SET_LED LED=btt_mini12864 RED=1 GREEN=0.2 BLUE=0.2 INDEX=3

```

**Comment by Rudis1261** [comment]
Any ideas/thoughts on how to isolate/trace the issue would be welcome!

**Comment by Sineos** [comment]
As already stated when you opened the ticket: Issues here are for development only. Please be so kind to place your support / feature request on [Klipper Discourse](https://klipper.discourse.group/)

Also attach your klippy.log file there

See:
https://klipper.discourse.group/t/tmc-extruder-reports-error-gstat-00000001-reset-1-reset/1156/39?u=sineos

**Comment by Rudis1261** [comment]
Cool cool, tnx 😢
