### ISSUE TITLE
New slider (PA, smooth time) does not work proper with extruder_stepper config

### ISSUE THREAD

**Issue by homasholz** [Klipper3d/klipper#5510]
The new sliders do not work with my extruder config. See screenshots attached. 

![image](https://user-images.githubusercontent.com/43454128/168966150-6325ec24-d38e-4712-931d-3ea2de0f6e1f.png)
![image](https://user-images.githubusercontent.com/43454128/168966342-377fcfec-4f5f-490b-86e2-71c39d7bde78.png)
![image](https://user-images.githubusercontent.com/43454128/168966178-0399d1ed-a789-43f6-b3c7-552a79ab1a1b.png)
![image](https://user-images.githubusercontent.com/43454128/168966218-692cbfc9-fe33-4094-8f1a-71de08edb3ab.png)
![image](https://user-images.githubusercontent.com/43454128/168966242-72f52a8d-dfcc-422d-a329-a3fde27c81f7.png)

**Comment by Sineos** [comment]
This is not a Klipper issue but an issue of the web interface (fluidd / mainsail) you are using.

**Comment by homasholz** [comment]
oh yes, sorry was on wrong page 🙈
