### ISSUE TITLE
no scv control for delta z axis moves. 

### ISSUE THREAD

**Issue by danorder** [Klipper3d/klipper#5511]
not having a scv option presents certain problems. 
high acc isn't ideal for homing or potential crashes just  to speed it up 
small hop values are particularly slow without setting acc high. 
eg 500 -800 acc on  a voron is generally snappier while homing retains sane  values.

**Comment by Sineos** [comment]
https://klipper.discourse.group/t/add-delta-scv-control-for-delta-z/2905
