### ISSUE TITLE
New install on Taz 6 with Hemera 175 toolhead

### ISSUE THREAD

**Issue by reinharm1959** [Klipper3d/klipper#5513]
[klippy (1).log](https://github.com/Klipper3d/klipper/files/8716617/klippy.1.log)
Getting multiple errors on unrecognized G code commands. Bed heats up but extruder remains off or 0.

**Comment by Sineos** [comment]
As already stated when you opened the ticket: Issues here are for development only. Please be so kind to place your support / feature request on [Klipper Discourse](https://klipper.discourse.group/)
