### ISSUE TITLE
random restart klipper

### ISSUE THREAD

**Issue by drveni** [Klipper3d/klipper#5524]
i gotta strange behavior. I'm not sure .. I've been updated (last 2-3 updates !?). during printing the printer stops printing by itself and resets out. there are simply no rules. sometimes he knows how to work for days. and is sometimes reset 3 times in the middle of the print. there are simply no rules or what to print. not the length of the print. for smaller pieces it is not a problem. for larger pieces that last 1 day it is not very comfortable. I was hoping the last two upgrades would work out. but they are not. there are simply no rules. it manifests only to crack the print and get stuck at one point in the print. an error pops up to reset the firmware or printer. none of the commands help. the printer must be physically turned off and on. no hardware modifications have been made. 
[klippy.log](https://github.com/Klipper3d/klipper/files/8755387/klippy.log)

i don't see any weird things from the clipper in the log. I have no idea what else to look at, take it off and send it. i don't know if maybe it's a mistake in something else or in the clipper itself. maybe moonraker !? if I missed the group my apologies.

I have no idea if you happen to see me with others. ?!

**Comment by Sineos** [comment]
As already stated when you opened the ticket: Issues here are for development only. Please be so kind to place your support / feature request on [Klipper Discourse](https://klipper.discourse.group/)
