### ISSUE TITLE
Issue #5008 persists when M117 and M118 are renamed

### ISSUE THREAD

**Issue by tux2603** [Klipper3d/klipper#5527]
When using a gcode macro to redefine the behavior of M117 or M118, the renamed base call to M117 or M118 will be affected by the bug mentioned in issue #5008 

Steps to reproduce:

1. Add the gcode macro example redefining M117 given in the documentation to `printer.cfg` and restart klipper
```
[gcode_macro M117]
rename_existing: M117.1
gcode:
    M117.1 { rawparams }
    M118 { rawparams }
```
2. Run the command `M117 test`. It will work as expected
3. Run the command `M117 123 test`. It will raise an error "Unknown command:"M117.1 123"

[klippy log file](https://github.com/Klipper3d/klipper/files/8781362/klippy.log)

**Comment by Sineos** [comment]
Considered resolved via PRs linked above.
