### ISSUE TITLE
Z_TILT and position_endstop not compatible? Z=0 always wrong when using Z_TILT_ADJUST

### ISSUE THREAD

**Issue by Hundsbuah** [Klipper3d/klipper#5530]
Hi there,

i have a strange klipper behaviour. I cannot use

```
[z_tilt]
z_positions:  -60, 117.5
             340, 117.5
points:        70, 117.5
             280, 117.5
speed: 300
horizontal_move_z: 3
retries: 10
retry_tolerance: 0.005
```
and

```
#*# [stepper_z]
#*# position_endstop = -0.090
```
together. Z=0 is always wrong when using Z_TILT_ADJUST
Babystepping/Z-Offset is adjusted via shifting the “Z-Endstop”:

![2022-05-24 12_26_23-22% Printing - ETA_ 13_19 - CFFFP_3DBenchy gcode](https://user-images.githubusercontent.com/2735699/170768762-0c1eb14f-212a-426f-adb0-95368fbfdc86.png)

which results in:
```
#*# [stepper_z]
#*# position_endstop = -0.090
```

**MBL:**

```
[probe]
pin: ^PC2
x_offset: -35
y_offset: 0
speed: 1
samples: 1
lift_speed: 12

[bed_mesh]
speed: 300
horizontal_move_z: 3
mesh_min: 35,10
mesh_max: 245,220
probe_count: 3,3
fade_start: 1
fade_end: 0
relative_reference_index: 4
```

Z Stepper:
```
[stepper_z]
step_pin: PA15
dir_pin: PA8
enable_pin: !PD1
microsteps: 32
rotation_distance: 4
full_steps_per_rotation: 200
endstop_pin: ^!PC0
position_min = -4
position_max: 300
homing_speed: 4
homing_retract_speed: 2
homing_retract_dist: 3
second_homing_speed: 0.5

[stepper_z1]
step_pin: PD11
dir_pin: PD10
enable_pin: !PD13
microsteps: 32
rotation_distance: 4
full_steps_per_rotation: 200
endstop_pin: ^!PA0
```

**Hardware:**
CoreXY with 2 Z motors and 2 Z endstops and 1 induktive probe for mesh bed leveling

**How to reproduce the problem:**
Set the

```
#*# [stepper_z]
#*# position_endstop = -0.090
```
to some high value, so that the nozzle will be some mm over the bed for z=0, lets say position_endstop = -3.0

Now home all axis and do a mesh bed leveling. after that go to some point of the bed. i.e center and type G0 Z0
**_The nozzle is about 3mm over the bed, which is correct, i have a z position endstop of -3 defined._**

Now home all axis, do a Z_TILT_ADJUST and then mesh bed leveling. after that go again to some point of the bed. i.e center and type G0 Z0. **_Now the nozzle is attached to the bed._**

It seems the the “offset” from position_endstop is ignored or not used for final z calculation. Does s.o. else encountered the same problem?

[klippy.log](https://github.com/Klipper3d/klipper/files/8788986/klippy.log)

I posted it here, but i created a github issue now, because i think its a bug.
https://klipper.discourse.group/t/z-tilt-and-position-endstop-not-compatible-z-0-always-wrong/2976

**Comment by Sineos** [comment]
Please do not cross post. The developers are monitoring the Discourse as well.
