### ISSUE TITLE
WHY IS IT SO FUCKING HARD TO TELL ME WHAT ADC IS OUT OF RANGE AND BY HOW MUCH????????????????

### ISSUE THREAD

**Issue by kilinvitunklitoris** [Klipper3d/klipper#5531]
Fault finding is real pain in the ass, because of this and has been for ages! For fuck sake! Yes I am fustrated, but come on. Really how hard can it be? It's not even in the fucking log file!!! Do you think I am some kind of medium or what? This is really some microsoft/apple level of shit! Yes you have an error, but NO we wont give you more info on it, because it would otherwise be too easy for you. HA fucking HA!
I think my head is going to explode!

**Comment by KevinOConnor** [comment]
The content and language of your comment here is inappropriate.
