### ISSUE TITLE
MAX_HEAT_TIME causes heaters to occasionally drop out of tolerant temperature

### ISSUE THREAD

**Issue by junlingm** [Klipper3d/klipper#5532]
The MAX_HEAT_TIME in klippy/extras/heaters.py causes oscillations in temperature control, because it introduces a delay. This delay may occasionally cause the heater temperature to drop out of tolerant range since the Pam may keep at 0 for about 5 seconds and prevent the heater from heating up. Removing it makes the oscillations in the temperature curves much smaller.

I wonder what is the logic after this variable? Can we remove it?

**Comment by Sineos** [comment]
As already stated when you opened the ticket: Issues here are for development only. Please be so kind to place your support / feature request on [Klipper Discourse](https://klipper.discourse.group/)
