### ISSUE TITLE
Need to document necessity of max_extrude_only_accel and/or improve default

### ISSUE THREAD

**Issue by richfelker** [Klipper3d/klipper#5534]
Over the past few days on Discord, I've helped multiple users who were experiencing severe print quality issues stemming from failed retraction due to physically unachievable `max_extrude_only_accel` making their extruder slip or skip motor steps. This usually manifests as overextrusion after unretract, since part or all of the retract failed to happen, but could occur in the other direction if retracting is "easier" than unretract. This is giving users a really bad first impression of Klipper.

None of the users I helped through this were even aware that Klipper *has* a retraction-acceleration setting, much less where to set it or what the default is. And the way the default is computed is very convoluted, defined in terms of filament diameter, nozzle diameter (inirectly via max extrude cross section), and print acceleration. Assuming 1.75 mm filament and 0.4 nozzle, it comes out to 267% of max print acceleration. For example, if the user has set print acceleration to 20000 (very reasonable for some printers), that produces a retraction acceleration of 5340, which no reduction-geared extruder is capable of achieving with normal 1.8 or 0.9 degree stepper motors.

Probably the simplest fix for this is putting a safe example `max_extrude_only_accel` in the configuration samples, along with a comment that it should be tuned to your extruder. Asking around among people who do high-speed printing on geared extruders, a value of 1500 was the consensus I got, though I would include a caveat that you probably want somewhat higher for a bowden extruder because 1500 will be very slow.

**Comment by Sineos** [comment]
Please move such a discussion to Discourse, potentially into the Developers section.
At first glance this does not seem conclusive for me, especially 

> I would include a caveat that you probably want somewhat higher for a bowden extruder because 1500 will be very slow.
