### ISSUE TITLE
Error on I2C lines in klipper

### ISSUE THREAD

**Issue by Hateyaall** [Klipper3d/klipper#5539]
Hello everyone, I have an issue with klipper. I am not using it for 3D printing. I have designed a custom hardware. It consists of large heater plate switched by a MOSFET and reading a TCN75AV0A I2C sensor. At each corner of this heater plate I have one more of those sensors heating up with 40 W cartridge heater a standard Mk8 Creality heater block. For control I use a MUX PCA9545A. The main idea was to switch between different sensors and heat each one at a time. A general mistake in the design of the board I placed only one MOSFET to switch  all heaters. The MUX idea for the logic is dead but I can still test my device non the less. Now I have to heat them up at the same time this just takes longer but is not an issue for testing. I use a Raspberry pi 4 to run klipper and an arduino micro as controller. My device requires two of these plate boards. I switch between addresses of the two boards one uses the MUX address 112 and the other 113 by bringing up a certain pin on the controller. I use a custom driver for PCA9545A mux that in testing works fine. I have problems with switching between the two boards. If I connect one of the boards and give it the default address of the MUX 112 it works I can heat everything and I don't have any errors. The problem comes when I try to use the other 113 address. After restart I can see the temps of the sensors but just for a bit then klipper shutdowns and error message: CommandError: Unable to obtain 'i2c_read_response' response.

[PCA9545A.txt](https://github.com/Klipper3d/klipper/files/8804121/PCA9545A.txt)
[mlm75 mux code original.txt](https://github.com/Klipper3d/klipper/files/8804126/mlm75.mux.code.original.txt)
[klippy.log.txt](https://github.com/Klipper3d/klipper/files/8804129/klippy.log.txt)

As far as I am with testing the hardware I see no hardware error and everything works fine as long as I use the default MUX address. Am I doing something wrong or is there something wrong with klipper?

**Comment by Sineos** [comment]
As already [stated when you opened the ticket](https://www.klipper3d.org/Contact.html): Issues here are for development only. Please be so kind to place your support / feature request on [Klipper Discourse](https://klipper.discourse.group/)
