### ISSUE TITLE
Nema23 Stepper

### ISSUE THREAD

**Issue by carl1961** [Klipper3d/klipper#5543]
I have searched for hours online and youtube, now to ask, How to setup klipper for using external Stepper driver? dir, step, enable pins. need to control nema23 steppers.

**Comment by Sineos** [comment]
As already [stated when you opened the ticket](https://www.klipper3d.org/Contact.html): Issues here are for development only. Please be so kind to place your support / feature request on [Klipper Discourse](https://klipper.discourse.group/)
