### ISSUE TITLE
TMC2130 spi mode with physical endstop not working.

### ISSUE THREAD

**Issue by AnandRaj-R** [Klipper3d/klipper#5547]
I am trying to disable the sensorless homing from Tmc2130 driver because layer shifting after power loss so i comment the virtual_endstop and uncomment the physical endstop pin

#tmc2130_stepper_y : virtual_endstop     
endstop_pin : ^!PJ1

in printer config file and also disconnect the diag1 pin from physical endstop pin after restart i check the endstop it's always open and not triggered.

Printer : Anet A8
Motherboard : MKS GenL v2.1
Stepper driver : TMC2130 with spi mode(Bigtreetec)
[printer.cfg.txt](https://github.com/Klipper3d/klipper/files/8837635/printer.cfg.txt)

**Comment by Sineos** [comment]
As already [stated when you opened the ticket](https://www.klipper3d.org/Contact.html): Issues here are for development only. Please be so kind to place your support / feature request on [Klipper Discourse](https://klipper.discourse.group/)
