### ISSUE TITLE
Firmware problem ?

### ISSUE THREAD

**Issue by Rom1T3** [Klipper3d/klipper#5548]
Forgive me for my very bad English google translation.

I just updated:
- fluidd: v1.18.1
- klipper: v0.10.0-448-g9047702a
- moonraker: v0.7.1-573-g74d6e35

Hardware configuration:
Creality ender 3
- mcu: creality 4.2.7
- Bltouch
- extruder: biqu H2
- End of filament detector

Problem :
Since the update on all of my new prints, I have a shift on the Z axis during printing when moving my nozzle on the X axis on the 1st layer, which forms a kind of arc for me. circle on the Z axis (example distance: x:10 y:100 z:2 - x:100
 y:100 z:0 - x:200
 y:100 z:2)

Consequence: Part of the one if it sticks well to the board (the center of my parts on the contour) and on the outside of my X axis part it doesn't at all stick to the board.

In addition the filling is the same I have a Z axis rise ~2mm I stopped at the 1st layer because it is the base if the base is not solid the result will be a disaster.

All my prints start with a G29

Has anyone else had a problem? is this a firmware issue?

Having made no other modification than an update, I do not see where the problem would be.

I enclose my config file sometimes it is to ask me in .txt of course it goes without saying that they are .cfg

[macros.txt](https://github.com/Klipper3d/klipper/files/8837980/macros.txt)
[other.txt](https://github.com/Klipper3d/klipper/files/8837981/other.txt)
[printer.txt](https://github.com/Klipper3d/klipper/files/8837982/printer.txt)

Photo : ![1654354362285](https://user-images.githubusercontent.com/106875031/172009269-07ca0aa6-3e98-4304-afd0-849eeefbb84e.jpg)

**Comment by Sineos** [comment]
Please do not cross post
