### ISSUE TITLE
Can't get Klipper, ender board 4.2.7 and Octoprint working together

### ISSUE THREAD

**Issue by maikeru896** [Klipper3d/klipper#5555]
Ok so, I have followed every instruction I can find relating to my situation. I have followed all the instructions on how to install Klipper to the point where I would flash the board. Since I have a 4.2.7 board, I followed the instructions for making the .bin file and putting it on an sd card and attempting the flash there. 
After restarting the printer, the screen remained blank. I used the printer config file with my serial id and put it in the pi directory. It shows that the config is present on octoprint (the id is /dev/serial/by-id/usb-1a86_USB_Serial-if00-port0). at this point i still see a blank lcd and octoklipper hangs in connecting. 
![image](https://user-images.githubusercontent.com/107109193/172582204-9d3871ab-90f2-4fc9-8524-8fdb96b58488.png)
![image](https://user-images.githubusercontent.com/107109193/172582353-fe268cc0-bfd4-4a6b-8f4d-2fa2ca7d348f.png)
![image](https://user-images.githubusercontent.com/107109193/172583427-fd23fd4e-85c9-4f64-9916-8ca5f0bfa854.png)

I renamed the klipper.bin every time i tried to flash, I installed AVR-GCC Compiler etc etc. I have no idea what i missed or what Im doing wrong. Can anyone point out why this isnt working?

**Comment by Sineos** [comment]
As already [stated when you opened the ticket](https://www.klipper3d.org/Contact.html): Issues here are for development only. Please be so kind to place your support / feature request on [Klipper Discourse](https://klipper.discourse.group/)
