### ISSUE TITLE
Can not open serial port after printer restart

### ISSUE THREAD

**Issue by dozer47528** [Klipper3d/klipper#5564]
```
mcu 'mcu': Unable to open serial port: [Errno 2] could not open port /dev/ttyUSB0: [Errno 2] No such file or directory: '/dev/ttyUSB0'
```

I checked the mcu location and it will change from`/dev/ttyUSB0`to`/dev/ttyUSB1`.

`usb-Silicon_Labs_CP2102_USB_to_UART_Bridge_Controller_0001-if00-port0 -> ../../ttyUSB1`

But symbol link is correct.

Restart klipper and fireware didn't help.

**Comment by Sineos** [comment]
As already [stated when you opened the ticket](https://www.klipper3d.org/Contact.html): Issues here are for development only. Please be so kind to place your support / feature request on [Klipper Discourse](https://klipper.discourse.group/)
