### ISSUE TITLE
Wrong MCU Temperature on BPi-M2-Zero in Klipper

### ISSUE THREAD

**Issue by Markus-1984** [Klipper3d/klipper#5577]
Hi @all,

in order to get a cheaper base for Klipper i´ve succesfully run Raspbian buster in a BPi-M2-Zero.
Everything is working well but one thing is not working correct.
The MCU Temp. from the BPi which is provided at /sys/class/thermal/thermal_zone0/temp is not 5 digit. It´s only 2 digits long.
So when Klipper reads the Temp and divides it by  I think it´s 100 it only shows 0.1 °C.
Is there a chance to edit this multiplier by providing a parameter or just do a manual adjustment to the devider?

Best regards
Markus

**Comment by Sineos** [comment]
As already [stated when you opened the ticket](https://www.klipper3d.org/Contact.html): Issues here are for development only. Please be so kind to place your support / feature request on [Klipper Discourse](https://klipper.discourse.group/)
