### ISSUE TITLE
Must home axis error during the middle of a print

### ISSUE THREAD

**Issue by sdc53** [Klipper3d/klipper#5579]
Hi, 
I'm getting a "must home axis first" error _in the middle of a print_.  It seems like a hardware problem, but there is nothing in the log or console to indicate what triggered it.  The error occurs randomly, usually fairly early on in the print - in the first few layers.  I've inspected the gcode at the file offset that appears in the log and they are just normal print moves - no shutdown etc is occurring at that time.  Usually, I can print the exact same file again from the job history successfully.

I've already tried getting help for this issue over on discord to no avail.  

I've attached the log with an m112 shortly after the issue occurred again - suggest searching from the bottom up for the most recent must home axis error. 

It'd be awesome to get a clue as to what might be the source of the problem - the log isn't much help to me, and there's nothing in the console to give a reason - if it's hardware, like klipper sensed something wrong with a stepper - it's not telling me.  Thanks.

[klippy.log](https://github.com/Klipper3d/klipper/files/8907224/klippy.log)

**Comment by Sineos** [comment]
Github is not used for support requests. See above link. Please be so kind to place your support / feature request on [Klipper Discourse](https://klipper.discourse.group/)
