### ISSUE TITLE
BIGTREETECH MINI 12864 LCD not working butt neopixel is working

### ISSUE THREAD

**Issue by mitofun** [Klipper3d/klipper#5590]
sorry folks to bother you but need help
have got the skr 1.4t the pi 3 a+ and the btt mini 12864 
have remover the R1 C6 according to the https://docs.vorondesign.com/build/electrical/mini12864_klipper_guide.html

in the printer config file:
######################################################################
# Fysetc Mini 12864Panel v2.1 (with neopixel backlight leds)
######################################################################

[display]
##  mini12864 LCD Display
lcd_type: uc1701
cs_pin: P1.18
a0_pin: P1.19
encoder_pins: ^P3.25,^P3.26
click_pin: ^!P0.28
contrast: 63

[neopixel fysetc_mini12864]
##  To control Neopixel RGB in mini12864 display
pin: P1.21
chain_count: 3
initial_RED: 0.1
initial_GREEN: 0.5
initial_BLUE: 0.0
color_order: RGB

##  Index 1 = display, Index 2 and 3 = Knob
[delayed_gcode setdisplayneopixel]
initial_duration: 1
gcode:
        SET_LED LED=fysetc_mini12864 RED=1 GREEN=1 BLUE=1 INDEX=1 TRANSMIT=0
        SET_LED LED=fysetc_mini12864 RED=1 GREEN=0 BLUE=0 INDEX=2 TRANSMIT=0
        SET_LED LED=fysetc_mini12864 RED=1 GREEN=0 BLUE=0 INDEX=3

after save and restart have got :
mcu 'mcu': Unable to encode: config_spi

This type of error is frequently caused by running an older
version of the firmware on the micro-controller (fix by
recompiling and flashing the firmware).

Known versions: host=v0.10.0-278-g7c964e5f, mcu=v0.10.0-419-g4490a584, rpi=v0.10.0-278-g7c964e5f

Once the underlying issue is corrected, use the "RESTART"
command to reload the config and restart the host software.
Protocol error connecting to printer

also if do not activate the display section have got led on on the mini 12864
need some one who can show the way 
thank you)

**Comment by mitofun** [comment]
![image](https://user-images.githubusercontent.com/59706069/174658688-21ee77b9-eb02-44dc-b3b4-17863c1eeec7.png)
![image](https://user-images.githubusercontent.com/59706069/174658745-38a74372-7783-4f22-854a-47360ddea2f2.png)

**Comment by mitofun** [comment]
![image](https://user-images.githubusercontent.com/59706069/174658889-cfbf79ee-1ab9-4b4e-ba37-63522efdff0a.png)

**Comment by Sineos** [comment]
Github is not used for support requests. See above link. Please be so kind to place your support / feature request on [Klipper Discourse](https://klipper.discourse.group/)

**Comment by hobbyplace** [comment]
spi_software_miso_pin: EXP2_1
spi_software_mosi_pin: EXP2_6
spi_software_sclk_pin: EXP2_2
adding the spi config will bring it to life
