### ISSUE TITLE
EBB42 V1.1 STM32G0B1:   MCU 'EBBCan' shutdown: Timer too close

### ISSUE THREAD

**Issue by cristianku** [Klipper3d/klipper#5595]
I am running a Voron 2.4 with Octopus Pro 1.0, BTT U2C 1.1 and EBB42 1.1 STM32G0B1

All are with the latest firmware.

I am running the EBB42 with 4 wires from the U2C, using can bus communication.

I am also running a can bus communication, using a usb cable, from U2C to Octopus pro 1.0

I have set the can bus everywhere to 250000.

The error is repeatable over and over again, and always at the same point of the print. It actually starts after printing few layers, if my print is only few layers height , it doesn't appear.

So its not an overload . the raspberry pi 4 2gb I am using has 30% used CPU and 12% memory load... its not here the problem I think.

Can it be something in EBB42 from BigTreetech ?

and now after printing fine for few minutes, I am getting this error :

16:45:19
MCU 'EBBCan' shutdown: Timer too close

16:45:19

MCU 'EBBCan' shutdown: Timer too close
This often indicates the host computer is overloaded. Check
for other processes consuming excessive CPU time, high swap
usage, disk errors, overheating, unstable voltage, or
similar system problems on the host computer.
Once the underlying issue is corrected, use the
"FIRMWARE_RESTART" command to reset the firmware, reload the
config, and restart the host software.
Printer is shutdown

[klippy.log](https://github.com/Klipper3d/klipper/files/8958790/klippy.log)

**Comment by cristianku** [comment]
I forgot to add that i am using CanBoot on Klipper Octopus pro 1.0, and this is connected via usb cable to the U2C BTT 1.1

**Comment by cristianku** [comment]
I have a raspberry pi 4 2gb

**Comment by cristianku** [comment]
Uninstalled Obico ( ex spaghetti ) but still the same problem and always on the same layer ! ![image](https://user-images.githubusercontent.com/25354817/175225640-e6a733ed-5fff-4e78-b236-71b1dd0e0dbc.jpeg)

**Comment by cristianku** [comment]
![image](https://user-images.githubusercontent.com/25354817/175225691-f7100aa5-7c33-4a4f-beee-c0a784c316c3.jpeg)

**Comment by cristianku** [comment]
and if the problem is in EBB42 because the micro steps are too high ( 16 ) ?

**Comment by cristianku** [comment]
It's happening always at this layer

![image](https://user-images.githubusercontent.com/25354817/175230545-35ceb7fb-00c5-45d9-91b9-d44760644557.jpeg)

**Comment by cristianku** [comment]
maybe thats the reason ?

 Compiling out/src/stm32/can.o
src/stm32/can.c:68:3: warning: #warning CAN on STM32F4 is untested [-Wcpp]
  #warning CAN on STM32F4 is untested
   ^~~~~~~

**Comment by cristianku** [comment]
Solution ! the can communication between Bigtreetech U2C and OCTOPUS pro 1.0 STM32F4  is not working !!!!

**Comment by Sineos** [comment]
Please shift this discussion to the Klipper Discourse. Matching threads are already existing there:
https://klipper.discourse.group/t/experimental-usb-to-canbus-bridge-mode/3136
https://klipper.discourse.group/t/host-canbus-devices/37/8
