### ISSUE TITLE
input shaper for Z

### ISSUE THREAD

**Issue by bubnikv** [Klipper3d/klipper#5601]
It looks as if input shaper is not supported on Z axis. At least it is not mentioned in documentation and the firmware refuses the Z axis.

Input shaper on Z promisses quicker Z hops thus quicker prints. Would you please consider adding input shaping for Z axis?

Thanks for consideration,
Vojtech

**Comment by Matthias1992** [comment]
Sound also Usefull for a belt printer :)

**Comment by Sineos** [comment]
Github is not used for support / feature requests. See above link. Please be so kind to place your support / feature request on [Klipper Discourse](https://klipper.discourse.group/)
