### ISSUE TITLE
Strange extruder temperature behavior.

### ISSUE THREAD

**Issue by dudi300** [Klipper3d/klipper#5609]
Recently, I've been experiencing some strange temperature behavior. 
I start the 3d print. After about 2 hours I have small peaks on the temperature curve. These get bigger over time. So after 4 hrs. the temperature becomes so big that Klipper aborts with an ADC temperature error. By increasing the extruder max temperature I can avoid the error. I have not had such behavior with the previous version. I have no idea what this could be. After a reboot, the system is quiet for about 2 hours, then the behavior starts again. As I find when the peaks occur, the extruder temperature is briefly regulated to 100%. and remain up to a felt 2 seconds so. 

[klippy (4).log](https://github.com/Klipper3d/klipper/files/8994126/klippy.4.log)

![image](https://user-images.githubusercontent.com/48863145/175993170-83a4693a-ca60-4a86-b0af-fc34e5f57be1.png)

**Comment by Sineos** [comment]
Github is not used for support / feature requests as already stated when opening the Issue and detailed in above link. Please be so kind to place your support / feature request on [Klipper Discourse](https://klipper.discourse.group/)
