### ISSUE TITLE
Failed to verify BLTouch probe is raised; retrying.

### ISSUE THREAD

**Issue by jsmol11** [Klipper3d/klipper#5612]
Hello 
I'm Using a CR10s-Pro V1 with a BL touch when I try and home the z-axis I get - Failed to verify BLTouch probe is raised; retrying (twice) then BLTouch failed to raise probe. I'm all out of ideas on how to make this work. Any help would be a life saver! 

thank you  

my Config file is below.,

[cr10-s-pro-hemrea-BLtouch.txt](https://github.com/Klipper3d/klipper/files/9001196/cr10-s-pro-hemrea-BLtouch.txt)

**Comment by Sineos** [comment]
Github is not used for support / feature requests as already stated when opening the Issue and detailed in above link. Please be so kind to place your support / feature request on [Klipper Discourse](https://klipper.discourse.group/)

Also attach your klippy.log there.
