### ISSUE TITLE
BLTouch stops working after cancelling a print job.

### ISSUE THREAD

**Issue by beatkipfer** [Klipper3d/klipper#5616]
If I "pause" and "cancel" a running print job BLTouch stops working doesn't matter what command I send.
The only thing I can do is a firmware_restart. If I don't so, it ends in a crash between hotend and bed.

Beside this I have the same issue reported here:
https://github.com/Klipper3d/klipper/issues/5229

Configuration is mainsail, btt octopuss, original BLTouch

**Comment by Sineos** [comment]
Github is not used for support / feature requests as already stated when opening the Issue and detailed in above link. Please be so kind to place your support / feature request on [Klipper Discourse](https://klipper.discourse.group/)
