### ISSUE TITLE
Extruder temperature lower than Klipper reports

### ISSUE THREAD

**Issue by Cabinfourus** [Klipper3d/klipper#5619]
I am trying to get my extruder temperatures correct but I am having issues. I am using a WINSINN HT-NTC100K sensor on my printer and when I try to set my extruder temperature, Klipper says the temps rise but when I check them with my heat gun, they are nowhere close. I have tried all the sensors listed in the Klipper manual but none of them made a difference. I ran PID on each of them and still no luck. When I set the extruder to 225, Klipper shows the temps rising but the actual temperature is about 90. I know this is something I am doing or inputting incorrectly but I can't seem to figure it out. Also, under the configuration settings, it refers to more temperature sensors I can use in my printer.cfg but I can't find these to try them. 
[klippy.log](https://github.com/Klipper3d/klipper/files/9015626/klippy.log)

**Comment by Sineos** [comment]
Github is not used for support / feature requests as already stated when opening the Issue and detailed in above link. Please be so kind to place your support / feature request on [Klipper Discourse](https://klipper.discourse.group/)
