### ISSUE TITLE
Problem with mesh

### ISSUE THREAD

**Issue by panik988** [Klipper3d/klipper#5626]
I have a problem with the BED_MESH_CALIBRATE that I cannot resolve in any way.

If I do a manual leveling of the bed and run a print without ABL I have a good first layer.

If, on the other hand, I do a print with the mesh of the bed, I have the front part totally raised from the bed and the rear part totally crushed until the bed scratches.

I use Klicky as a probe and it is mounted on the nozzle and trying to move it with my hand it does not seem to move and if I redo the mesh 10 times I always have the same reading.

I exclude the mechanical problem because otherwise I would have the problem even without the mesh and instead without this the first layer is good, however I have checked all the mechanics and I do not seem to detect anomalies.

Doing the leveling with BED_SCREWS_ADJUST with a thickness gauge and then launching SCREWS_TILT_CALCULATE also here tells me that I should level the plate by at least one full turn of the screw on the front.

I no longer know what to check and test, I am attaching the screens of the mesh and a video where the first layer with the mesh is visible, it seems that the plate is flat and he tries to compensate for the reading he made despite not being necessary.

This is my klipper config: https://github.com/panik988/vzbot13_bck

Thank you for the help

https://user-images.githubusercontent.com/83404637/177139893-f19d13af-4c04-4dba-b059-1c24041e5f8a.mp4

![mesh](https://user-images.githubusercontent.com/83404637/177139910-48af52d8-ce40-4720-8841-8d0a56015abc.jpg)
![2022-07-04_12h44_31](https://user-images.githubusercontent.com/83404637/177139956-5356559b-026f-4d97-953b-afa6e1a5c1ad.png)

**Comment by Sineos** [comment]
Github is not used for support / feature requests as already stated when opening the Issue and detailed in above link. Please be so kind to place your support / feature request on [Klipper Discourse](https://klipper.discourse.group/)

Also attach your `klippy.log` file there
