### ISSUE TITLE
Issues connecting to printer after reflashing

### ISSUE THREAD

**Issue by Martichoke** [Klipper3d/klipper#5631]
Hi,

I've had klipper working great and printing. Recently had to reflash the printer because I'm configuring input shaping with ACC.
The printer is a CR6 Max, same board as CR6 SE, AFAIK.
I have followed tried flashing both with SD (cannot confirm completed, no screen) and via serial;

pi@octopi:~/klipper $ sudo service klipper stop                              
pi@octopi:~/klipper $ make menuconfig
Loaded configuration '/home/pi/klipper/.config'
No change to configuration in '/home/pi/klipper/.config'
Loaded configuration '/home/pi/klipper/.config'
Configuration saved to '/home/pi/klipper/.config'
pi@octopi:~/klipper $ make flash FLASH_DEVICE=/dev/serial/by-id/usb-1a86_USB2.0-Serial-if00-port0
  Creating symbolic link out/board
  Building out/autoconf.h
  Compiling out/src/sched.o
  Compiling out/src/command.o
  Compiling out/src/basecmd.o
  Compiling out/src/debugcmds.o
  Compiling out/src/initial_pins.o
  Compiling out/src/gpiocmds.o
  Compiling out/src/stepper.o
  Compiling out/src/endstop.o
  Compiling out/src/trsync.o
  Compiling out/src/adccmds.o
  Compiling out/src/spicmds.o
  Compiling out/src/thermocouple.o
  Compiling out/src/i2ccmds.o
  Compiling out/src/pwmcmds.o
  Compiling out/src/spi_software.o
  Compiling out/src/sensor_adxl345.o
  Compiling out/src/sensor_angle.o
  Compiling out/src/sensor_mpu9250.o
  Compiling out/src/lcd_st7920.o
  Compiling out/src/lcd_hd44780.o
  Compiling out/src/buttons.o
  Compiling out/src/tmcuart.o
  Compiling out/src/neopixel.o
  Compiling out/src/pulse_counter.o
  Compiling out/src/stm32/watchdog.o
  Compiling out/src/stm32/gpio.o
  Compiling out/src/stm32/clockline.o
  Compiling out/src/generic/crc16_ccitt.o
  Compiling out/src/generic/armcm_boot.o
  Compiling out/src/generic/armcm_irq.o
  Compiling out/src/generic/armcm_reset.o
  Compiling out/src/../lib/stm32f1/system_stm32f1xx.o
  Compiling out/src/stm32/stm32f1.o
  Compiling out/src/generic/armcm_timer.o
  Compiling out/src/stm32/adc.o
  Compiling out/src/stm32/i2c.o
  Compiling out/src/stm32/spi.o
  Compiling out/src/stm32/serial.o
  Compiling out/src/generic/serial_irq.o
  Compiling out/src/stm32/hard_pwm.o
  Building out/compile_time_request.o
Version: v0.10.0-515-g24a1b50e
  Preprocessing out/src/generic/armcm_link.ld
  Linking out/klipper.elf
  Creating hex file out/klipper.bin
  Flashing out/klipper.bin to /dev/serial/by-id/usb-1a86_USB2.0-Serial-if00-port0

Failed to flash to /dev/serial/by-id/usb-1a86_USB2.0-Serial-if00-port0: Unable to find tty device

If the device is already in bootloader mode it can be flashed with the
following command:
  make flash FLASH_DEVICE=1eaf:0003
  OR
  make flash FLASH_DEVICE=1209:beba

If attempting to flash via 3.3V serial, then use:
  make serialflash FLASH_DEVICE=/dev/serial/by-id/usb-1a86_USB2.0-Serial-if00-port0

make: *** [src/stm32/Makefile:84: flash] Error 255

From the octoklipper terminal;
11:23:00 Klipper: Standby
11:23:11 Klipper: Connecting ...
11:23:11 Printer is not ready
11:23:11 Printer is not ready
The klippy host software is attempting to connect. Please
retry in a few moments.
11:23:11 Klipper: Connected to host
11:23:11 Connected to host via /tmp/printer @0bps
11:23:11 Firmware version: v0.10.0-515-g24a1b50e
[klippy.log](https://github.com/Klipper3d/klipper/files/9062754/klippy.log)

Thanks

**Comment by Martichoke** [comment]
I can reconnect now.
The issue is resolved when commenting out the lines needed for resonance testing. Any fixes for this?

![image](https://user-images.githubusercontent.com/52363390/177761801-2f7ec6e5-43d1-4db1-81b3-bd1f4eb81c19.png)

**Comment by Sineos** [comment]
Github is not used for support / feature requests as already stated when opening the Issue and detailed in above link. Please be so kind to place your support / feature request on [Klipper Discourse](https://klipper.discourse.group/)
