### ISSUE TITLE
BLTouch behaves erratically after klipper update

### ISSUE THREAD

**Issue by phongshader** [Klipper3d/klipper#5634]
BLTouch was working as expected until I updated klipper to v0.10.0-515-g24a1b50e. Unfortunately I don't remember what I updated from. I get these errors: **BLTouch failed to verify sensor state; retrying**, **Failed to verify BLTouch probe is raised; retrying** most times klipper recovers but sometimes it does not recover and errors out, **BLTouch failed to raise probe** and in the worst case klipper doesn't acknowledge the BLTouch trigger at all and the bed crashes into to the toolhead. I can sometimes get through a Z_TILT_ADJUST but I can never complete a G29.
[klippy.log.zip](https://github.com/Klipper3d/klipper/files/9074220/klippy.log.zip)

**Comment by Sineos** [comment]
Github is not used for support / feature requests as already stated when opening the Issue and detailed in above link. Please be so kind to place your support / feature request on [Klipper Discourse](https://klipper.discourse.group/)
