### ISSUE TITLE
BIQU B1 Klipper

### ISSUE THREAD

**Issue by lucasromeiro** [Klipper3d/klipper#5636]
Hello everyone, I hope you are well.
I'm starting in the world of klipper now.
I have a B1 BIQU.
Reading the documentation and looking for the files, I didn't find the BIQU B1 file.
There are other BIQU printers, but not the B1:

![image](https://user-images.githubusercontent.com/2086543/178114181-fa1cfb12-1b91-4f37-a2a2-05ac33987a3b.png)

My BIQU B1 uses SKR v1.4 MTB board and TFT35 LCD v3.0.

What files do I use in it, because I didn't find the appropriate file with my printer's name.

Another important question: How fast can my hardware print with klipper? Keeping good quality. I want to print fast!

Thank you for any help.

**Comment by Sineos** [comment]
Github is not used for support / feature requests as already stated when opening the Issue and detailed in above link. Please be so kind to place your support / feature request on [Klipper Discourse](https://klipper.discourse.group/)
