### ISSUE TITLE
Extruder motor vibrates but does not move

### ISSUE THREAD

**Issue by GitSiam** [Klipper3d/klipper#5637]
Hi, i'm using Klipper on SW_X1 with the original Motherboard and a raspbbery pi 3b+. I change the original extruder for a biqu_h2 (i also experiment some issue withe the original extruder). 

When i try to load, unload or print a file my Extruder stepper vibrates but does not move.

What i have tried :
- change the wiring setup --> fail
- put a brand new nema17 stepper --> Extruder motor vibrates but does not move
- Plug the extruder stepper on the X-axis --> work well

so the problem should comme from the firmware but i cant figure it out.
i check the other Printer.cfg from Github for the same configuration without any result.

do i need to change the motherboard or it can be fix in klipper parameter

Thanks for your help

[klippy.log](https://github.com/Klipper3d/klipper/files/9078079/klippy.log)

**Comment by Pieter005** [comment]
hello gitsiam

u may need to buy a new cable, i had the same problem on my i3 clone

**Comment by Sineos** [comment]
Github is not used for support / feature requests as already stated when opening the Issue and detailed in above link. Please be so kind to place your support / feature request on [Klipper Discourse](https://klipper.discourse.group/)

**Comment by GitSiam** [comment]
use github to share the results of work done to improve Klipper. We don't use github for requests.
