### ISSUE TITLE
[BUG] Getting 0.0C degrees from mcu temp on a STM32H743 BTT SKR3

### ISSUE THREAD

**Issue by NAPCAL** [Klipper3d/klipper#5639]
I have this in my printer.cfg for this board, but getting 0.0C flatline no change, no issues on Octopus V1.0 (STM32F466), Octopus Pro(STM32F466), SKR Pro V1.1(STM32F407), or GTR (STM32F407) boards.

[temperature_sensor SKR3_temp]
sensor_type: temperature_mcu
min_temp: 0
max_temp: 100

This is my initial setup for this board and only bench testing; no thermistors are plugged into this board
![Temps](https://user-images.githubusercontent.com/47440988/178174667-6d1b3b2f-3812-4a30-9366-613d7be14e60.png)
.

**Comment by Sineos** [comment]
Github is not used for support / feature requests as already stated when opening the Issue and detailed in above link. Please be so kind to place your support / feature request on [Klipper Discourse](https://klipper.discourse.group/)
