### ISSUE TITLE
Ender 3 4.2.2 st7920 LCD not working with recent update

### ISSUE THREAD

**Issue by jl1009** [Klipper3d/klipper#5641]
[klippy-Ender3 (2).log](https://github.com/Klipper3d/klipper/files/9098539/klippy-Ender3.2.log)

I recently flashed the latest Klipper firmware (v0.10.0-515) on my Ender 3 v4.2.2 board (previous flashed version from 06/20/22), and my lcd screen no longer works (remains on but blank). All other aspects of the printer works, and there were no hardware or config file changes. The screen is currently configured with the following: 

[display]
lcd_type: st7920
cs_pin: PB12
sclk_pin: PB13
sid_pin: PB15
encoder_pins: ^PB14, ^PB10
click_pin: ^!PB2

**Comment by Sineos** [comment]
Github is not used for support / feature requests as already stated when opening the Issue and detailed in above link. Please be so kind to place your support / feature request on [Klipper Discourse](https://klipper.discourse.group/)
