### ISSUE TITLE
Multipin and two fans with tachometer

### ISSUE THREAD

**Issue by int-0x03** [Klipper3d/klipper#5644]
Hello there. Sorry I want write to existing issue, but it closed right now. I have similar question as described here https://github.com/Klipper3d/klipper/issues/61

Is it possible use two fans in tandem with simple parallel connection, but use their tachometers? I need some way declare two fans, using same pin, but also using different tachometer_pin.

**Comment by Sineos** [comment]
Github is not used for support / feature requests as already stated when opening the Issue and detailed in above link. Please be so kind to place your support / feature request on [Klipper Discourse](https://klipper.discourse.group/)
