### ISSUE TITLE
UnicodeDecodeError: 'ascii' codec can't decode byte 0xff in position 0: ordinal not in range(128)

### ISSUE THREAD

**Issue by cfelicio** [Klipper3d/klipper#5645]
I'm using Klipper with Fluidd and it works fine (everything prints out), but at the very end of a print with the Palette 2 in connected mode, the MCU shuts down with this error:

Unhandled exception during run
Traceback (most recent call last):
  File "/home/pi/klipper/klippy/klippy.py", line 217, in run
    self.reactor.run()
  File "/home/pi/klipper/klippy/reactor.py", line 292, in run
    g_next.switch()
  File "/home/pi/klipper/klippy/reactor.py", line 340, in _dispatch_loop
    timeout = self._check_timers(eventtime, busy)
  File "/home/pi/klipper/klippy/reactor.py", line 158, in _check_timers
    t.waketime = waketime = t.callback(eventtime)
  File "/home/pi/klipper/klippy/extras/palette2.py", line 547, in _run_Read
    text_buffer = self.read_buffer + str(raw_bytes.decode())
UnicodeDecodeError: 'ascii' codec can't decode byte 0xff in position 0: ordinal not in range(128)
Transition to shutdown state: Unhandled exception during run
Dumping gcode input 0 blocks

See attached files for full log. Let me know if any questions. Thanks for your help! :-)

[201901MosaicKeychain1.p2pp.zip](https://github.com/Klipper3d/klipper/files/9108627/201901MosaicKeychain1.p2pp.zip)
[klippy.log](https://github.com/Klipper3d/klipper/files/9108624/klippy.log)

**Comment by cfelicio** [comment]
For reference: https://github.com/Klipper3d/klipper/pull/4057

**Comment by Sineos** [comment]
Ping @cmroche

**Comment by Sonnenwerk** [comment]
I had this issue today. It is caused e.g. by a german special sign "ü" or "ä", which is in the filename.
I used prusaslicer 2.4 and it was reproducable.

**Comment by cmroche** [comment]
Sorry for the delay folks, I'll take a look at the error and see if I can repro, or at least discard it following what @Sonnenwerk mentioned.

**Comment by Sineos** [comment]
#5694

**Comment by ReXT3D** [comment]
I'm not sure if https://github.com/Klipper3d/klipper/pull/5694 was also supposed to address the case that I encountered.  Issuing pretty quotes in place of regular double quotes still causes Klipper shutdown:

![image](https://user-images.githubusercontent.com/77699888/185689100-0002c796-aaa1-4da1-baac-1eb3f41ebf0f.png)

![image](https://user-images.githubusercontent.com/77699888/185689187-8c197700-36f9-47f7-b94d-0fc764592e11.png)

Thank you.

**Comment by Sineos** [comment]
> I'm not sure if #5694 was also supposed to address the case that I encountered. Issuing pretty quotes in place of regular double quotes still causes Klipper shutdown:

I think this is a completely different issue. Pretty quotes IMO were never meant to work in a Klipper command. This is like you would subsitute quotes by pretty quotes in C or JS etc and expect the compiler / runtime to like it.

**Comment by ReXT3D** [comment]
> I think this is a completely different issue. Pretty quotes IMO were never meant to work in a Klipper command. This is like you would subsitute quotes by pretty quotes in C or JS etc and expect the compiler / runtime to like it.

I understand and I agree.  I guess my only point here is that it would be nice to have a bit more graceful error handling than a machine shutdown.  In case someone goofs typing a console command 40 hours into a print, let's say...
