### ISSUE TITLE
how/where to connect hall filament width sensor on octopus v1.1

### ISSUE THREAD

**Issue by seebaer1976** [Klipper3d/klipper#5646]
Hi,
got the octopus v1.1.

now I have recreated the hall filament width sensor([link to hall filament width sensor](https://www.klipper3d.org/Hall_Filament_Width_Sensor.html)) and would like to connect it.
unfortunately I can't find anything to which pins I have to/can connect it.

does anyone have an idea?

Kind regards
mark

**Comment by JamesH1978** [comment]
I believe you needs a couple of pins capable of analog input with that sensor. I assume you could use a couple of the thermistor ports. But this is not a GitHub issue, this is used for triaged bugs to be fixed, not general help, it is better discussed on the discourse or the discord servers. 

Thanks
James

**Comment by seebaer1976** [comment]
OK thanks
my mistake
