### ISSUE TITLE
Cant compile atmega328/p firmware

### ISSUE THREAD

**Issue by iqubik** [Klipper3d/klipper#5647]
At last version i get:
Version: v0.10.0-521-gd91939c4
  Linking out/klipper.elf
/usr/lib/gcc/avr/5.4.0/../../../avr/bin/ld: out/klipper.elf section `.text' will not fit in region `text'
/usr/lib/gcc/avr/5.4.0/../../../avr/bin/ld: address 0x800b7c of out/klipper.elf section `.data' is not within region `data'
/usr/lib/gcc/avr/5.4.0/../../../avr/bin/ld: address 0x800ce8 of out/klipper.elf section `.bss' is not within region `data'
/usr/lib/gcc/avr/5.4.0/../../../avr/bin/ld: address 0x800b7c of out/klipper.elf section `.data' is not within region `data'
/usr/lib/gcc/avr/5.4.0/../../../avr/bin/ld: address 0x800ce8 of out/klipper.elf section `.bss' is not within region `data'
/usr/lib/gcc/avr/5.4.0/../../../avr/bin/ld: region `text' overflowed by 4546 bytes
collect2: error: ld returned 1 exit status
make: *** [Makefile:72: out/klipper.elf] Ошибка 1

**Comment by Sineos** [comment]
Github is not used for support / feature requests as already stated when opening the Issue and detailed in above link. Please be so kind to place your support / feature request on [Klipper Discourse](https://klipper.discourse.group/)

Also see: https://github.com/Klipper3d/klipper/issues/4938

**Comment by iqubik** [comment]
https://github.com/Klipper3d/klipper/issues/4938#issuecomment-1094246978
