### ISSUE TITLE
mcu 'mcu' shutdown: rescheduled timer in the past

### ISSUE THREAD

**Issue by madsemanden12** [Klipper3d/klipper#5650]
mcu 'mcu' shutdown: rescheduled timer in the past this generally occurs when the micro-controller has been requested to step at a rate higher than it is capable of obtaining.

I have been getting this error very frequently almost every third print and it's really getting annoying. I have a bigtreetech skr mini e3 v3.0 and a raspberry pi 4 with Fluid and i use superslicer as my slicer. I also know i'm not the only one getting this error since there are other's who have reported the same issue. Sadly non of the suggested solutions have worked for me. 
![Skærmbillede 2022-05-22 213201](https://user-images.githubusercontent.com/109626339/179838021-714b4b66-77d5-465d-930d-406e1b863698.png)
[klippy (1).log](https://github.com/Klipper3d/klipper/files/9144300/klippy.1.log)

**Comment by Sineos** [comment]
Github is not used for support / feature requests as already stated when opening the Issue and detailed in above link. Please be so kind to place your support / feature request on [Klipper Discourse](https://klipper.discourse.group/)
