### ISSUE TITLE
BTT GTR v1.0 and BTT TMC5160 v1.2 | Unable to write tmc spi 'stepper_x' register GLOBALSCALER"

### ISSUE THREAD

**Issue by DEAth1981** [Klipper3d/klipper#5653]
Good day!
So, I bought Mellow FLY-SHT42 and FLY-UTOC-3 boards, connected them. At the same time, I updated the firmware on all MCUs.
At the moment the configuration is:

RPi 3B+ => USART => BTT GTR 1.0 + BTT M5
and to the same RPi 3B+ => USB => FLY-UTOC-3 => CAN => FLY-SHT42

BTT GTR 1.0 has two drivers (X and Y) BTT TMC5160 v1.2 connected via SPI.

Before installing the "moving" of the head on the FLY-SHT42, everything worked fine, I decided to minimize the number of wires. :)

Now the error "TMC stepper_x failed to init: Unable to write tmc spi 'stepper_x' register GLOBALSCALER" and "TMC stepper_y failed to init: Unable to write tmc spi 'stepper_y' register GLOBALSCALER" appears periodically.

You can get rid of it after long and painful reboots (power off and on) of the 3D printer.
I did an experiment, deleted all the settings associated with FLY-SHT42, i.e. in fact, Klipper did not see this MCU, but the error remained.

How to fix?

P.S. If in the driver settings you notice the software SPI to the hardware one (spi_bus: spi3), then reboots no longer help.

[klippy.log](https://github.com/Klipper3d/klipper/files/9157418/klippy.log)

**Comment by Sineos** [comment]
Duplicate: https://klipper.discourse.group/t/klipper-state-shutdown-running-tmc5160-btt-octopus-1-1/3102/8
