### ISSUE TITLE
PWM fan on SKR mini E3 V3

### ISSUE THREAD

**Issue by SEModer** [Klipper3d/klipper#5655]
Hi!
I'm try enable hardware PWM on Klipper config To fan0 or fan1 or fan

And get this error.

> MCU Protocol error
> This is frequently caused by running an older version of the
> firmware on the MCU(s). Fix by recompiling and flashing the
> firmware.
> 
> Your Klipper version is: v0.10.0-526-ga151aa8c
> MCU(s) which should be updated:
> 
> Up-to-date MCU(s):
> mcu: Current version v0.10.0-526-ga151aa8c
> 
> Once the underlying issue is corrected, use the "RESTART"
> command to reload the config and restart the host software.
> 
> mcu 'mcu': Firmware constant 'PWM_MAX' not found

firmware compiled correctly for STM32G0B1

When fans are connected, with software PWM, the fans either shake hard or they squeak if try change cycle_time.
Tried Sunon 5015 24v maglev and Younuon 4020 dual ball/5015 24v

**Comment by Sineos** [comment]
Not supported on this chip currently.
See https://github.com/Klipper3d/klipper/pull/5657
