### ISSUE TITLE
Pin assignment on multi MCU

### ISSUE THREAD

**Issue by MermaidSystem** [Klipper3d/klipper#5659]
i've found a possible Bug with the usage of the same Pin in the same call on multi MCU.

i have two SKR2 Boards with the Driverprotection on Pin PC13.
I can release the protection but only on one Board.

The following code lines are working for one MCU
> [output_pin motor_power]
pin: PC13
value: 1< 

or

>[output_pin motor_power]
pin: z:PC13
value: 1<

But the assignment of both Pins with "pin: PC13, z:PC13" results in the Klippy-State Error "Unknown pin chip name 'PC13, z'"

**Comment by MermaidSystem** [comment]
I've found a work around for that problem, but it is not the most elegant solution.

>[multi_pin driver_enable]
pins: PC13, z:PC13

[output_pin motor_power]
pin: multi_pin:driver_enable
value: 1>

**Comment by Sineos** [comment]
Github is not used for support / feature requests as already stated when opening the Issue and detailed in above link. Please be so kind to place your support / feature request on [Klipper Discourse](https://klipper.discourse.group/)
