### ISSUE TITLE
SCARA Kinematics for new 3D printer

### ISSUE THREAD

**Issue by prestonmcmillian** [Klipper3d/klipper#5669]
Hello, recently myself and others have been working building a SCARA similar to the MP_SCARA configuration and we're interested in running klipper on it. We were wondering if we could receive some help in getting klipper working on the SCARA.
Thanks.

**Comment by Sineos** [comment]
Github is not used for support / feature requests as already stated when opening the Issue and detailed in above link. Please be so kind to place your support / feature request on [Klipper Discourse](https://klipper.discourse.group/)

It might make sense to post in the developer section, detailing how far you got in implementing the kinematic and where exactly you need help. You also might want to refer to https://www.klipper3d.org/Code_Overview.html#adding-new-kinematics and https://github.com/Klipper3d/klipper/commit/ec9cb3a1b302bddf10bde84fc87ae2a8ad6230b3

If you expect other developers to implement it, the best place is "Feature Request"
