### ISSUE TITLE
Filament sensor triggers on long G0 E command

### ISSUE THREAD

**Issue by RSurprenant** [Klipper3d/klipper#5670]
I've been using the BTT SFS V1.0 Smart Filament Sensor but it seems to trigger when sending long G0 E command.
When sending the long command, the sensor instantly detects a slip but I confirmed physically on the printer that  there is no slipping.
Trying to pinpoint the exact length of the movement I found that it triggered between 750 and 800mm. The length at which the trigger happens wasn't consistent.
The current fix is to send multiple G0 command of shorter length but it is not optimal.

Any help would be appreciated!
[klippy.log](https://github.com/Klipper3d/klipper/files/9221275/klippy.log)

**Comment by Sineos** [comment]
Github is not used for support / feature requests as already stated when opening the Issue and detailed in above link. Please be so kind to place your support / feature request on [Klipper Discourse](https://klipper.discourse.group/)
