### ISSUE TITLE
Invalid speed in 'G0 F0 X91.354 Y115.457 Z0.4'

### ISSUE THREAD

**Issue by mustytechy** [Klipper3d/klipper#5671]
great mate , i run in to error please after installation and i tried to print calibration cude but  i also get this error Invalid speed in 'G0 F0 X101.5 Y117.79 Z0.4' , please how can i fix it  and thanks in advance.

**Comment by Afterschnitzel** [comment]
This is because you try to run stepper with feedrate F0

https://github.com/Klipper3d/klipper/issues/173

**Comment by mustytechy** [comment]
I understand, but do you have any idea how to fix this please

**Comment by Sineos** [comment]
Github is not used for support / feature requests as already stated when opening the Issue and detailed in above link. Please be so kind to place your support / feature request on [Klipper Discourse](https://klipper.discourse.group/)

**Comment by Afterschnitzel** [comment]
It depends what slicer you use.
