### ISSUE TITLE
ADXL issue on RPi4b

### ISSUE THREAD

**Issue by SergedeParis** [Klipper3d/klipper#5690]
I guess I am not alone with this issue, and I am not sure that I post it at the right place.
My config works well on a Rpi 3b but when I use a RPi 4B -4Gb, I cannot connect klipper. The issue appears as soon as I enter the ADXL lines:
[mcu rpi]
serial: /tmp/klipper_host_mcu
[adxl345]
cs_pin: rpi:None
[resonance_tester]
accel_chip: adxl345
probe_points:
   127,127,20  # an example

Is there anything I did not see? 
Any help is welcome.
I attached the klippy.log and printer.cfg as a txt file.

[klippy (7).log](https://github.com/Klipper3d/klipper/files/9256518/klippy.7.log)
[printer.txt](https://github.com/Klipper3d/klipper/files/9256522/printer.txt)

**Comment by Sineos** [comment]
Github is not used for support / feature requests as already stated when opening the Issue and detailed in above link. Please be so kind to place your support / feature request on [Klipper Discourse](https://klipper.discourse.group/)
