### ISSUE TITLE
Gantry skew issue - each side of gantry should be homed individually

### ISSUE THREAD

**Issue by psyblue** [Klipper3d/klipper#5691]
I'm working on a large Cartesian format printer that has a relatively long gantry. 
It is driven by two Y steppers (stepper_y & stepper_y1)

The problem is that the gantry has a skew issue and the skew value changes every new boot.
I want to configure the printer to automatically adjust the X-aixs and the gantry to be orthogonal.
The first idea is using two endstops to correct it. 
Is it possible to configure Klipper like this? Do I use probing method? or any other suggestion?

**Comment by Sineos** [comment]
Github is not used for support / feature requests as already stated when opening the Issue and detailed in above link. Please be so kind to place your support / feature request on [Klipper Discourse](https://klipper.discourse.group/)
