### ISSUE TITLE
2-in 1-out hot end [extruder_stepper belted_extruder] not able to use tmc 2209 stepper driver capabilities.

### ISSUE THREAD

**Issue by MattKelly4D4B** [Klipper3d/klipper#5696]
Hello,  When I am setting up my 2in 1out nozzle, it says that "Option 'microsteps' in section 'belted_extruder' must be specified" but it is already in my 2nd extruder section.  Its like it expects it to be in the [2209 belted_extruder] section as well. Heres what I have:

[extruder_stepper belted_extruder]
extruder: ""
step_pin: PE6
dir_pin: !PC13	
enable_pin: !PE5
microsteps: 16
rotation_distance: 34.40860215053763

[tmc2209 belted_extruder]
uart_pin: PC14
run_current: 0.800
stealthchop_threshold: 999999

**Comment by Sineos** [comment]
Github is not used for support / feature requests as already stated when opening the Issue and detailed in above link. Please be so kind to place your support / feature request on [Klipper Discourse](https://klipper.discourse.group/)
