### ISSUE TITLE
`make menuconfig` not works if the parent directory contains spaces

### ISSUE THREAD

**Issue by sl1pkn07** [Klipper3d/klipper#5706]
if the parent directory contains spaces, `make menuconfig` fails

~~~
┌─┤[$]|[sl1pkn07]|[sL1pKn07]|[/media/COSAS/aplicaciones/Creality Ender 3/klipper]|
└───╼  make menuconfig
No change to configuration in '/media/COSAS/aplicaciones/Creality Ender 3/klipper/.config'
Loaded configuration '/media/COSAS/aplicaciones/Creality Ender 3/klipper/.config'
---snip----
~~~

but if move the main directory to one without spaces:

~~~
┌─┤[$]|[sl1pkn07]|[sL1pKn07]|[/media/COSAS/aplicaciones/klipper]|
└───╼  make menuconfig
(Top)
                                                                                                                                                                 Klipper Firmware Configuration
[ ] Enable extra low-level configuration options
    Micro-controller Architecture (Atmega AVR)  --->
    Processor model (atmega2560)  --->







[Space/Enter] Toggle/enter      [?] Help            [/] Search
[Q] Quit (prompts for save)     [ESC] Leave menu
~~~

start works

greetings

**Comment by sl1pkn07** [comment]
ping

**Comment by sl1pkn07** [comment]
ping

**Comment by Neko-vecter** [comment]
The best solution probably use “-” to replace space.

**Comment by Sineos** [comment]
Send a PR?

**Comment by sl1pkn07** [comment]
seems involved python scripts, so no, i cant. sorry

greetings

**Comment by sl1pkn07** [comment]
ping

**Comment by Neko-vecter** [comment]
I think this error is caused by menuconfig instead of klipper. 

More info in https://wiki.st.com/stm32mpu/wiki/Menuconfig_or_how_to_configure_kernel

**Comment by djessup** [comment]
Make and menuconfig both struggle with spaces. This is not a Klipper problem IMO.

**Comment by sl1pkn07** [comment]
ping

**Comment by Neko-vecter** [comment]
I checked the section on `make menuconfig` configuration. This is part of [Kconfiglib](https://github.com/ulfalizer/Kconfiglib) library. 
Which means you need to go to [Kconfiglib](https://github.com/ulfalizer/Kconfiglib) and open an issue.

**Comment by sl1pkn07** [comment]
https://github.com/ulfalizer/Kconfiglib/issues/125

done

**Comment by sl1pkn07** [comment]
ping again
