### ISSUE TITLE
The value 'runout' is not valid for SENSOR

### ISSUE THREAD

**Issue by valeria52** [Klipper3d/klipper#5708]
Unclear message / error: 09:38:00 The value 'runout' is not valid for SENSOR
What is the problem? Due to the error, no printing can be started.
What was done? Runout sensor was exchanged against BIGTREETECH Smart Filament Sensor

_[printer.cfg]_
#[filament_switch_sensor runout]
#pause_on_runout: True
#switch_pin: PA5

[filament_motion_sensor BIGTREETECH_Smart_Filament_Sensor]
detection_length: 10.0
#The minimum length of filament pulled through the sensor to trigger
#a state change on the switch_pin
#Default is 7 mm.
extruder: extruder
#The name of the extruder section this sensor is associated with.
#This parameter must be provided.
switch_pin: ^PA5
pause_on_runout: True
runout_gcode: FILAMENT_RUNOUT
event_delay: 5
pause_delay: 1
#See the "filament_switch_sensor" section for a description of the
#above parameters.

_[macros.cfg]_
[gcode_macro FILAMENT_RUNOUT]
description: FILAMENT_RUNOUT
gcode:
  M300 S1 P10
  M600
  M300 S1 P10

_[Versions]:_
klipper: v0.10.0-546-ga709ba43
KlipperScreen: v0.2.5-27-g036ba20
moonraker: v0.7.1-625-g413e3b2
mainsail: v2.2.1
System: OS-Packages

**Comment by Sineos** [comment]
Github is not used for support / feature requests as already stated when opening the Issue and detailed in above link. Please be so kind to place your support / feature request on [Klipper Discourse](https://klipper.discourse.group/)

Also attach your `klippy.log` there
