### ISSUE TITLE
MCU 'mcu' shutdown: Scheduled digital out event will exceed max_duration

### ISSUE THREAD

**Issue by Flyguy62** [Klipper3d/klipper#5716]
I have been having this issue for a while now. it happens every time the macro for clog or runout is run by the ERCF scripts. basically without fail. I have worked with ETTE the designer of the ercf and tried changing my macros. but nothing has really worked. i am thinking at this point that it could be a klipper issue.
<img width="1006" alt="Screen Shot 2022-08-18 at 8 41 00 AM" src="https://user-images.githubusercontent.com/85184129/185429062-732b46f7-a4e6-4e1f-87dd-bd71a1a44316.png">
[klippy (69).log](https://github.com/Klipper3d/klipper/files/9375002/klippy.69.log)

**Comment by Flyguy62** [comment]
also as an update it only causes the shutdown when the printer automatically detects runout or clog, when i call the script manually it completes just fine. heres the log file for that
[klippy (70).log](https://github.com/Klipper3d/klipper/files/9375201/klippy.70.log)
.

**Comment by Sineos** [comment]
As already noted when you opened this topic: GitHub shall only be used for development purposes. Please be so kind to open such support topics on [klipper.discourse.group](https://klipper.discourse.group/) and attach your klippy.log file there.
