### ISSUE TITLE
PID Calibration fails with Klipper but is fine with Marlin

### ISSUE THREAD

**Issue by podmore71** [Klipper3d/klipper#5719]
So this is not the first time I have installed Klipper on my Ender 3. I've had it running various times, but I just keep going back to Marlin and just using Octoprint. 
I am now triying again from scratch, but for some weird reason, every time I try to run a PID calibration of the hotend, it keeps failing.

My Printer:
Ender 3 running on a SKR E3 mini v1.2 board.
Raspberry Pi 3B+ ( tried i with Octopi and Klipper plugin, Mainsail and Fluidd)
My printer.cfg file is the same one I've been using every time I've ran it before, so I know that's not an issue, as it's just a copy of the example SKR E3 mini 1.2.cfg file.

If I switch back to Marlin and just run Octoprint on my Pi, then everything is fine. PID tuning works and I can print without any issues. I would just like to get Klipper setup again and give a another go.

Any ideas?

Andy

**Comment by Sineos** [comment]
As already noted when you opened this topic: GitHub shall only be used for development purposes. Please be so kind to open such support topics on [klipper.discourse.group](https://klipper.discourse.group/) and attach your klippy.log file there.

Also attach your klippy.log file there
