### ISSUE TITLE
(section 'z_calibration' is not a valid config section) Recently encountered after upgrading klipper and moonraker

### ISSUE THREAD

**Issue by gebioldhuang** [Klipper3d/klipper#5720]
![W{LM%_E0JO}GXOX~TJK8KD3](https://user-images.githubusercontent.com/111633137/185771308-ddfc6da6-d413-4f9a-ba09-03be59e7a491.png)
![6~QTS7R`THPO1MRG_A8DSPN](https://user-images.githubusercontent.com/111633137/185771347-00141ae9-ef5d-4658-8a01-855d7e610d9d.png)
>#####################################################################
# Z Calibration
#####################################################################
[z_calibration]
#   The X and Y coordinates (in mm) for clicking the nozzle on the
#   Z endstop.
nozzle_xy_position: 202,305
#   The X and Y coordinates (in mm) for clicking the probe's switch
#   on the Z endstop.
switch_xy_position: 195,291
#   The X and Y coordinates (in mm) for probing on the print surface
#   (e.g. the center point) These coordinates will be adapted by the
#   probe's X and Y offsets. The default is the relative_reference_index
#   of the configured bed_mesh. It will raise an error if there is no
#   probe_bed site and no bed_mesh with a relative_reference_index
#   configured.
bed_xy_position: 150,150
#   The trigger point offset of the used mag-probe switch.
#   This needs to be fined out manually.
#   A smaller value is more away from bed
switch_offset: 1.65
#   The maximum allowed deviation of the calculated offset.
#   If the offset exceeds this value, it will stop!
#   The default is 1.0 mm.
max_deviation: 2.0
#   The number of times to probe each point. The probed z-values
#   will be averaged. The default is from the probe's configuration.
#samples: default from "probe:samples" section
#   The maximum Z distance (in mm) that a sample may differ from other
#   samples. The default is from the probe's configuration.
#samples_tolerance: default from "probe:samples_tolerance" section
#   The number of times to retry if a sample is found that exceeds
#   samples_tolerance. The default is from the probe's configuration.
#samples_tolerance_retries: default from "probe:samples_tolerance_retries" section
#   The calculation method when sampling more than once - either
#   "median" or "average". The default is from the probe's configuration.
#samples_result: default from "probe:samples_result" section
#   The distance in mm to move up before moving to the next
#   position. The default is two times the z_offset from the probe's
#   configuration.
clearance: 2
#position_min: default from "stepper_z:position_min" section.
#   The moving speed in X and Y. The default is 50 mm/s.
speed: 150
#   Speed (in mm/s) of the Z axis when lifting the probe between
#   samples and clearance moves. The default is from the probe's
#   configuration.
#lift_speed: default from "probe:lift_speed" section
#   The fast probing speed (in mm/s) used, when probing_first_fast
#   is activated. The default is from the Z rail configuration.
#probing_speed: default from "stepper_z:homing_speed" section.
#   The slower speed (in mm/s) for probing the recorded samples.
#   The default is second_homing_speed of the Z rail configuration.
#probing_second_speed: default from "stepper_z:second_homing_speed" section.
#   Distance to backoff (in mm) before probing the next sample.
#   The default is homing_retract_dist from the Z rail configuration.
#probing_retract_dist: default from "stepper_z:homing_retract_dist" section.
#   If true, the first probing is done faster by the probing speed.
#   This is to get faster down and the result is not recorded as a
#   probing sample. The default is false.
probing_first_fast: true
#   A list of G-Code commands to execute prior to each calibration command.
#   See docs/Command_Templates.md for G-Code format. This can be used to
#   attach the probe.
start_gcode: _SET_Z_CURRENT VAL=HOME
             DETACH_PROBE
#   A list of G-Code commands to execute prior to each probing on the
#   mag-probe. See docs/Command_Templates.md for G-Code format. This can be
#   used to attach the probe after probing on the nozzle and before probing
#   on the mag-probe.
before_switch_gcode: ATTACH_PROBE
                     G0 Z20
#   A list of G-Code commands to execute after each calibration command.
#   See docs/Command_Templates.md for G-Code format. This can be used to
#   detach the probe afterwards.
end_gcode: _SET_Z_CURRENT
           DETACH_PROBE

**Comment by jakep82** [comment]
Z_calibration is a 3rd party module that is not a part of Klipper. Please note we also don't handle support questions on GitHub. In the future please use Discord or Discourse.
