### ISSUE TITLE
Blobbing at the end of every layer. Terrible stitch marks problem.

### ISSUE THREAD

**Issue by CoinNester** [Klipper3d/klipper#5728]
Hello,

This is in relation to Issue #516 that never was addressed or solved by the developers. 

https://github.com/Klipper3d/klipper/issues/516

I have spent dozens of hours and days and a lot of money converting to Klipper only to discover this issue that does not go away no matter what. It seems that the developers try to explain it away rather than actually fix the problem which is very frustrating because it renders this firmware useless when you are trying to obtain an accurately printed part (which can be achieved through either Repetier firmware or Marlin in my case). 

The problem is very simple. The print head pauses at the end of every layer before starting to retract and then travel or begin the next layer. This can not be mitigated by turning up the speed of anything and it can not go away through direct drive either though it will not be as apparent because there is less pressure build up in the filament tract. As soon as you start printing something like TPU on your direct drive, say goodbye to any quality finish because this problem will be very apparent.

I have tried all the possible settings options as per issue #516 and nothing has helped. As you increase the pressure advance, what happens is that as the head is heading towards the end of the layer, it thins out the extrusion but then it pauses like it always does and leaves a wide blob. 

Can someone please take this seriously and address the problem that hasn't been fixed for the past 4 years. I will provide further detail and evidence if needed. Thank you in advance. If for some ungodly reason I am writing about firmware issues in the wrong place, then please direct me to where this will indeed be read and addressed. Thank you again

**Comment by Sineos** [comment]
As already noted when you opened this topic: GitHub shall only be used for development purposes. Please be so kind to open such support or feature request topics on [Klipper Discourse](https://klipper.discourse.group/)
