### ISSUE TITLE
Move out of range error after QGL of VOron2.4

### ISSUE THREAD

**Issue by gratefulfrog** [Klipper3d/klipper#5731]
I have an occasional error:

Move out of range: 353.000 459.000 40.000 [103.0] 

after:
Home all
QGL
Home X
Home Y
Homz Z : causes this error 

As you  can see both the X and Y coordinates are way off since I have a 300x300 bed.

I've attached the logs and the printer.cfg and moonraker.conf

I am a qualified software scientist and happy to try to help debug this!

Cheers,
Bob
[Move Out of Range Error.zip](https://github.com/Klipper3d/klipper/files/9421915/Move.Out.of.Range.Error.zip)

**Comment by Sineos** [comment]
As already noted when you opened this topic: GitHub shall only be used for development purposes. Please be so kind to open such support or feature request topics on [Klipper Discourse](https://klipper.discourse.group/)
