### ISSUE TITLE
the ADXL345 can communicate in adxl345spi but klipper say no

### ISSUE THREAD

**Issue by harvyh1985** [Klipper3d/klipper#5738]
as title described ,when i use adxl345spi  from https://github.com/nagimov/adxl345spi i can got correct value like this:
....
time = 3.603, x = -49.402, y = 57.449, z = 115.805
time = 3.803, x = 78.898, y = -108.551, z = 115.613
time = 4.004, x = 0.000, y = 3.000, z = 0.777
time = 4.204, x = 0.000, y = 0.000, z = 0.000
time = 4.404, x = 6.000, y = 0.219, z = 0.000
time = 4.604, x = -88.391, y = -53.777, z = -107.555
time = 4.804, x = -86.000, y = 0.508, z = 0.000
25 samples read in 5.02 seconds with sampling rate 5.0 Hz

but same time i use  ACCELEROMETER_QUERY in octoprint ,it resturns:
Recv: // Invalid adxl345 id (got 0 vs e5).
Recv: // This is generally indicative of connection problems
Recv: // (e.g. faulty wiring) or a faulty adxl345 chip.
Recv: !! Invalid adxl345 id (got 0 vs e5).

why and how can i fix it?

**Comment by Sineos** [comment]
As already noted when you opened this topic: GitHub shall only be used for development purposes. Please be so kind to open such support or feature request topics on [Klipper Discourse](https://klipper.discourse.group/)
