### ISSUE TITLE
SKR 3 EZ SPI issue  spi 'stepper_z' register GLOBALSCALER

### ISSUE THREAD

**Issue by ninjadudexp** [Klipper3d/klipper#5739]
Unable to write tmc spi 'stepper_z' register GLOBALSCALER
Once the underlying issue is corrected, use the
"FIRMWARE_RESTART" command to reset the firmware, reload the
config, and restart the host software.
Printer is shutdown

```########################################
[tmc5160 stepper_x]
cs_pin: PD5
spi_bus: spi4
run_current: 0.800
hold_current: .5
stealthchop_threshold: 999999

[tmc5160 stepper_y]
cs_pin: PD0
spi_bus: spi4
run_current: 0.800
hold_current:.5
stealthchop_threshold: 999999


[tmc5160 stepper_z]
cs_pin: PE1
spi_bus: spi4
run_current: 0.650
hold_current:.5
stealthchop_threshold: 999999


[tmc5160 stepper_z1]
cs_pin: PD12
spi_bus: spi4
run_current: 0.650
hold_current:.5
stealthchop_threshold: 999999


[tmc5160 extruder]
cs_pin: PC6
spi_bus: spi4
run_current: 0.800
stealthchop_threshold: 999999
```

Klipper starts up, as soon as i hit home it gives me that error, and then all the fans start to go to max.
2209 with my full config ran just fine, and this was trouble shooted on discord with no luck.

[klippy (2).log](https://github.com/Klipper3d/klipper/files/9436962/klippy.2.log)

**Comment by Sineos** [comment]
As already noted when you opened this topic: GitHub shall only be used for development purposes. Please be so kind to open such support or feature request topics on [Klipper Discourse](https://klipper.discourse.group/)
