### ISSUE TITLE
Issue with Neopixels over 45 LED

### ISSUE THREAD

**Issue by Guilouz** [Klipper3d/klipper#5740]
How many LEDs does Klipper support?

Because I have strange issue, I have a 60 led ring (WS2812) with this config :

[neopixel RGB1]
pin: PD0
chain_count: 60
color_order: GRB
initial_RED: 1
initial_GREEN: 1
initial_BLUE: 1

[gcode_macro NEOPIXEL_ON]
description: Allumer les LEDs
gcode:
  SET_LED LED=RGB1 RED=1 GREEN=1 BLUE=1

[gcode_macro NEOPIXEL_OFF]
description: Eteindre les LEDs
gcode:
  SET_LED LED=RGB1 RED=0 GREEN=0 BLUE=0

      
[gcode_macro NEOPIXEL_BLUE]
description: Allumer les LEDs en bleu
gcode:
  SET_LED LED=RGB1 RED=0 GREEN=0 BLUE=1

[gcode_macro NEOPIXEL_RED]
description: Allumer les LEDs en rouge
gcode:
  SET_LED LED=RGB1 RED=1 GREEN=0 BLUE=0

[gcode_macro NEOPIXEL_GREEN]
description: Allumer les LEDs en vert
gcode:
  SET_LED LED=RGB1 RED=0 GREEN=1 BLUE=0

At startup all my 60 led light on to white. No problem.

If I light off led and light on again, only part of the leds light up but not the 60

If try to change another color, all my leds are not changed.
When I try to light off only part light off.

I have also tested with or without TRANSMIT parameters, same issue.

If I set as example chain_count: 30 all is working as expected. Max number led without issue is 45.

**Comment by JamesH1978** [comment]
Please use the klipper discord or the discourse for this. We do not use the GitHub issues for general support, we only use it for actual bugs.

**Comment by Guilouz** [comment]
@JamesH1978 Already posted on Discord without without answers...
