### ISSUE TITLE
BLTouch failed to deploy

### ISSUE THREAD

**Issue by jgm22** [Klipper3d/klipper#5742]
I have an issue with BLTOUCH v3.1 (genuine) on SKR3 EZ mainboard, attached log and cfg files.
The probe deploy and stow using debug commands, BLTOUCH_DEBUG COMMAND=pin_down, BLTOUCH_DEBUG COMMAND=pin_up, and report the output triggered or open when commands BLTOUCH_DEBUG COMMAND=touch_mode and QUERY_PROBE but using homing button fail to deploy the stroke, I can see the blue led flashing but nothing happen, the stroke does not deploy.
[klippy.zip](https://github.com/Klipper3d/klipper/files/9439754/klippy.zip)

**Comment by JamesH1978** [comment]
Please use the klipper discord or the discourse for this. We do not use the GitHub issues for general support, we only use it for actual bugs.
