### ISSUE TITLE
Heater Extruder not heating up at expected rate

### ISSUE THREAD

**Issue by Chaossully** [Klipper3d/klipper#5762]
@
[klippy (16).log](https://github.com/Klipper3d/klipper/files/9523031/klippy.16.log)

i'm having an issue trying to calibrate my nozzle is there anyone that can help me diagnose where my problem is?

**Comment by ZISQO** [comment]
verifying hotend, heating bed pinmap on your printer.cfg also incorrect command that pid for heating bed at 260 degree.
