### ISSUE TITLE
delta z_offset_apply_endstop unknown command

### ISSUE THREAD

**Issue by lnquang** [Klipper3d/klipper#5765]
unable to update baby steps since command is broken. only for delta printer.

**Comment by lnquang** [comment]
![image](https://user-images.githubusercontent.com/5865395/189345969-687f188d-9a94-4dc0-b4d1-21e24e7dcaf9.png)

**Comment by Sineos** [comment]
And as already stated when you opened the ticket: Issues here are for development only. Please be so kind to place your support / feature request on: [klipper.discourse.group](https://klipper.discourse.group/)

**Comment by lnquang** [comment]
this is a bug, not for help, please respond accordingly.

**Comment by Sineos** [comment]
If you can pinpoint the lines of code that are causing the bug, then we can continue here. Otherwise please be so kind to follow the directions above and also provide your klippy.log there.
This ticket will not be followed up any more.

**Comment by lnquang** [comment]
i am no developer, my klipper control 4 printers, 2 delta printers and 2 others, those delta printers did not recognize command above.

**Comment by jakep82** [comment]
There is no Z endstop on a delta, so it would be expected that this command doesn't work.

**Comment by lnquang** [comment]
right, you need somehow to saving babystepping, right now there is no way to save these adjustment.

**Comment by ksdfpr** [comment]
Hi, I have the same problem. If the save button doesnt work how can we save a new z offset (in easy way) permanently?
Now, every time I turn on the printer I have to remember to change z offset manually.
And why does it show this button if it doesn’t work on delta printers? Maybe this works??? Z_OFFSET_APPLY_PROBE
