### ISSUE TITLE
Where did the revamped PID Controller commands go?

### ISSUE THREAD

**Issue by Alexander-T-Moss** [Klipper3d/klipper#5770]
I was looking around for a way to set the PID values for my hotend/bed on the fly as I print at a wide range of temps and came across this, https://github.com/Klipper3d/klipper/pull/2507#issue-565728135, but can't find any documentation on the commands that where added. Do they still exist?

**Comment by JamesH1978** [comment]
These were not added, that PR was closed and not merged. I do not think he opened another one.

Thanks
James
