### ISSUE TITLE
Peculiar issue on G1

### ISSUE THREAD

**Issue by WackoKacko** [Klipper3d/klipper#5775]
Trying to get a polar printer set up. I run a g-code using a .cfg file with cartesian kinematics. keep everything the same, basically, when doing on .cfg with polar kinematics. Then I get the errors:

stepcompress o=0 i=0 c=57 a=0: Invalid sequence
Internal error on command:"G1"

I've attached a github link with my gcode, my successful .cfg, my unsuccessful .cfg, and my unsuccessful .cfg's klippy.log.

I'm running Klipper on Octoprint. This is a custom setup with a Raspberry Pi 4B, an Arduino Mega2560, and a RAMPs1.4. Printer parts custom. Unimportant, I think, but there it is. I slice using SuperSlicer.

Many thanks in advance.

https://github.com/WackoKacko/printingProblem

Here's the printer-to-be, btw:
![printer](https://user-images.githubusercontent.com/44558448/190497472-84efbe57-5034-48c6-aea5-ab265a32daa7.png)

[klippy_defiant.log](https://github.com/Klipper3d/klipper/files/9578602/klippy_defiant.log)

**Comment by Sineos** [comment]
And as already stated when you opened the ticket: Issues here are for development only. Please be so kind to place your support / feature request on: https://klipper.discourse.group/
