### ISSUE TITLE
ADXL345 installation Broke my Klipper

### ISSUE THREAD

**Issue by OBCGenji** [Klipper3d/klipper#5776]
So today I tried to connect a ADXL345 to do some calibrations, followed the instructions, https://www.klipper3d.org/Measuring_Resonances.html.
But that gave me issues. Looks like the Python is too old, tried up update it also. NO GO. Now my Klipper does not work anymore, tried flashing the firmware again but no more Klipper. Klippy not connected.
Can I fix it or must I format and start again, took me a long time to get it working fine on my Ender 5 plus. :(
Please what am I missing.
[klippy.log](https://github.com/Klipper3d/klipper/files/9586046/klippy.log)

**Comment by vladimir-poleh** [comment]
It seems that you have not installed secondary MCU for RPi. There are connection errors in the log.

https://www.klipper3d.org/RPi_microcontroller.html
