### ISSUE TITLE
Small correction to documentation

### ISSUE THREAD

**Issue by rssw** [Klipper3d/klipper#5779]
Hi!  Not sure where would be the best to post this, corrections welcome.

In the documentation, on the page @https://www.klipper3d.org/Command_Templates.html , in the section "Variables", in the gcode, the variable is declared as `variable_bed_temp: 0` but it should be `bed_temp: 0`

This is all. ;-)

**Comment by Ramalama2** [comment]
> Hi! Not sure where would be the best to post this, corrections welcome.
> 
> In the documentation, on the page @https://www.klipper3d.org/Command_Templates.html , in the section "Variables", in the gcode, the variable is declared as `variable_bed_temp: 0` but it should be `bed_temp: 0`
> 
> This is all. ;-)

Hi, i don't see the error 🤣
It's above declared as a variable and below called correctly either.

Cheers ✌️
