### ISSUE TITLE
[bug] G92 don't work as expected

### ISSUE THREAD

**Issue by goldjunge91** [Klipper3d/klipper#5786]
[klippy.log](https://github.com/Klipper3d/klipper/files/9630914/klippy.log)
Hi,

**### how i understand and how i use it on other printer.**
i turn on my printer (not homed) I enter into the console G92 X0 Y0 Z0 and all axes are homed.

**But what klipper do:**
G92 X0 Y0 Z0 work on all my printer (RRF3 / Marlin) and i use it for now more then 2-4 years,
but today i'm making some macros and to don't home every time i enter G92 X0 Y0 Z0 the values for the axis change but homing state are not changing.
![Screenshot 2022-09-23 074320](https://user-images.githubusercontent.com/30201929/191898568-45dd0703-ba9b-4d9f-bf3c-244c7af305a9.png)

**For me in my eyes its a bug in behavior of g92.
no matter what we call it it should be changed otherwise there is no way to move the machine without Z-safe home or so**

_offtopic:
and with klipper I'm starting to get a little annoyed the documentation is more bad than good, and every time is something and I have to search again because it is different from Marlin and RRF2 / RRF3 i like to try things out at the moment i just have to say reprap has the nose in front_

**Comment by JamesH1978** [comment]
G92 does not work that way in klipper. It is used to set offset position from the homed position. A home is still needed. 

See https://github.com/Klipper3d/klipper/issues/140

Klipper is not marlin or reprap, and it was never built to be or to replace those. We only try to support Gcode we have to for slicer compatibility, and favour extended gcode commands instead. It was never a goal to mimic those firmwares,

It is not a bug

Please use the discourse or discord to discuss further

Thanks
James
