### ISSUE TITLE
X-axis homing issue

### ISSUE THREAD

**Issue by boristouchstone** [Klipper3d/klipper#5796]
I didn't have this issue an hour ago, but it did occur sporadically over the last few weeks.

It seems to me that my printer already thinks that the x axis is at the 0 position during the homing routine.
It also appears to be triggered. I thought the x endstop might have stopped working - and since I can't get to the switch to replace it (I have a CR10v3), I decided to try sensorless homing instead.

However, the issue still persists.

[klippy (2).log](https://github.com/Klipper3d/klipper/files/9658904/klippy.2.log)

Edit: The homing issue has been resloved. The x axis no longer appears to be triggered and everything homes as it should. However, it did fails once and how when I try to perform a height map, my x and y axis are moving in the oppsite direction.

[klippy (3).log](https://github.com/Klipper3d/klipper/files/9663110/klippy.3.log)

Edit 2: The issue has returned. X axis is showing that it is triggered when its not.

[klippy (4).log](https://github.com/Klipper3d/klipper/files/9663246/klippy.4.log)

**Comment by Sineos** [comment]
And as already stated when you opened the ticket: Issues here are for development only. Please be so kind to place your support / feature request on: https://klipper.discourse.group/
