### ISSUE TITLE
STM32G0B1 board SPI1 boot loop

### ISSUE THREAD

**Issue by FranzPVal** [Klipper3d/klipper#5799]
### FIRST
This is a REAL bug.
I tried to find it myself looking into the klipper/src code but I found nothing - maybe it's the bootloader (sources?) for this µC...
### SECOND
If some admin mark this bug as "not on github" or close it so that none of the developers can give me more hints for fixing it, then I will NEVER ever try to participate on klipper as an developer. GitHub issues are there so that users can report bugs or requests. If you prefer to do this on Discord, fine but in this case a lot of reports are gone missing in this process.

### SPI1 bug
If I connect a ADXL345 to the SPI1 connector (PA5,6,7 + PB15) the firmware will not boot. No serial device pops up in the Linux host system.
When booting up the MCU there is a burst on SCK with a very short double pulse on MOSI - for this burst I don't find the source. If an ADXL345 connected to this port, SCK continues toggling (~250kHz) and the ADXL sends data to MISO. In this case, the STM32G0B1 is looping and don't boot. No USB serial connection pops up in the Linux host.
PB15 (used later for CS) is low at startup so the ADXL is in SPI mode.

controller board used: BTT Manta M8P equipped with a CB1 Linux compute module replacement.

If I plug in the ADXL board later - a few seconds after power-on - it works like expected and ACCELEROMETER_QUERY returns values.

Is here a condition that prevent the firmware from boot?
Is a bootloader within the first 8KiB doing some SPI stuff at start.

**Comment by KevinOConnor** [comment]
We don't use github to diagnose problems with a printer (not even problems due to real bugs).  We also don't use github to answer questions (not even questions on what we use github for). You can head over to Klipper Discourse if you wish to discuss these things.  This is your third ticket that we have now marked as "not on github" - please refrain from opening further tickets.

-Kevin
