### ISSUE TITLE
special characters in exlude objects causing problems

### ISSUE THREAD

**Issue by Zodiak1993** [Klipper3d/klipper#5813]
Hello, if you are using special characters for example "ö" in the name of your stl and create a gcode (with PrusaSlicer in my case) the print will not start. I am not sure if this is the expected behaviour. If this is not changeable maybe a warning would help users to find the problem. 
This happens only if you use [exclude_objects]

**Gcode after pre processing:**
`; Pre-Processed for Cancel-Object support by preprocess_cancellation v0.2.0
; 1 known objects
EXCLUDE_OBJECT_DEFINE NAME=testü_id_0_copy_0 CENTER=174.931,175.043 POLYGON=[[157.8,157.8],[157.8,192.2],[192.2,192.2],[192.2,157.8]]
;TYPE:Custom`

**Klippy Log Error:**
`UnicodeEncodeError: 'ascii' codec can't encode character u'\xfc' in position 50: ordinal not in range(128)`

[klippy(15).log](https://github.com/Klipper3d/klipper/files/9732786/klippy.15.log)

**Comment by Sineos** [comment]
https://github.com/Klipper3d/klipper/issues/4794

**Comment by Zodiak1993** [comment]
Thank you but in my case the filename is "testu.gcode" and the name of the object is "testü". I did not know that even the gcode file name itself has a problem with special characters.
But it is okay. I will be more careful when exporting files from fusion.
