### ISSUE TITLE
OverflowError: can't convert negative number to unsigned

### ISSUE THREAD

**Issue by cz12312388** [Klipper3d/klipper#5872]
Hello, I have a problem that I can't solve.
My onboard mcu is hc32, which is officially unadapted, so I found a ported klipper connection on GitHub as follows：[https://github.com/SteveGotthardt/klipper/tree/hc32f460_work](url)

Modified the serial port pin PA3 PA2 and masked the PA2 PA3 related code in src/hc32f460/adc.c src/hc32f460/hard_pwm.c

Boot and click reconnect firmware with OverflowError: can't convert negative number to unsigned

The log is as follows：
[klippy (5).log](https://github.com/Klipper3d/klipper/files/9919590/klippy.5.log)

**Comment by Sineos** [comment]
https://klipper.discourse.group/t/support-for-hdsc-chips-hc32f460
