### ISSUE TITLE
bl-touch on y-axis for a belt printer

### ISSUE THREAD

**Issue by JoshuaMorris** [Klipper3d/klipper#5884]
Is it possible to add an option to define which axis the bltouch is configured for? I would like to setup my belt printer to use a bl-touch, but it looks like that is only possible for the z-axis. Are there any options I'm not seenig in the documentation?

**Comment by Neko-vecter** [comment]
If my understanding currently. You have an infinite z? You wish to using y axis to probe the belt?

**Comment by JoshuaMorris** [comment]
> If my understanding currently. You have an infinite z? You wish to using y axis to probe the belt?

 Exactly

**Comment by Neko-vecter** [comment]
> > If my understanding currently. You have an infinite z? You wish to using y axis to probe the belt?
> 
> Exactly

Unfortunately the klipper currently does not really support infinite z. You probably need make a new kinematics to support this feature.
