### ISSUE TITLE
Feature request - Anet-A8 Plus printer.cfg

### ISSUE THREAD

**Issue by DragonicDefson** [Klipper3d/klipper#5896]
Request for Anet-A8 Plus config to be included in the Klipper repository.

I've written an printer.cfg for the Anet-A8 Plus printers.
It's in my repo:
[anet-a8-plus-klipper-config](https://github.com/DragonicDefson/anet-a8-plus-klipper-config)

Fabric standard, no moddifications on the printers.

**Comment by Sineos** [comment]
Thanks for your contribution @DragonicDefson 
Please either hand in a pull request or post your cfg in the config section on discourse: https://klipper.discourse.group/c/configs/14
