### ISSUE TITLE
Bug Connect Palette

### ISSUE THREAD

**Issue by 3dinova** [Klipper3d/klipper#5901]
I have a bug in my Klipper. I use Palette2 and it works fine. But now it updated and it just stopped working. The settings are fine, but when I give the command "PALETTE_CONNECT" an internal error occurs and Klipper shuts down.
![WhatsApp Image 2022-11-12 at 21 26 59](https://user-images.githubusercontent.com/114314000/201526603-b2f3f3bb-baab-49a8-8ea1-017ef3204886.jpeg)
![WhatsApp Image 2022-11-12 at 21 29 42](https://user-images.githubusercontent.com/114314000/201526613-935ab92e-b58e-4bf4-8110-f4c3107d3b17.jpeg)
[klippy.log](https://github.com/Klipper3d/klipper/files/9997427/klippy.log)

**Comment by 3dinova** [comment]
How is a bug reported to you? because even on discord they told me it was an update bug

**Comment by Sineos** [comment]
See the bot's comment here: https://github.com/Klipper3d/klipper/issues/5900#issuecomment-1312663425

We do not use GH to diagnose potential bugs or support individual printer issues. The official place is the [Klipper Discourse](https://klipper.discourse.group)
