### ISSUE TITLE
klipper not connecting to my ender 3s1 

### ISSUE THREAD

**Issue by MohanKishan** [Klipper3d/klipper#5904]
![image](https://user-images.githubusercontent.com/65703437/201913017-7eafccb5-d3ce-4a42-be5a-0902f86addf9.png)
[klippy (1).log](https://github.com/Klipper3d/klipper/files/10012337/klippy.1.log)
[message.txt](https://github.com/Klipper3d/klipper/files/10012338/message.txt)
klipper not connecting to my ender 3s1

**Comment by Sineos** [comment]
Please red and follow the direction given in the links above. It makes no sense to open one issue after the next. Ref https://github.com/Klipper3d/klipper/issues/5899
