### ISSUE TITLE
Heater extruder not heating at expected rate 

### ISSUE THREAD

**Issue by essigns** [Klipper3d/klipper#5915]
[klippy.log](https://github.com/Klipper3d/klipper/files/10099144/klippy.log)

I'm having a problem all the sudden with the HOT end! I've tried a bunch of stuff like  changed heating element, reloaded software and i can't seem to fix the problem. when i changed heating element it turn and i was drying the nitride paste at 90 degrees, the when i started printiing and I got this.  and this priinter has been running well over a year.

(hour later)
just ran a hot end PID. save config. hit print and the hot end turned off and got the same error again.

Klipper reports: SHUTDOWN

Heater extruder not heating at expected rate
See the 'verify_heater' section in docs/Config_Reference.md
for the parameters that control this check.

Once the underlying issue is corrected, use the
"FIRMWARE_RESTART" command to reset the firmware, reload the
config, and restart the host software.
Printer is shutdown

**Comment by nathancmatthews** [comment]
Is your part fan running?  I had issues with my part fan preventing the nozzle from maintaining temperatures at speed.
