### ISSUE TITLE
RepRap Display doesn't work properly

### ISSUE THREAD

**Issue by Kaan88** [Klipper3d/klipper#5989]
This is still an issue.

_Originally posted by @yoerivdm in https://github.com/Klipper3d/klipper/issues/5089#issuecomment-1200367957_

**Comment by Kaan88** [comment]
This is not a help request, it's a bug with Klipper and it's solved by the modified files in that older issue.

**Comment by BuddyBing** [comment]
+1 for this still being an issue so any chance we can have these modified files incorporated into a future release?
