### ISSUE TITLE
PROBE_CALIBRATE does not reflect reality

### ISSUE THREAD

**Issue by Blackolite** [Klipper3d/klipper#5997]
HI all,

When I use the PROBE_CALIBRATE command mainsail I can calibrate the nozzle with the paper test to 0.018.

Z position: -0.012 --> 0.008 <-- 0.018

But when i ACCEPT and SAVE_CONFIG I see the following offset:

''bltouch: z_offset: 3.680
The SAVE_CONFIG command will update the printer config file
with the above and restart the printer.''

This of course does not reflect reality and my printer is printing in mid air almost 4mm above the build plate.

Also the Bltouch Z_offset is commented after.
Even when I uncomment and set the right offset it still goes to 3.680 offset when I want to print

------------------SAVE_CONFIG--------------
#*# [bltouch]
#*# z_offset = 3.680

How can I correct this?

I have the following machine setup:
Printer: Ender 5 pro
Board: BTT SKR mini E3 V3
Extruder: Mosquito magnum  with Bondtech DDX V3

**Comment by 0xorial** [comment]
same issue on ender 3 s1 pro
