### ISSUE TITLE
Ender 3, Klipper/Mainsail no longer booting

### ISSUE THREAD

**Issue by duncan-rtfm** [Klipper3d/klipper#6197]
I've been successfully using Klipper for many months.  This morning, Klipper/Mainsail refuses to boot. 
The Ender 3 screen fires up, but remains blank.  I tried to log in to Klipper, but it could not make a connection.  I checked all cables and tried again.  Just the Ender 3 blue screen of death.  So I removed all cables except the power cable to the motherboard.  Same result.  I have now tried three different SKR Mini motherboards, and two Raspberry PI v4's.  No joy.  So I used KIAUH to update the software (Klipper, Mainsail, Moonraker).  Still no joy.  I've run out of ideas. 
[klippy.log](https://github.com/Klipper3d/klipper/files/11437443/klippy.log)
[moonraker (2).log](https://github.com/Klipper3d/klipper/files/11437445/moonraker.2.log)

**Comment by DaVinci-10** [comment]
could not open port /dev/serial/by-id/usb-Klipper_rp2040_E66198F1CF336429-if00
there is a new issue lately, check on klipper discord mainsail pinned comments for fix...

https://discord.com/channels/431557959978450984/704747457795588100/1103388450805260358

```A bug has been introduced in Debian Bullseye (which includes current MainsailOS), which prevents the symlinks in /dev/serial/by-id/ from being created. If your printer can't connect to the MCU anymore after a system update, you can check if it is caused by that bug by checking the installed version of udev with ```

```sudo su
sed -i '/^SUBSYSTEMS=="pci", ENV{ID_BUS}="pci".*/i SUBSYSTEMS=="usb", IMPORT{builtin}="usb_id", IMPORT{builtin}="hwdb --subsystem=usb"' /lib/udev/rules.d/60-serial.rules 
sed -i 's/^SUBSYSTEMS=="pci", ENV{ID_BUS}="pci".*/SUBSYSTEMS=="pci", ENV{ID_BUS}=="", ENV{ID_BUS}="pci", \\\
  ENV{ID_VENDOR_ID}="$attr{vendor}", ENV{ID_MODEL_ID}="$attr{device}", \\\
  IMPORT{builtin}="hwdb --subsystem=pci"/g' /lib/udev/rules.d/60-serial.rules 
sed -i '/ENV{MODALIAS}==".*/d' /lib/udev/rules.d/60-serial.rules
sudo reboot```
