### ISSUE TITLE
MCU Problem

### ISSUE THREAD

**Issue by GiacomoC00** [Klipper3d/klipper#6228]
I have klipper installed in my RPi4 and I am using it with my Sidewinder X2. Today I updated the OS packages and Klipper to the version released the 25th of May and after that I was not able to retrieve the MCU, even after I flashed the new built firmware in the printer motherboard. The only way to solve was to reinstall Raspberry OS (but this time without doing the OS packages update through Mainsail)and Klipper 1 commit back. Am I the only one that had this problem? Could it be the bug of Debian Bullseye version  247.3-7+deb112 (which includes current MainsailOS), which prevents the symlinks in /dev/serial/by-id/ from being created? Thank you.

**Comment by lnorton89** [comment]
I'm also experiencing this issue after update. 
![image](https://github.com/Klipper3d/klipper/assets/537513/2f42178e-82ea-47a5-aca9-54161f5ab8e7)

**Comment by GiacomoC00** [comment]
> I'm also experiencing this issue after update. ![image](https://user-images.githubusercontent.com/537513/241589204-2f42178e-82ea-47a5-aca9-54161f5ab8e7.png)

Hi, I solved doing this: https://klipper.discourse.group/t/debian-bullseye-bug-causing-klipper-to-no-longer-find-the-printer-board/8231

**Comment by lnorton89** [comment]
Confirmed this fixes, thanks buddy.
