### ISSUE TITLE
Apparent regression in variable PA

### ISSUE THREAD

**Issue by richfelker** [Klipper3d/klipper#6338]
Commit 29724a741106 moved the PA constant from being a property of the move to a property of the extruder. As far as I can tell, this broke configurations with variable PA, e.g. use of a lower K for bridges where there's no backpressure, by performing the integration with a single K that's whatever happens to have been the most-recent-set at the time of the iterative solver running, rather than using potentially differing-per-move K values in the integration.

My proposal for fixing this would be reverting the changes to chelper and the representation of PA K in trapq, and instead having the Python side copy the PA K from the relevant extruder object to the moves when adding them to the trapq.

**Comment by richfelker** [comment]
This is not a request for help, silly bot. It's a report citing a particular commit and describing the regression it introduced.

**Comment by Sineos** [comment]
As you surely noticed, this project has no possibility to open a new issue. To simply outsmart this fact seems rather brazen to me.
Please either open a PR or follow the given instructions.

**Comment by ganzgustav22** [comment]
@Sineos But apart from richfelker being a naughty boy, have you maybe considered fixing it?

**Comment by Sineos** [comment]
You might want to open a topic in Discourse as this is still not considered the right place to discuss it.

**Comment by ganzgustav22** [comment]
No thanks, I'm happy with Danger Klipper.

**Comment by richfelker** [comment]
Opened thread in the proper place here: https://klipper.discourse.group/t/regression-in-dynamic-pa/17260
