### ISSUE TITLE
Skew angle innacuracy (or maybe hidden math joke)

### ISSUE THREAD

**Issue by bharrisau** [Klipper3d/klipper#6614]
https://github.com/Klipper3d/klipper/blob/49c0ad6369670da574f550aa878ce9f6e1899e74/klippy/extras/skew_correction.py#L93-L95

So `calc_skew_factor` returns the tan of an angle - but the print statement is referring to it as the actual angle. Should probably be printing the arctan of the skew factor for correctness.

But if you apply the fundamental theorum of engineering - we know that `sin(x) = tan(x) = x`. So the actual printed values are still really close to the true angles.

**Comment by jakep82** [comment]
We don't use GitHub to report or track issues. 

https://www.klipper3d.org/Contact.html#i-found-a-bug-in-the-klipper-software
