### ISSUE TITLE
Multi pass look ahead

### ISSUE THREAD

**Issue by Cyberwizzard** [Klipper3d/klipper#662]
Does Klipper optimize the movements during look ahead once, or multiple times?

Teacup and Marlin optimize only pair wise, so single runs. This means large curves with many segments still run slow.

Does Klipper have this feature or is it planned?

**Comment by KevinOConnor** [comment]
Klipper implements the cornering algorithm described at: https://github.com/KevinOConnor/klipper/blob/master/docs/Kinematics.md#look-ahead .  It will be applied to all moves - large curves do not adversely impact Klipper.

-Kevin

**Comment by Cyberwizzard** [comment]
Sorry for the tardy reply, my dog ate the notification email.

That link describes how 2 adjacent moves are optimized. It does not say if this process is ran repeatedly.

For example, when considering move A and move B, both in the same direction, both for a very high speed (which is unattainable at that length), both with equal distance and very short.
```
    /\/\
    A B
```
The single pass look-ahead will optimize this and ideally do full acceleration during move A, full breaking on move B.
```
     /\
    /  \
    A B
```
Now move C enters the queue, same length, same insane top speed. Move B started faster, so B is now speeding up and then breaking, to allow move C to break during the entire move and end up at zero velocity.
```
     /\
    /  \
   /    \
   A B C
```
Now move D enters the queue, same length, same everything again. Now move C is converted into a move which speeds up for half the time, breaks the other half and D becomes a move that breaks from the exit speed from C to 0.
```
  /\/\
 /    \
/      \
A B C D
```
Now if the lookahead was using multiple passes, it would notice the exit-entry speed between B and C is not optimal and the breaking could be removed turning A and B into full acceleration moves, and C and D into full breaking moves.
```
   /\
  /  \
 /    \
/      \
A B C D
```
Coming back to my original question: does Klipper support multiple pass look-ahead, or pairwise / single pass?
