### ISSUE TITLE
klipper/gcode.py: SyntaxWarning: invalid escape sequence '\s'

### ISSUE THREAD

**Issue by matdibu** [Klipper3d/klipper#6636]
https://github.com/Klipper3d/klipper/blob/00cb683def53be4b437bfb3e3a637d2d5879946c/klippy/gcode.py#L409

`klipper/gcode.py:409: SyntaxWarning: invalid escape sequence '\s'`

I'm getting this error on a NixOS 23.11 system (with python 3.12.4)

Should that string be a regex literal? Or maybe with double backslashes ?

**Comment by jakep82** [comment]
We don't use GitHub to report or track issues.

https://www.klipper3d.org/Contact.html#i-found-a-bug-in-the-klipper-software
