### ISSUE TITLE
G4 add seconds

### ISSUE THREAD

**Issue by mikemerryguy** [Klipper3d/klipper#6641]
https://github.com/Klipper3d/klipper/blob/248d3dbf8bcda69a51e3a303862bbcc64a32119d/klippy/toolhead.py#L611C3-L614C26

def cmd_G4(self, params):
        # Dwell
        if 'S' in params:
            delay = self.get_float('S', params, minval=0.)
        else:
            delay = self.get_float('P', params, 0., minval=0.) / 1000.
        self.toolhead.dwell(delay)

**Comment by jakep82** [comment]
We don't use GitHub to report or track issues.

https://www.klipper3d.org/Contact.html#i-found-a-bug-in-the-klipper-software
