### ISSUE TITLE
M27 after M25 during vSD job cancels octoprint job

### ISSUE THREAD

**Issue by mamoit** [Klipper3d/klipper#877]
If we pause a print from the virtual SD card, there is a chance that Octoprint will issue an `M27` to get the status of the job right after the print has been canceled by the `M25`.
This will make klipper respond with a `Not SD printing.`, which will result in a canceled Octoprint job.
We can observe this by pausing during long Gcode sections such as long `G0`s or `G1`s.

This is not really a klipper problem, since in reality it is not printing from the sdcard, but instead it is paused.
Maybe Klipper could reply with the status of the print job even if it is paused somewhere around [this](https://github.com/KevinOConnor/klipper/blob/f6c2e8b4ebdac6a0b4b16c2799013b517ae1d77d/klippy/extras/virtual_sdcard.py#L125) conditional.

Octoprint's serial terminal:
```
Send: M27
Recv: SD printing byte 6199/23818682
Recv: ok
Changing monitoring state from "Printing from SD" to "Pausing"
Send: M25
Recv: ok
Send: M27
Recv: Not SD printing.
Changing monitoring state from "Pausing" to "Cancelling"
```

`klipper.log` not included since it does not provide any extra info in this specific issue.

**Comment by KevinOConnor** [comment]
I'm not sure I understand what's being reported.  If the print is paused, I would think Klipper should report that the print is not in progress.  Perhaps there should be some way for OctoPrint to be notified when the print resumes.

-Kevin

**Comment by mamoit** [comment]
The problem is exactly what you described. It is a race condition basically.
If you use octoprint you can easily reproduce this race condition by pausing and resuming several times in a long command print (like a cube).
It seems to be indeed an octoprint issue and not a klipper one.
Is anybody else capable of reproducing this issue or is it just me?
I'm using Octoprint 1.3.9.

**Comment by KevinOConnor** [comment]
I agree that this sounds like an OctoPrint issue.  I'm not sure there's anything Klipper can reasonably do about it.  (If the print is paused, it must respond that the print is paused.)

-Kevin
